// Explicitly synthetic UI verification data; this server is never deployed.
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {BUSINESS_ROUTINE_CATALOG} from '../src/business-routine-catalog.ts';
import {nextCheckRun} from '../src/check-schedule.ts';
import {CREDIT_PACKS,PLANS,freePeriod} from '../src/billing/plans.ts';
const argument=name=>process.argv.find(value=>value.startsWith(`--${name}=`))?.slice(name.length+3);
const harnessEvidencePath=argument('harness-evidence');
const harnessEvidence=harnessEvidencePath?JSON.parse(await readFile(resolve(harnessEvidencePath),'utf8')):null;
if(harnessEvidence&&(!harnessEvidence.synthetic||!harnessEvidence.result?.passed||harnessEvidence.result.run?.status!=='ready'||harnessEvidence.result.report?.id!==harnessEvidence.result.run.id))throw new Error('Use an accepted, synthetic-input Workers AI harness evidence file.');
const role=argument('role')??'owner',port=Number(argument('port')??5185);
if(!['owner','manager','staff','viewer','billing'].includes(role)||!Number.isInteger(port)||port<1024||port>65535)throw new Error('Use --role=owner|manager|staff|viewer|billing and --port=1024..65535.');
const signedOut=process.argv.includes('--signed-out');
const longConversation=process.argv.includes('--long-conversation');
const keyboardViewportPreview=process.argv.includes('--keyboard-viewport-preview');
const voiceLayoutPreview=process.argv.includes('--voice-layout-preview');
const conversationDelay=Number(argument('conversation-delay-ms')??0);
if(!Number.isInteger(conversationDelay)||conversationDelay<0||conversationDelay>10000)throw new Error('Use --conversation-delay-ms=0..10000 for synthetic delayed replies.');
const conversationFixture=longConversation?Array.from({length:12},(_,index)=>({role:index%2?'assistant':'user',content:index%2?'Synthetic conversation for scrolling verification. Review the saved appointment notes, prepare a concise handoff checklist, and keep each suggested action as an editable draft. The conversation should scroll independently while the composer and navigation remain reachable.\n\nThis preview uses invented test records only. No AI inference, external messages, booking changes, or payments occur.':'Help me plan a useful appointment preparation routine using the saved business context. Show the next steps clearly.'})):[];
const revokeAfterOverview=process.argv.includes('--revoke-after-overview');
const longName=process.argv.includes('--long-name');
const emptyAgent=process.argv.includes('--empty-agent');
if(harnessEvidence&&(emptyAgent||longName))throw new Error('--harness-evidence cannot be combined with --empty-agent or --long-name.');
// Business creation and saved-profile names both allow at most 160 characters.
const businessName=harnessEvidence?'Cedar Bike Service · synthetic acceptance':longName?'Willow Community Wellness and Creative Services for Families, Independent Professionals, Neighborhood Shops, and Local Business Owners Across the Hudson Valley '.repeat(2).slice(0,160):'Willow Studio';
const businessProfile=harnessEvidence?{name:businessName,assistantName:'Mayor Cedar',industry:'Neighborhood bicycle repair workshop',services:['Commuter bicycle repairs','Brake adjustments','Flat-tire repair','Seasonal maintenance'],locations:['Brooklyn, New York'],staff:[],timeZone:'America/New_York',businessGoals:['Build a useful repeat-maintenance process'],bottlenecks:['Maintenance follow-up handoffs are not documented'],currentTools:['Mayor internal tasks']}:{name:businessName,description:'Synthetic business used for interface verification.',services:['Consultations'],timeZone:'America/New_York'};
const requests=[];let revoked=false;
const tenant='a'.repeat(32),customers=[{id:randomUUID(),name:'Jordan Lee',email:'jordan@example.test',phone:null,revision:1},{id:randomUUID(),name:'Alex Morgan',email:'alex@example.test',phone:'+12025550123',revision:1}];
const zone='America/New_York';const day=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let tasks=[{id:randomUUID(),title:'Prepare tomorrow’s appointment notes',dueAt:null,priority:'normal',status:'open',revision:1,customer:null},{id:randomUUID(),title:'Check supplies for next week',dueAt:null,priority:'normal',status:'open',revision:1,customer:null}],appointments=[{id:randomUUID(),input:{title:'Jordan’s appointment',appointmentType:'Consultation',start:day+'T16:00:00-04:00',end:day+'T16:30:00-04:00',attendees:[]},status:'confirmed',customer:customers[0],canCheck:true},{id:randomUUID(),input:{title:'Alex’s appointment',appointmentType:'Follow-up',start:day+'T17:00:00-04:00',end:day+'T17:30:00-04:00',attendees:[]},status:'confirmed',customer:customers[1],canCheck:true}];
const futureDay=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+21*86400000)),futureOffset=new Intl.DateTimeFormat('en-US',{timeZone:zone,timeZoneName:'longOffset'}).formatToParts(new Date(futureDay+'T12:00:00Z')).find(part=>part.type==='timeZoneName').value.replace('GMT','');
const futureStart=Date.parse(futureDay+'T16:00:00'+futureOffset);
appointments.push({id:randomUUID(),input:{title:'Jordan’s follow-up in three weeks',appointmentType:'Consultation',start:new Date(futureStart).toISOString(),end:new Date(futureStart+30*60000).toISOString(),attendees:[]},status:'confirmed',customer:customers[0],canCheck:true});
// Matches the scheduling policy contract without loading Worker-only transitive imports.
const policy={timeZone:zone,weeklyHours:Array.from({length:7},(_,day)=>({day,startMinute:540,endMinute:1080})),closedDates:[],appointmentTypes:[{name:'Consultation',durationMinutes:30,bufferBeforeMinutes:0,bufferAfterMinutes:0}],staff:[],minimumNoticeMinutes:0,maximumAdvanceDays:90,cancellationNoticeMinutes:60};
const localDate=time=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time));
const overlapsDay=(appointment,date)=>localDate(Date.parse(appointment.input.start))<=date&&localDate(Date.parse(appointment.input.end)-1)>=date;
const linkedCustomer=id=>id?customers.find(customer=>customer.id===id):null;
const proposals=new Map();let callbackOpen=true;
const routineScope='Synthetic preview: brief and records are test data. No business was reviewed, no schedule is executed, and no message is sent.';
let routineConfig={enabled:false,templateIds:['daily-priorities'],schedule:null,revision:0,nextRunAt:null,lastRunAt:null,lastStatus:null,running:false},routineBrief=null;const routineRuns=new Map();
const harnessScope=harnessEvidence?'Recorded Workers AI report using the exact synthetic Cedar Bike probe inputs. This preview replays the saved report; it makes no model calls, reads no real mailbox or external calendar, and runs no automation. Preview writes affect only in-memory test records.':'Synthetic preview: reports, goals, and suggested experiments are test data. No AI model, real mailbox, external calendar, or automation is executed.';
const harnessTools=['profile','tasks','customers','bookings','goals','connector_status','gmail_unread','calendar_openings'];
const harnessBuiltins=BUSINESS_ROUTINE_CATALOG.map(item=>({id:'builtin:'+item.id,title:item.title,instructions:item.assistantPrompt,description:item.description,steps:item.steps,allowedTools:harnessTools.slice(0,6)}));
let harnessGoals=[{id:randomUUID(),revision:1,title:'Build a dependable customer follow-up routine',description:'Prepare useful follow-up drafts for review and measure progress with manually entered values.',metric:{baseline:0,current:4,target:10,unit:'reviewed follow-ups'},deadline:null,archived:false}],harnessSkills=[{id:randomUUID(),revision:1,title:'Prepare consultation notes',instructions:'Read the saved business profile and Mayor bookings. Draft a short checklist for the owner. State missing customer needs instead of inventing them.',allowedTools:['profile','bookings','goals'],archived:false}];
let harnessIdentity={revision:1,displayName:'Mayor',mission:'Help this synthetic local business choose useful next steps.',tone:'warm',principles:['Check saved records before making claims.','Keep messages and bookings under the owner’s control.'],workingStyle:'Be concise. Separate facts, suggested experiments, and decisions.'};
let harnessConfig={revision:1,enabled:false,goalIds:[harnessGoals[0].id],skillIds:['builtin:daily-priorities'],connectorOptions:{},schedule:{frequency:'weekdays',hour:9,minute:0,timeZone:zone},nextRunAt:null,lastRunAt:null,lastStatus:null,running:false};
const harnessRuns=new Map(),harnessCreates=new Map(),harnessTaskProposals=new Map(),harnessTaskReceipts=new Map();let harnessHistory=[];
function buildHarnessReport(id){
 const now=Date.now(),open=tasks.filter(task=>task.status==='open'),activeGoals=harnessGoals.filter(goal=>!goal.archived&&harnessConfig.goalIds.includes(goal.id));
 const sources=[{id:'profile:'+tenant,kind:'Saved profile',detail:businessName+' · consultations'},...tasks.map(task=>({id:'task:'+task.id,kind:'Internal task',detail:task.title+' · '+task.status})),...appointments.map(appointment=>({id:'booking:'+appointment.id,kind:'Mayor booking',detail:appointment.input.title+' · '+appointment.input.start})),...customers.map(customer=>({id:'customer:'+customer.id,kind:'Saved customer',detail:customer.name+' · synthetic customer record'}))];
 return {id,generatedAt:new Date(now).toISOString(),sources,summary:'Synthetic review: prepare your next consultation, review the unverified callback request, and try a measurable follow-up experiment. Suggested actions are drafts for your review.',goalProgress:activeGoals.map(goal=>({goalId:goal.id,title:goal.title,metric:goal.metric,progress:goal.metric&&goal.metric.target!==goal.metric.baseline?Math.max(0,Math.min(1,(goal.metric.current-goal.metric.baseline)/(goal.metric.target-goal.metric.baseline))):null,source:'manual_entry'})),metrics:[{key:'open_tasks',label:'Open tasks',value:open.length},{key:'overdue_tasks',label:'Overdue tasks',value:open.filter(task=>task.dueAt&&Date.parse(task.dueAt)<now).length},{key:'pending_callbacks',label:'Pending callbacks',value:callbackOpen?1:0},{key:'bookings_next_7_days',label:'Confirmed Mayor bookings · next 7 days',value:appointments.filter(appointment=>appointment.status==='confirmed'&&Date.parse(appointment.input.start)>=now&&Date.parse(appointment.input.start)<now+7*86400000).length},{key:'saved_customers',label:'Saved customer records',value:customers.length},{key:'customers_with_contact',label:'Records with a contact field',value:customers.filter(customer=>customer.email?.trim()||customer.phone?.trim()).length},{key:'revenue',label:'Revenue · not recorded',value:null}],priorities:open.slice(0,2).map(task=>({title:task.title,detail:'An open task from this synthetic workspace. Review the saved appointment context before deciding what to prepare.',sourceIds:['task:'+task.id]})),taskDrafts:[{id:randomUUID(),title:'Prepare a consultation checklist',detail:'Draft a short preparation checklist for the next Mayor booking. Confirm the customer’s needs before filling in details.',priority:'normal',dueAt:null,customerId:null,goalIds:activeGoals.map(goal=>goal.id),skillIds:harnessConfig.skillIds,sourceIds:['booking:'+appointments[0].id,'profile:'+tenant],acceptedTaskId:null}],experiments:[{id:randomUUID(),title:'Try a small follow-up checklist',hypothesis:'A consistent checklist may make reviewed follow-ups easier to prepare.',measure:'Manually record how many drafts you review. This is an experiment, not a forecast of revenue.',goalIds:activeGoals.map(goal=>goal.id),skillIds:harnessConfig.skillIds,sourceIds:customers.map(customer=>'customer:'+customer.id)}],toolTrace:[{tool:'profile',status:'completed',detail:'Read the synthetic saved profile.'},{tool:'tasks',status:'completed',detail:`Read ${tasks.length} synthetic tasks.`},{tool:'customers',status:'completed',detail:`Counted ${customers.length} synthetic saved customers.`},{tool:'gmail_unread',status:'skipped',detail:'No real mailbox is read by this preview.'}],gaps:['Revenue, customer needs, purchase history, and external reviews are not measured in this synthetic preview.'],scope:harnessScope};
}
const initialHarnessRun={id:randomUUID(),status:'ready',trigger:'manual',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),errorCode:null,replyAttemptCounted:true};let harnessReport=buildHarnessReport(initialHarnessRun.id);harnessHistory=[initialHarnessRun];
if(harnessEvidence){
 const result=harnessEvidence.result,report=structuredClone(result.report),goal=report.goalProgress.find(item=>item.title==='Grow repeat service bookings'),taskSource=report.sources?.find(item=>item.kind==='task'),skillId=report.taskDrafts[0]?.skillIds[0]??report.experiments[0]?.skillIds[0];
 if(!goal||!taskSource?.id.startsWith('task:')||!taskSource.detail.includes('Review which maintenance notes the workshop already records')||!skillId||!report.sources.some(item=>item.id==='profile:confirmed'&&item.detail.includes(businessName)))throw new Error('This preview maps the accepted Cedar Bike Service probe records only.');
 customers.splice(0);appointments=[];callbackOpen=false;
 tasks=[{id:taskSource.id.slice(5),title:'Review which maintenance notes the workshop already records',dueAt:null,priority:'normal',status:'open',revision:1,customer:null}];
 harnessGoals=[{id:goal.goalId,revision:1,title:goal.title,description:'The owner entered these monthly figures. They have not been verified against sales records.',metric:structuredClone(goal.metric),deadline:null,archived:false}];
 harnessSkills=[{id:skillId,revision:1,title:'Retention planning',instructions:'Suggest one reversible maintenance-retention experiment and one useful internal planning task based on the supplied goal and saved workshop records. Avoid duplicating open tasks. Treat every suggestion as a draft. Do not invent contact consent, sales history, response times or customer information.',allowedTools:['profile','tasks','goals','connector_status'],archived:false}];
 harnessIdentity={revision:1,displayName:'Mayor Cedar',mission:'Help this neighborhood workshop stay organized and learn whether a repeat-maintenance process helps.',tone:'direct',principles:['Use recorded facts','Ask before customer-facing actions'],workingStyle:'Choose small practical next steps and describe how to measure a proposed experiment.'};
 harnessConfig={revision:1,enabled:false,goalIds:[goal.goalId],skillIds:[skillId],connectorOptions:{},schedule:null,nextRunAt:null,lastRunAt:result.run.updatedAt,lastStatus:'ready',running:false};
 harnessReport=report;harnessHistory=structuredClone(result.history); 
}
if(emptyAgent){harnessGoals=[];harnessSkills=[];harnessIdentity={revision:0,displayName:'Mayor',mission:'',tone:'warm',principles:[],workingStyle:''};harnessConfig={revision:0,enabled:false,goalIds:[],skillIds:['builtin:daily-priorities'],connectorOptions:{},schedule:null,nextRunAt:null,lastRunAt:null,lastStatus:null,running:false};harnessReport=null;harnessHistory=[];}
function harnessState(){return {agent:{id:tenant,label:'Business agent'},identity:harnessIdentity,goals:harnessGoals,skills:harnessSkills,builtins:harnessBuiltins,allowedTools:harnessTools,config:harnessConfig,latestReport:harnessReport,history:harnessHistory.slice(0,10),connectors:{gmail:{available:false,connections:[],scope:'No real mailbox is connected to this synthetic preview.'},calendar:{available:!harnessEvidence,timeZone:zone,appointmentTypes:harnessEvidence?[]:policy.appointmentTypes.map(type=>({name:type.name,staff:[]})),scope:harnessEvidence?'No calendar was connected in the recorded synthetic probe.':'Synthetic policy only. No external calendar openings are read.'}},scope:harnessScope};}
const source={scope:'Appointments booked through Mayor. Other events in your connected calendar are not imported.'};
const callback={id:randomUUID(),number:'+12025550126',reason:'human_assistance',createdAt:new Date().toISOString()};
const json=(response,data,status=200)=>{response.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});response.end(JSON.stringify(data));};
const server=http.createServer(async(request,response)=>{try{const url=new URL(request.url,`http://127.0.0.1:${port}`);response.once('finish',()=>{if(url.pathname.startsWith('/api/'))requests.push({method:request.method,path:url.pathname,status:response.statusCode});});let body={};if(request.method==='POST'){let raw='';for await(const chunk of request)raw+=chunk;body=JSON.parse(raw||'{}');}
 const route=url.pathname.replace('/api/businesses/'+tenant,'');
 if(route==='/connections'&&request.method==='GET')return json(response,{connections:[],builtIn:[],limits:{connections:10,outboundPerDay:100},scope:'Synthetic UI preview; no external service is contacted.'});
 if(route==='/mcp/tokens'&&request.method==='GET')return json(response,{tokens:[],endpoint:'http://127.0.0.1:'+port+'/mcp'});
 if(url.pathname==='/api/auth/grants')return json(response,{grants:[]});
 if(route==='/calendars/selected')return json(response,{selection:null});

 if(url.pathname==='/__preview__/requests')return json(response,{synthetic:true,role,signedOut,revoked,requests});
 if(url.pathname==='/__preview__/harness-evidence')return json(response,{recordedWorkersAi:Boolean(harnessEvidence),syntheticInputs:true,model:harnessEvidence?.result.model??null,generatedAt:harnessEvidence?.result.report.generatedAt??null,scope:harnessScope});
 if(url.pathname==='/api/auth/capabilities')return json(response,{providers:{google:{configured:true,capabilities:[{id:'calendar_manage',label:'Calendar',enabled:true},{id:'gmail_read',label:'Gmail',enabled:false}]},microsoft:{configured:false,capabilities:[]},zoho:{configured:false,capabilities:[]}}});
 if(url.pathname==='/api/auth/get-session')return json(response,signedOut?null:{user:{id:`preview-${role}`,email:`${role}@example.test`},session:{id:'synthetic-preview'}});
 if(url.pathname==='/api/businesses')return json(response,{businesses:[{id:tenant,name:harnessEvidence||longName?businessName:'Willow Studio · test workspace',role}]});
 if(revoked&&url.pathname.startsWith('/api/'))return json(response,{error:'permission_denied',message:'Synthetic preview: workspace access was removed.'},403);
 if(role==='billing'&&route==='/billing/sync'&&request.method==='POST')return json(response,{synced:false,message:'Synthetic preview keeps the billing fixture unchanged.'});
 if(role==='billing'&&url.pathname.startsWith('/api/')&&(route!=='/billing'||request.method!=='GET'))return json(response,{error:'permission_denied',message:'Synthetic billing role cannot read business profiles, conversations, or workday records.'},403);
 if(!['owner','manager'].includes(role)&&/^\/(?:overview|tasks|customers|agenda|callbacks|routines|harness|appointments|appointment-changes|availability|bookings)(?:\/|$)/.test(route))return json(response,{error:'permission_denied',message:'Only owners and managers manage shared records in this synthetic workspace.'},403);
 if(role==='viewer'&&(route==='/conversation'||url.pathname==='/api/voice/session'))return json(response,{error:'permission_denied',message:'The synthetic viewer role has no conversation access.'},403);
 if(['staff','viewer'].includes(role)&&route==='/profile'&&request.method!=='GET')return json(response,{error:'permission_denied',message:'This synthetic role can read business details, not change them.'},403);
 if(!['owner','billing'].includes(role)&&route.startsWith('/billing/')&&request.method==='POST')return json(response,{error:'permission_denied',message:'Only an owner or billing role manages payments in this synthetic preview.'},403);
 if(route==='/profile')return json(response,{profile:businessProfile});
 if(route==='/overview'){if(revokeAfterOverview)revoked=true;return json(response,{business:{id:tenant,name:businessName,timeZone:zone},date:day,attention:[{id:'tasks',kind:'task',title:'Review your next steps',detail:`${tasks.filter(t=>t.status==='open').length} tasks are ready for your attention.`,action:'tasks'},...(callbackOpen?[{id:'callback',kind:'callback',title:'A customer asked for a callback',detail:'Return contact is unverified. Review it before following up.',action:'callbacks'}]:[])],appointments:appointments.filter(a=>overlapsDay(a,day)),tasks:tasks.filter(t=>t.status==='open'),counts:{tasksOpen:tasks.filter(t=>t.status==='open').length},setup:{calendarConnected:!harnessEvidence},source});}
 if(route==='/tasks'&&request.method==='POST'){const customer=linkedCustomer(body.customerId);if(body.customerId&&!customer)return json(response,{message:'Choose a customer from this synthetic workspace.'},404);const task={id:randomUUID(),...body,status:'open',revision:1,customer};tasks.push(task);return json(response,{task},201);}
 if(route.startsWith('/tasks/')&&request.method==='POST'){const task=tasks.find(t=>t.id===route.split('/')[2]);if(!task||task.revision!==body.revision)return json(response,{message:'Task changed. Refresh the list.'},409);const customer=body.customerId===undefined?task.customer:linkedCustomer(body.customerId);if(body.customerId&&!customer)return json(response,{message:'Choose a customer from this synthetic workspace.'},404);Object.assign(task,body,{revision:task.revision+1,customer});return json(response,{task});}
 if(route==='/tasks'){const rows=tasks.filter(t=>url.searchParams.get('status')==='all'||t.status===(url.searchParams.get('status')??'open'));return json(response,{tasks:rows,counts:{open:tasks.filter(t=>t.status==='open').length,completed:tasks.filter(t=>t.status==='completed').length,total:tasks.length},hasMore:false,nextCursor:null});}
 if(route==='/customers/prepare'){if(!body.email&&!body.phone)return json(response,{message:'Provide at least one contact method.'},400);const proposal={id:randomUUID(),customerId:body.id??randomUUID(),profile:{name:body.name,email:body.email??null,phone:body.phone??null},expiresAt:new Date(Date.now()+120000).toISOString(),readback:`Save ${body.name}? Email: ${body.email??'not provided'}. Phone: ${body.phone??'not provided'}.`};proposals.set(proposal.id,proposal);return json(response,{proposal});}
 if(route==='/customers/confirm'){const proposal=proposals.get(body.id);if(!proposal)return json(response,{message:'Review expired.'},409);let customer=customers.find(c=>c.id===proposal.customerId);if(customer)Object.assign(customer,proposal.profile,{revision:customer.revision+1});else{customer={id:proposal.customerId,...proposal.profile,revision:1};customers.push(customer);}return json(response,{result:{id:customer.id,saved:true}});}
 if(route==='/customers'){const q=(url.searchParams.get('q')??'').toLowerCase();const rows=customers.filter(c=>[c.name,c.email,c.phone].join(' ').toLowerCase().includes(q));return json(response,{customers:rows,total:rows.length,hasMore:false,nextCursor:null});}
 if(route.startsWith('/customers/'))return json(response,{customer:customers.find(c=>c.id===route.split('/')[2])});
 if(route==='/agenda'){const hasRange=url.searchParams.has('start')||url.searchParams.has('end'),start=Date.parse(url.searchParams.get('start')),end=Date.parse(url.searchParams.get('end'));if(hasRange&&(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>93*86400000||url.searchParams.has('date')))return json(response,{message:'Choose a range of up to 93 days.'},400);const date=url.searchParams.get('date')??day;const rows=appointments.filter(a=>(!url.searchParams.has('customerId')||a.customer?.id===url.searchParams.get('customerId'))&&(hasRange?Date.parse(a.input.start)<end&&Date.parse(a.input.end)>start:overlapsDay(a,date))).sort((a,b)=>Date.parse(a.input.start)-Date.parse(b.input.start)||a.id.localeCompare(b.id));return json(response,{appointments:rows,total:rows.length,timeZone:zone,source,hasMore:false,nextCursor:null});}
 if(route==='/callbacks')return json(response,{callbacks:callbackOpen?[callback]:[],total:callbackOpen?1:0,hasMore:false,nextCursor:null});
 if(route.startsWith('/callbacks/')&&request.method==='POST'){callbackOpen=false;return json(response,{callback:{status:'handled'}});}
 if(route==='/scheduling-policy')return json(response,{policy:harnessEvidence?null:policy,revision:harnessEvidence?0:1});
 if(route==='/harness'&&request.method==='GET')return json(response,harnessState());
 if(['/harness/goals','/harness/skills'].includes(route)&&request.method==='POST'){
  const rows=route.endsWith('/goals')?harnessGoals:harnessSkills,id=body.id??randomUUID(),existing=rows.find(item=>item.id===id),createKey=route+':'+id;
  if(existing){if(body.revision===0&&harnessCreates.get(createKey)===JSON.stringify({...body,id}))return json(response,harnessState());if(body.revision!==existing.revision)return json(response,{message:'This saved item changed. Reload and review it again.'},409);Object.assign(existing,body,{id,revision:existing.revision+1});}
  else{if(body.revision!==0)return json(response,{message:'Start a new item at revision zero.'},409);const created={...body,id,revision:1,archived:body.archived??false};if(route.endsWith('/goals')){created.metric??=null;created.deadline??=null;}rows.push(created);harnessCreates.set(createKey,JSON.stringify({...body,id}));}return json(response,harnessState());
 }
 if(route==='/harness/identity'&&request.method==='POST'){if(body.revision!==harnessIdentity.revision)return json(response,{message:'Identity changed. Reload and review it again.'},409);harnessIdentity={...harnessIdentity,...body,displayName:harnessIdentity.displayName,revision:harnessIdentity.revision+1};return json(response,harnessState());}
 if(route==='/harness/config'&&request.method==='POST'){if(body.revision!==harnessConfig.revision)return json(response,{message:'Agent settings changed. Reload and review again.'},409);harnessConfig={...harnessConfig,...body,revision:harnessConfig.revision+1,nextRunAt:body.enabled?nextCheckRun(body.schedule,Date.now()).at:null};return json(response,harnessState());}
 if(route==='/harness/run'&&request.method==='POST'){if(harnessEvidence)return json(response,{message:'This preview replays one recorded Workers AI report. It cannot generate another review.'},503);if(!body.requestId)return json(response,{message:'A request ID is required.'},400);if(harnessRuns.has(body.requestId))return json(response,{...harnessRuns.get(body.requestId),replay:true});const run={id:randomUUID(),status:'ready',trigger:'manual',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),errorCode:null,replyAttemptCounted:true};harnessReport=buildHarnessReport(run.id);harnessHistory.unshift(run);harnessConfig={...harnessConfig,lastRunAt:run.createdAt,lastStatus:'ready'};const result={run,report:harnessReport};harnessRuns.set(body.requestId,result);return json(response,{...result,replay:false});}
 if(route==='/harness/tasks/prepare'&&request.method==='POST'){const report=harnessReport?.id===body.runId?harnessReport:[...harnessRuns.values()].find(result=>result.run.id===body.runId)?.report,draft=report?.taskDrafts.find(item=>item.id===body.draftId);if(!draft)return json(response,{message:'This suggested task is not in the synthetic report.'},404);const input={runId:body.runId,draftId:body.draftId,title:body.title,priority:body.priority,dueAt:body.dueAt??null,customerId:body.customerId??null};const proposal={id:randomUUID(),expiresAt:new Date(Date.now()+120000).toISOString(),readback:`Save internal task “${input.title}”? Priority: ${input.priority}. Due: ${input.dueAt??'not set'}. No message or calendar invitation is sent.`,input};harnessTaskProposals.set(proposal.id,{proposal,draft});return json(response,{proposal});}
 if(route==='/harness/tasks/confirm'&&request.method==='POST'){const id=body.proposal?.id;if(harnessTaskReceipts.has(id))return json(response,{task:harnessTaskReceipts.get(id),replay:true});const saved=harnessTaskProposals.get(id);if(!saved||Date.parse(saved.proposal.expiresAt)<=Date.now())return json(response,{message:'Review expired. Prepare the suggested task again.'},409);if(saved.draft.acceptedTaskId){const task=tasks.find(task=>task.id===saved.draft.acceptedTaskId);harnessTaskReceipts.set(id,task);return json(response,{task,replay:true});}const input=saved.proposal.input,customer=linkedCustomer(input.customerId);if(input.customerId&&!customer)return json(response,{message:'Choose a saved synthetic customer.'},404);const task={id:randomUUID(),title:input.title,priority:input.priority,dueAt:input.dueAt,customerId:input.customerId,customer,status:'open',revision:1};tasks.push(task);saved.draft.acceptedTaskId=task.id;harnessTaskReceipts.set(id,task);return json(response,{task,replay:false});}
 if(route==='/routines'&&request.method==='POST'){if(body.revision!==routineConfig.revision)return json(response,{message:'Your playbook settings changed. Refresh and review again.'},409);routineConfig={...routineConfig,...body,revision:routineConfig.revision+1,nextRunAt:body.enabled?nextCheckRun(body.schedule,Date.now()).at:null};return json(response,{config:routineConfig});}
 if(route==='/routines')return json(response,{catalog:BUSINESS_ROUTINE_CATALOG,config:routineConfig,latestBrief:routineBrief,history:[],scope:routineScope});
 if(route==='/routines/run'&&request.method==='POST'){
  if(!routineConfig.revision)return json(response,{message:'Save your playbook first.'},409);if(routineRuns.has(body.requestId))return json(response,{brief:routineRuns.get(body.requestId),replay:true});
  const now=Date.now(),openTasks=tasks.filter(task=>task.status==='open'),overdue=openTasks.filter(task=>task.dueAt&&Date.parse(task.dueAt)<now).length,pending=callbackOpen?1:0,bookings=appointments.filter(appointment=>appointment.status==='confirmed'&&Date.parse(appointment.input.start)>=now&&Date.parse(appointment.input.start)<now+7*86400000).length,withContact=customers.filter(customer=>customer.email?.trim()||customer.phone?.trim()).length;
  routineBrief={id:randomUUID(),generatedAt:new Date(now).toISOString(),templateIds:routineConfig.templateIds,summary:`Synthetic snapshot: ${overdue} overdue tasks, ${pending} callback requests awaiting review, and ${bookings} confirmed Mayor bookings in the next seven days.`,metrics:[{key:'open_tasks',label:'Open tasks',value:openTasks.length},{key:'overdue_tasks',label:'Overdue tasks',value:overdue},{key:'pending_callbacks',label:'Pending callbacks',value:pending},{key:'bookings_next_7_days',label:'Confirmed Mayor bookings · next 7 days',value:bookings},{key:'saved_customers',label:'Saved customer records',value:customers.length},{key:'customers_with_contact',label:'Records with a contact field',value:withContact},{key:'revenue',label:'Revenue · not recorded',value:null}],priorities:openTasks.slice(0,1).map(task=>({id:task.id,title:task.title,detail:'An open task from your synthetic workspace. Check the appointment details before preparing notes.',source:{kind:'task',id:task.id},assistantPrompt:'Help me prepare appointment notes using my confirmed business details. Do not invent customer needs.'})),suggestions:routineConfig.templateIds.map(id=>{const template=BUSINESS_ROUTINE_CATALOG.find(t=>t.id===id);return {title:template.title,detail:template.description,assistantPrompt:template.assistantPrompt};}),gaps:['Revenue, customer consent, purchase history and external review data are not measured in this preview.'],scope:routineScope};routineConfig={...routineConfig,lastRunAt:routineBrief.generatedAt,lastStatus:'ready'};routineRuns.set(body.requestId,routineBrief);return json(response,{brief:routineBrief,replay:false});
 }
 if(route==='/routines/brief/read'&&request.method==='POST')return json(response,{read:true});
 if(route==='/conversation'&&request.method==='POST'&&conversationDelay){
  await new Promise(resolve=>setTimeout(resolve,conversationDelay));
  const reply='Synthetic preview reply. Your message was received; no business record was changed.';
  conversationFixture.push({role:'user',content:String(body.text??'')},{role:'assistant',content:reply});
  return json(response,{reply,events:[]});
 }
 if(route==='/conversation')return json(response,{messages:conversationFixture});
 if(route==='/notifications/refresh')return json(response,{notifications:[],hasMore:false});
 if(route==='/billing'){const period=freePeriod();return json(response,{plans:PLANS,creditPacks:CREDIT_PACKS.map(pack=>({...pack,available:role==='owner'})),credits:{...period,periodStart:new Date(period.periodStart*1000).toISOString(),expiresAt:new Date(period.periodEnd*1000).toISOString(),replyAttempts:0,voiceMinutes:0,purchases:[],checkout:{pending:false}},plan:{id:'free',name:'Free',status:'active',cancelAtPeriodEnd:false},usage:{replies:{used:12,limit:100,remaining:88},voiceMinutes:{used:2,limit:10,remaining:8},resetAt:new Date(period.periodEnd*1000).toISOString()},permissions:{canManage:['owner','billing'].includes(role)},readiness:{checkout:false,creditPacks:role==='owner',portal:false,mode:'test',message:'Synthetic UI preview. Payments are tested separately against Stripe sandbox.'},checkout:{pending:false}});}
 if(route==='/billing/credit-checkout')return json(response,{message:'Synthetic UI preview cannot create payments. Actual pack checkouts are tested in the isolated Stripe Sandbox.'},503);
 if(url.pathname==='/api/voice/session')return json(response,{message:'Synthetic UI preview uses typed interface checks; real voice is tested separately.'},503);
 if(url.pathname.startsWith('/api/'))return json(response,{message:'This optional service is not connected in the synthetic preview.'},503);
 const path=resolve('public','.'+(url.pathname==='/'?'/index.html':url.pathname));if(!path.startsWith(resolve('public')+'/')&&!path.startsWith(resolve('public')+'\\'))return json(response,{},404);
 let bytes=await readFile(path);if(extname(path)==='.html'){
  let html=bytes.toString().replace('<div class="app">',`<div style="position:fixed;right:5px;bottom:3px;z-index:40;font:9px sans-serif;color:#678;background:#fff">${harnessEvidence?'RECORDED WORKERS AI · SYNTHETIC INPUTS':'SYNTHETIC UI PREVIEW'}</div><div class="app">`);
  // Explicit test-only geometry shim. It exercises the real adapter and CSS;
  // it does not emulate a physical device or its keyboard behavior.
  if(keyboardViewportPreview)html=html.replace('</head>',`<script>
   (()=>{const query=new URLSearchParams(location.search),viewport=new EventTarget();
    Object.defineProperties(viewport,{height:{get:()=>Number(query.get('synthetic-height'))||innerHeight},offsetTop:{get:()=>Number(query.get('synthetic-top'))||0},scale:{get:()=>Number(query.get('synthetic-scale'))||1}});
    Object.defineProperty(window,'visualViewport',{value:viewport,configurable:true});
   })();
  </script></head>`);
  // Explicit CSS state fixture only: no voice client, microphone or provider.
  if(voiceLayoutPreview)html=html.replace('</body>',`<button id="preview-voice-layout" type="button" style="position:fixed;right:5px;top:5px;z-index:1000;font:9px sans-serif;padding:3px;max-width:100px">Toggle synthetic voice layout</button><script>
   document.getElementById('preview-voice-layout').onclick=()=>{const active=document.body.dataset.voiceActive!=='true';document.body.dataset.voiceActive=String(active);document.body.classList.toggle('listening',active);document.getElementById('status').textContent=active?'Synthetic voice layout · no microphone':'Synthetic voice layout ended';};
  </script></body>`);
  bytes=Buffer.from(html);
 }
 const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.webmanifest':'application/manifest+json'};response.writeHead(200,{'content-type':types[extname(path)]??'application/octet-stream','cache-control':'no-store'});response.end(bytes);
 }catch(error){json(response,{message:'Preview route unavailable.'},404);}});
server.listen(port,'127.0.0.1',()=>process.stdout.write(`Synthetic Mayor UI preview (${role} role${signedOut?', signed out':''}${longName?', 160-character business name':''}${emptyAgent?', empty business agent':''}${harnessEvidence?', recorded Workers AI on synthetic Cedar Bike inputs':''}${revokeAfterOverview?', revocation after first overview':''}) http://127.0.0.1:${port}\n`));
