import {env as testEnv} from 'cloudflare:workers';
import {beforeEach,expect,it} from 'vitest';
import type {Env,Actor} from '../../src/env';
import {handleBillingPublic,handleBillingRequest} from '../../src/billing';
import {auditOffer,createAuditCheckout,auditReceipt,auditReport,auditIntakeSchema,AUDIT_DOMAIN} from '../../src/billing/audit';
import {processBillingEvent} from '../../src/billing/events';
import {StripeClient,type StripeObject,type StripeEvent} from '../../src/billing/stripe';
import {runBusinessAudits} from '../../src/business-audit';
import {auditFixtureEvidence,auditFixtureDraft,auditFixtureReview,auditCompletion} from '../fixtures/business-audit';
import type {BusinessAuditReport,AuditReview} from '../../src/business-audit-schema';
let env:Env,provider:AuditStripe;
const intake={contactName:'Alex Example',email:'owner@example.test',businessName:'Example local shop',website:'https://example.com',goals:'Reduce missed customer inquiries and improve scheduling.',notes:'A synthetic test business.',links:['https://example.com/services'],acceptedTerms:true as const};
const price={id:'price_MayorAudit',livemode:false,active:true,type:'one_time',recurring:null,currency:'usd',unit_amount:33000,billing_scheme:'per_unit',tax_behavior:'exclusive'};
class AuditStripe extends StripeClient{
 objects=new Map<string,StripeObject>([['/v1/prices/price_MayorAudit',structuredClone(price)]]);calls:Array<{path:string;method:string;body?:Record<string,unknown>;key?:string}>=[];
 constructor(){super('sk_test_fixture');}
 async request(path:string,method:'GET'|'POST'|'DELETE'='GET',body?:Record<string,unknown>,key?:string){this.calls.push({path,method,body,key});if(method==='POST'&&path==='/v1/checkout/sessions'){const id=`cs_test_${crypto.randomUUID().replaceAll('-','')}`,session={id,livemode:false,mode:body?.mode,metadata:body?.metadata,client_reference_id:body?.client_reference_id,status:'open',payment_status:'unpaid',expires_at:Math.floor(Date.now()/1000)+86400,url:`https://checkout.stripe.com/c/pay/${id}`};this.objects.set(`/v1/checkout/sessions/${id}`,session);return session;}const object=this.objects.get(path.split('?')[0]);if(!object)throw new Error('missing fixture');return structuredClone(object);}
}
beforeEach(async()=>{env={...testEnv as unknown as Env,MAYOR_STRIPE_MODE:'test',MAYOR_STRIPE_SECRET_KEY:'sk_test_fixture',MAYOR_STRIPE_WEBHOOK_SECRET:'whsec_fixture',MAYOR_STRIPE_AUDIT_PRICE_ID:'price_MayorAudit',MAYOR_AUDIT_STATUS_SECRET:'test-only-audit-receipt-secret-00000000'};provider=new AuditStripe();await env.AGENT_DB.prepare("DELETE FROM mayor_rate_limits WHERE subject LIKE 'mayor:audit:%'").run();});
function event(type:string,object:StripeObject):StripeEvent{return {id:`evt_${crypto.randomUUID().replaceAll('-','')}`,type,created:Math.floor(Date.now()/1000),livemode:false,data:{object}};}
async function paidFixture(){const result=await createAuditCheckout(env,intake,crypto.randomUUID(),provider),order=await env.AGENT_DB.prepare('SELECT * FROM mayor_audit_orders WHERE id=?').bind(result.orderId).first<any>(),session=provider.objects.get(`/v1/checkout/sessions/${order.stripe_session_id}`)!,intent={id:`pi_${crypto.randomUUID().replaceAll('-','')}`,livemode:false,status:'succeeded',currency:'usd',amount_received:33000,customer:'cus_AuditFixture',metadata:{mayor_billing_domain:AUDIT_DOMAIN,mayor_audit_order_id:order.id}};Object.assign(session,{status:'complete',payment_status:'paid',currency:'usd',amount_subtotal:33000,amount_total:33000,customer:intent.customer,line_items:{has_more:false,data:[{quantity:1,price:structuredClone(price)}]},payment_intent:intent});const charge={id:'ch_'+crypto.randomUUID().replaceAll('-',''),livemode:false,customer:intent.customer,payment_intent:intent.id,paid:true,captured:true,amount:33000,currency:'usd',refunded:false,amount_refunded:0,disputed:false};Object.assign(intent,{latest_charge:charge.id});provider.objects.set('/v1/charges/'+charge.id,charge);provider.objects.set('/v1/payment_intents/'+intent.id,intent);return {result,order,session,intent,charge};}
function completedFixture(orderId:string){
 const evidence=auditFixtureEvidence(),createdAt='2026-10-03T15:00:00.000Z';
 const report:BusinessAuditReport={...auditFixtureDraft(),schemaVersion:1,orderId,businessName:intake.businessName,website:intake.website,generatedAt:createdAt,analysisModel:'saved-analysis-model',reviewModel:'saved-review-model',scope:{method:'Public static source analysis with independent automatic review.',limitations:evidence.limitations,pagesChecked:evidence.sources.length},sources:evidence.sources};
 const review:AuditReview={...auditFixtureReview(),model:'saved-review-model',reviewedAt:createdAt};
 return {report,review,createdAt};
}
async function storeCompleted(orderId:string,fixture:ReturnType<typeof completedFixture>){await env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET fulfillment_status='report_ready',report_json=?,review_json=?,report_created_at=? WHERE id=?").bind(JSON.stringify(fixture.report),JSON.stringify(fixture.review),fixture.createdAt,orderId).run();}
it('offers an independent $330 one-time audit without requiring a Pro subscription or price',()=>{expect(auditOffer(env)).toMatchObject({available:true,mode:'test',offer:{priceCents:33000,currency:'USD',payment:'one_time'}});expect(auditOffer({...env,MAYOR_STRIPE_MODE:'live',MAYOR_STRIPE_SECRET_KEY:'sk_live_fixture'})).toMatchObject({available:false});expect(auditOffer({...env,MAYOR_STRIPE_AUDIT_PRICE_ID:undefined}).available).toBe(false);});
it('requires explicit accepted intake and allowlisted-origin JSON submission',async()=>{
 const request=(body:unknown,origin='https://mehyar.us')=>new Request(`${env.APP_ORIGIN}/api/business-audit/checkout`,{method:'POST',headers:{origin,'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)});expect((await handleBillingPublic(request({...intake,acceptedTerms:false}),env,provider))?.status).toBe(400);expect((await handleBillingPublic(request(intake,'https://foreign.example'),env,provider))?.status).toBe(403);expect(provider.calls).toHaveLength(0);const result=await handleBillingPublic(request(intake),env,provider);expect(result?.status).toBe(200);expect(result?.headers.get('access-control-allow-origin')).toBe('https://mehyar.us');expect(()=>auditIntakeSchema.parse({...intake,website:'https://user:password@example.test'})).toThrow();
});
it('accepts a bounded full brief including Unicode and supplied links within the published field limits',async()=>{
 const full={...intake,goals:'م'.repeat(4000),notes:'م'.repeat(4000),links:Array.from({length:10},(_,index)=>`https://example.com/${index}/`+'a'.repeat(1900))},request=new Request(`${env.APP_ORIGIN}/api/business-audit/checkout`,{method:'POST',headers:{origin:'https://mehyar.us','content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(full)});expect((await handleBillingPublic(request,env,provider))?.status).toBe(200);
});
it('creates only a server-priced one-time checkout with no intake in redirects and stable replay tokens',async()=>{
 const key=crypto.randomUUID(),first=await createAuditCheckout(env,intake,key,provider),second=await createAuditCheckout(env,intake,key,provider);expect(second).toMatchObject({...first,replay:true});const call=provider.calls.find(call=>call.path==='/v1/checkout/sessions'&&call.method==='POST')!;expect(call.body?.line_items).toEqual([{price:'price_MayorAudit',quantity:1}]);expect(call.body?.mode).toBe('payment');expect(String(call.body?.success_url)).not.toContain(intake.email);expect(String(call.body?.success_url)).not.toContain(intake.businessName);expect(first.statusToken).toMatch(/^[a-f0-9]{64}$/);const stored=await env.AGENT_DB.prepare('SELECT status_token_hash,intake_json FROM mayor_audit_orders WHERE id=?').bind(first.orderId).first<any>();expect(stored.status_token_hash).not.toBe(first.statusToken);expect(JSON.parse(stored.intake_json).email).toBe(intake.email);await expect(createAuditCheckout(env,{...intake,goals:'Changed goal details for another request'},key,provider)).rejects.toMatchObject({code:'audit_request_conflict'});
});
it('keeps original receipts readable after secret rotation and rejects returning an unusable replay token',async()=>{
 const key=crypto.randomUUID(),result=await createAuditCheckout(env,intake,key,provider),rotated={...env,MAYOR_AUDIT_STATUS_SECRET:'rotated-test-audit-receipt-secret-00000000'};expect((await auditReceipt(rotated,result.statusToken)).orderId).toBe(result.orderId);await expect(createAuditCheckout(rotated,intake,key,provider)).rejects.toMatchObject({code:'audit_receipt_needs_review'});expect(provider.calls.filter(call=>call.path==='/v1/checkout/sessions')).toHaveLength(1);
});
it('exposes receipt state without private intake, Stripe identifiers or a success-URL payment assumption',async()=>{
 const result=await createAuditCheckout(env,intake,crypto.randomUUID(),provider),receipt=await auditReceipt(env,result.statusToken);expect(receipt).toMatchObject({paymentStatus:'pending',fulfillmentStatus:'awaiting_payment',reportAvailable:false,mode:'test'});const text=JSON.stringify(receipt);for(const value of [intake.email,intake.contactName,intake.website,'stripe_session_id','intake_json'])expect(text).not.toContain(value);await expect(auditReceipt(env,'a'.repeat(64))).rejects.toMatchObject({code:'audit_receipt_unavailable'});const response=await handleBillingPublic(new Request(`${env.APP_ORIGIN}/api/business-audit/status?payment=success&receipt=${result.statusToken}`),env,provider);expect(response?.status).toBe(404);await expect(auditReceipt({...env,MAYOR_STRIPE_MODE:'live'},result.statusToken)).rejects.toMatchObject({code:'audit_receipt_unavailable'});
});
it('queues an audit only after canonical checkout and settled payment verification; repeats do not duplicate it',async()=>{
 const data=await paidFixture(),paid=event('checkout.session.completed',data.session);await processBillingEvent(env,paid,provider);expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'paid',fulfillmentStatus:'queued',reportAvailable:false});expect(await processBillingEvent(env,paid,provider)).toMatchObject({outcome:'duplicate'});await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const rows=await env.AGENT_DB.prepare('SELECT id FROM mayor_audit_orders WHERE id=?').bind(data.result.orderId).all();expect(rows.results).toHaveLength(1);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it('keeps declined or authentication-required payments pending without queuing a report',async()=>{
 const data=await paidFixture();data.session.payment_status='unpaid';data.session.status='open';data.intent.status='requires_action';await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'pending',fulfillmentStatus:'awaiting_payment'});data.session.status='complete';data.session.payment_status='paid';await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'audit_payment_unverified'});expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);
});
it('rejects price, order ownership, mode and amount mismatches without marking an audit paid',async()=>{
 const data=await paidFixture();data.session.amount_subtotal=1;await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'audit_payment_contract_mismatch'});data.session.amount_subtotal=33000;data.intent.metadata.mayor_audit_order_id=crypto.randomUUID();await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'audit_payment_unverified'});data.intent.metadata.mayor_audit_order_id=data.order.id;data.session.line_items.data[0].price.livemode=true;await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'stripe_mode_mismatch'});expect((await auditReceipt(env,data.result.statusToken)).paymentStatus).toBe('pending');
});
it('exposes only the exact complete final report with a fully approved independent review',async()=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const fixture=completedFixture(data.order.id);await storeCompleted(data.order.id,fixture);expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(true);expect(await auditReport(env,data.result.statusToken)).toEqual({orderId:data.order.id,...fixture});
 const response=await handleBillingPublic(new Request(`${env.APP_ORIGIN}/api/business-audit/report`,{headers:{authorization:`Bearer ${data.result.statusToken}`}}),env,provider);expect(response?.status).toBe(200);expect(response?.headers.get('cache-control')).toBe('no-store');expect(await response?.json()).toEqual({orderId:data.order.id,...fixture});
});
it.each([
 ['wrong order', (report:any)=>{report.orderId=crypto.randomUUID();}],
 ['wrong schema version', (report:any)=>{report.schemaVersion=2;}],
 ['missing draft field', (report:any)=>{delete report.business;}],
 ['internal draft instead of report', (report:any)=>{delete report.schemaVersion;delete report.sources;}],
 ['incomplete finding', (report:any)=>{delete report.findings[0].measurement.howToCollect;}],
 ['unknown citation source', (report:any)=>{report.findings[0].citations[0].sourceId='S8';}],
 ['duplicate finding IDs', (report:any)=>{report.findings[1].id=report.findings[0].id;}],
 ['missing category coverage', (report:any)=>{report.findings[1].category=report.findings[0].category;}],
 ['duplicate source IDs', (report:any)=>{report.sources.push(structuredClone(report.sources[0]));report.scope.pagesChecked=2;}],
 ['mismatched source count', (report:any)=>{report.scope.pagesChecked=2;}],
 ['duplicate roadmap windows', (report:any)=>{report.roadmap[1].window=report.roadmap[0].window;}],
 ['unaccounted mapped reference', (report:any)=>{report.roadmap[0].findingIds.push('F02');}],
 ['mixed historical and mapped actions', (report:any)=>{report.roadmap[0].deliverables[0]='One verified customer request walkthrough.';}],
 ['only approved true', (_report:any,review:any)=>{for(const key of Object.keys(review))delete review[key];review.approved=true;}],
 ['missing review flags', (_report:any,review:any)=>{delete review.verification;}],
 ['missing individual review flag', (_report:any,review:any)=>{delete review.verification.actionability;}],
 ['false citation flag', (_report:any,review:any)=>{review.verification.citationGrounding=false;}],
 ['false scope flag', (_report:any,review:any)=>{review.verification.scopeHonesty=false;}],
 ['false actionability flag', (_report:any,review:any)=>{review.verification.actionability=false;}],
 ['false metrics flag', (_report:any,review:any)=>{review.verification.noFabricatedMetrics=false;}],
 ['unapproved review', (_report:any,review:any)=>{review.approved=false;}],
 ['review model does not match report receipt', (_report:any,review:any)=>{review.model='another-saved-review-model';}],
 ['review issue references an absent finding', (_report:any,review:any)=>{review.issues=[{findingId:'F12',severity:'minor',message:'This review note names a finding that is not present in the saved report.',suggestedFix:'Match the review note to an existing report finding before delivery.'}];}],
 ['major review issue', (_report:any,review:any)=>{review.issues=[{findingId:'F01',severity:'major',message:'The report is not supported by the captured source evidence.',suggestedFix:'Correct the unsupported finding before delivering this report.'}];}],
 ['critical review issue', (_report:any,review:any)=>{review.issues=[{findingId:null,severity:'critical',message:'The saved report is unsafe to deliver in its current form.',suggestedFix:'Resolve the critical issue before making this report available.'}];}],
] as Array<[string,(report:any,review:any)=>void]>)('withholds %s at both receipt and direct report boundaries',async(_label,change)=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const fixture=completedFixture(data.order.id);change(fixture.report,fixture.review);await storeCompleted(data.order.id,fixture);expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({status:409,code:'audit_report_not_ready'});
});
it.each(['report_json','review_json'] as const)('withholds malformed saved %s without leaking a parsing error',async column=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await storeCompleted(data.order.id,completedFixture(data.order.id));await env.AGENT_DB.prepare(`UPDATE mayor_audit_orders SET ${column}='{' WHERE id=?`).bind(data.order.id).run();expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it.each([
 ['pending','report_ready'],['refunded','report_ready'],['paid','queued'],['paid','needs_review'],
] as const)('withholds complete final artifacts while payment=%s and fulfillment=%s',async(payment,fulfillment)=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await storeCompleted(data.order.id,completedFixture(data.order.id));await env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET payment_status=?,fulfillment_status=? WHERE id=?').bind(payment,fulfillment,data.order.id).run();expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it.each([null,'not-a-timestamp'])('withholds a complete report without a valid saved creation timestamp (%s)',async createdAt=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await storeCompleted(data.order.id,completedFixture(data.order.id));await env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET report_created_at=? WHERE id=?').bind(createdAt,data.order.id).run();expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it('keeps a complete historical legacy report unchanged without re-running new narrative heuristics',async()=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const fixture=completedFixture(data.order.id);fixture.report.roadmap.forEach(phase=>{phase.deliverables=phase.deliverables.map(value=>value.replace(/^\[[^\]]+\] /,''));});fixture.report.findings[0].observation='The legacy report asserted that no CRM is installed; the read boundary does not re-analyze already delivered prose.';fixture.report.summary.headline='  Original saved report headline retained exactly  ';await storeCompleted(data.order.id,fixture);expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(true);expect(await auditReport(env,data.result.statusToken)).toEqual({orderId:data.order.id,...fixture});
});
it.each(['review','revise'] as const)('never returns private drafts, evidence or intake during %s even when a review is approved',async stage=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const fixture=completedFixture(data.order.id);await storeCompleted(data.order.id,fixture);await env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET fulfillment_status='in_review',analysis_stage=?,draft_json=?,evidence_json=? WHERE id=?").bind(stage,JSON.stringify({privateDraft:'PRIVATE-DRAFT-MARKER'}),JSON.stringify({privateEvidence:'PRIVATE-EVIDENCE-MARKER'}),data.order.id).run();const receipt=await auditReceipt(env,data.result.statusToken);expect(receipt.reportAvailable).toBe(false);expect(Object.keys(receipt).sort()).toEqual(['orderId','mode','paymentStatus','fulfillmentStatus','priceCents','currency','paidAt','reportAvailable'].sort());for(const value of ['PRIVATE-DRAFT-MARKER','PRIVATE-EVIDENCE-MARKER',intake.email,intake.contactName,intake.goals])expect(JSON.stringify(receipt)).not.toContain(value);const response=await handleBillingPublic(new Request(`${env.APP_ORIGIN}/api/business-audit/report`,{headers:{authorization:`Bearer ${data.result.statusToken}`}}),env,provider);expect(response?.status).toBe(409);for(const value of ['PRIVATE-DRAFT-MARKER','PRIVATE-EVIDENCE-MARKER',intake.email,intake.contactName,intake.goals])expect(await response?.clone().text()).not.toContain(value);
});
it('halts automatic delivery for a canonically owned dispute even without public intake metadata',async()=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const charge={id:'ch_AuditDispute',livemode:false,customer:data.session.customer,payment_intent:data.intent.id};provider.objects.set(`/v1/charges/${charge.id}`,charge);const disputed=event('charge.dispute.created',{id:'dp_AuditDispute',charge:charge.id});await processBillingEvent(env,disputed,provider);expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'paid',fulfillmentStatus:'needs_review',reportAvailable:false});await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect((await auditReceipt(env,data.result.statusToken)).fulfillmentStatus).toBe('needs_review');
});
it('keeps a genuine dispute hold during an in-flight independent review and blocks public report access',async()=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const evidence=auditFixtureEvidence(),draft=auditFixtureDraft();await env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET analysis_stage='review',evidence_json=?,draft_json=? WHERE id=?").bind(JSON.stringify(evidence),JSON.stringify(draft),data.order.id).run();
 const result=await runBusinessAudits({...env,AI:{} as Ai},{allowTest:true,orderId:data.order.id,dependencies:{infer:async(_model,input)=>{const disputed=event('charge.dispute.created',{id:'dp_DuringReview',charge:data.charge.id});await processBillingEvent(env,disputed,provider);return {results:[{index:0,external_reference:(input.requests as any[])[0].external_reference,success:true,result:auditCompletion(auditFixtureReview())}]};}}});
 expect(result.ready).toBe(0);expect(result.lostLease).toBe(1);const held=await env.AGENT_DB.prepare('SELECT analysis_token,analysis_lease_expires_at,report_json,fulfillment_status FROM mayor_audit_orders WHERE id=?').bind(data.order.id).first<any>();expect(held).toEqual({analysis_token:null,analysis_lease_expires_at:null,report_json:null,fulfillment_status:'needs_review'});expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'paid',fulfillmentStatus:'needs_review',reportAvailable:false});await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it('honors a genuine full refund before the first paid mapping and does not queue on paid replay',async()=>{
 const data=await paidFixture();data.charge.refunded=true;data.charge.amount_refunded=33000;const refund=event('charge.refunded',data.charge);await processBillingEvent(env,refund,provider);expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'refunded',fulfillmentStatus:'needs_review',reportAvailable:false});expect(await processBillingEvent(env,refund,provider)).toMatchObject({outcome:'duplicate'});await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect(await auditReceipt(env,data.result.statusToken)).toMatchObject({paymentStatus:'refunded',fulfillmentStatus:'needs_review',reportAvailable:false});await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});
});
it('detects an already refunded or disputed canonical charge before queuing the paid completion',async()=>{
 const refunded=await paidFixture();refunded.charge.amount_refunded=1;await processBillingEvent(env,event('checkout.session.completed',refunded.session),provider);expect(await auditReceipt(env,refunded.result.statusToken)).toMatchObject({paymentStatus:'refunded',fulfillmentStatus:'needs_review',reportAvailable:false});const disputed=await paidFixture();disputed.charge.disputed=true;await processBillingEvent(env,event('checkout.session.completed',disputed.session),provider);expect(await auditReceipt(env,disputed.result.statusToken)).toMatchObject({paymentStatus:'paid',fulfillmentStatus:'needs_review',reportAvailable:false});
});
it('requires the audit payment customer identity rather than accepting two absent customer references',async()=>{
 const data=await paidFixture();data.session.customer=null;data.intent.customer=null as unknown as string;await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'audit_payment_unverified'});expect((await auditReceipt(env,data.result.statusToken)).paymentStatus).toBe('pending');
});
it('never publishes a rejected independent review and prevents structurally private audit inputs',async()=>{
 const data=await paidFixture();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET fulfillment_status='report_ready',report_json='{}',review_json=?,report_created_at=? WHERE id=?").bind(JSON.stringify({approved:false}),new Date().toISOString(),data.order.id).run();expect((await auditReceipt(env,data.result.statusToken)).reportAvailable).toBe(false);await expect(auditReport(env,data.result.statusToken)).rejects.toMatchObject({code:'audit_report_not_ready'});for(const website of ['http://localhost','https://127.0.0.1','https://service.internal','https://service.onion','https://-invalid.example.com','https://invalid-.example.com','https://example.com:444','https://example.com/?token=private'])expect(()=>auditIntakeSchema.parse({...intake,website})).toThrow();expect(auditIntakeSchema.parse({...intake,website:'http://example.com'}).website).toBe('https://example.com/');
});
it('requires a specifically configured audit operator for private global fulfillment intake',async()=>{
 const actor:Actor={tenantId:crypto.randomUUID().replaceAll('-',''),userId:crypto.randomUUID()};await env.AGENT_DB.prepare('INSERT INTO agent_tenants(id,name,created_at) VALUES(?,?,?)').bind(actor.tenantId,'Operator fixture',new Date().toISOString()).run();await env.AGENT_DB.prepare("INSERT INTO agent_memberships(tenant_id,user_id,role) VALUES(?,?,'owner')").bind(actor.tenantId,actor.userId).run();const request=new Request(`${env.APP_ORIGIN}/api/businesses/${actor.tenantId}/billing/audit-orders`);await expect(handleBillingRequest(request,env,actor,provider)).rejects.toMatchObject({code:'audit_operator_required'});expect((await handleBillingRequest(request,{...env,MAYOR_AUDIT_OPERATOR_USER_IDS:actor.userId},actor,provider))?.status).toBe(200);
});
it('allows main-site CORS preflight and rejects arbitrary origin preflight',async()=>{
 const request=(origin:string)=>new Request(`${env.APP_ORIGIN}/api/business-audit/checkout`,{method:'OPTIONS',headers:{origin,'access-control-request-method':'POST'}});const allowed=await handleBillingPublic(request('https://www.mehyar.us'),env,provider);expect(allowed?.status).toBe(204);expect(allowed?.headers.get('access-control-allow-origin')).toBe('https://www.mehyar.us');expect((await handleBillingPublic(request('https://attacker.example'),env,provider))?.status).toBe(403);
});
