import {env as testEnv} from 'cloudflare:workers';
import {beforeEach,expect,it,vi} from 'vitest';
import type {Actor,Env} from '../../src/env';
import {handleBillingRequest} from '../../src/billing';
import {createCreditCheckout,creditStatus} from '../../src/billing/credits';
import {billingStatus,syncBilling,createCheckout} from '../../src/billing/service';
import {processBillingEvent} from '../../src/billing/events';
import {billingUsageContext,reserveMonthlyUsage,usageBalance} from '../../src/billing/state';
import {CREDIT_PACKS,CREDIT_PACK_VERSION,freePeriod,type CreditPackId} from '../../src/billing/plans';
import {metadata,StripeClient,type StripeEvent,type StripeObject} from '../../src/billing/stripe';
let env:Env,actor:Actor,provider:Provider;
class Provider extends StripeClient{
 objects=new Map<string,StripeObject>();posts:Array<{path:string;body:Record<string,any>;key:string}>=[];requests=new Map<string,StripeObject>();unknown=false;beforeCheckout?:()=>Promise<void>;afterCheckout?:()=>Promise<void>;
 constructor(){super('sk_test_fixture');for(const pack of CREDIT_PACKS)this.objects.set(`/v1/prices/price_${pack.id}`,{id:`price_${pack.id}`,active:true,livemode:false,currency:'usd',unit_amount:pack.priceCents,type:'one_time',recurring:null,billing_scheme:'per_unit',tax_behavior:'exclusive',metadata:{mayor_credit_pack:pack.id,mayor_credit_version:CREDIT_PACK_VERSION}});this.objects.set('/v1/prices/price_Pro',{id:'price_Pro',active:true,livemode:false,currency:'usd',unit_amount:1400,type:'recurring',recurring:{interval:'month',interval_count:1},billing_scheme:'per_unit',tax_behavior:'exclusive'});}
 async request(path:string,method:'GET'|'POST'|'DELETE'='GET',body?:Record<string,unknown>,key?:string){
  if(this.beforeCheckout&&path.startsWith('/v1/prices/')){const hook=this.beforeCheckout;this.beforeCheckout=undefined;await hook();}
  if(method==='POST'){
   this.posts.push({path,body:body??{},key:key!});if(this.requests.has(key!))return structuredClone(this.requests.get(key!)!);
   if(path==='/v1/customers'){const item={id:`cus_${crypto.randomUUID().replaceAll('-','')}`,livemode:false,metadata:body!.metadata};this.objects.set(`/v1/customers/${item.id}`,item);this.requests.set(key!,item);return structuredClone(item);}
   if(path==='/v1/checkout/sessions'){const id=`cs_test_${crypto.randomUUID().replaceAll('-','')}`,item={id,livemode:false,mode:body!.mode,status:'open',payment_status:'unpaid',customer:body!.customer,metadata:body!.metadata,client_reference_id:body!.client_reference_id,expires_at:body!.expires_at??Math.floor(Date.now()/1000)+86400,url:`https://checkout.stripe.com/c/pay/${id}`};this.objects.set(`/v1/checkout/sessions/${id}`,item);this.requests.set(key!,item);if(this.unknown){this.unknown=false;throw new Error('uncertain_network_response');}if(this.afterCheckout&&body!.mode==='payment'){const hook=this.afterCheckout;this.afterCheckout=undefined;await hook();}return structuredClone(item);}
  }
  const item=this.objects.get(path.split('?')[0]);if(!item)throw new Error(`Missing fixture ${path}`);return structuredClone(item);
 }
}
beforeEach(async()=>{env={...testEnv as unknown as Env,MAYOR_STRIPE_MODE:'test',MAYOR_STRIPE_SECRET_KEY:'sk_test_fixture',MAYOR_STRIPE_WEBHOOK_SECRET:'whsec_fixture',MAYOR_STRIPE_PRICE_ID:'price_Pro',MAYOR_STRIPE_CREDIT_PRICE_SMALL:'price_small',MAYOR_STRIPE_CREDIT_PRICE_MEDIUM:'price_medium',MAYOR_STRIPE_CREDIT_PRICE_LARGE:'price_large'};actor={tenantId:crypto.randomUUID().replaceAll('-',''),userId:crypto.randomUUID()};provider=new Provider();await env.AGENT_DB.prepare('INSERT INTO agent_tenants(id,name,created_at) VALUES(?,?,?)').bind(actor.tenantId,'Credit fixture',new Date().toISOString()).run();await env.AGENT_DB.prepare("INSERT INTO agent_memberships(tenant_id,user_id,role) VALUES(?,?,'owner')").bind(actor.tenantId,actor.userId).run();});
const event=(type:string,object:StripeObject):StripeEvent=>({id:`evt_${crypto.randomUUID().replaceAll('-','')}`,livemode:false,type,created:Math.floor(Date.now()/1000),data:{object}});
async function checkout(packId:CreditPackId='small',key=crypto.randomUUID()){const context=await billingUsageContext(env,actor);await createCreditCheckout(env,actor,key,packId,context.periodKey,provider);const row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND request_id=?').bind(actor.tenantId,key).first<any>(),session=provider.objects.get(`/v1/checkout/sessions/${row.stripe_session_id}`)!;return {row,session,key};}
function pay(data:Awaited<ReturnType<typeof checkout>>){const pack=CREDIT_PACKS.find(pack=>pack.id===data.row.pack_id)!,intentId=`pi_${crypto.randomUUID().replaceAll('-','')}`,chargeId=`ch_${crypto.randomUUID().replaceAll('-','')}`;Object.assign(data.session,{status:'complete',payment_status:'paid',payment_intent:intentId,currency:'usd',amount_subtotal:pack.priceCents,amount_total:pack.priceCents,total_details:{amount_discount:0,amount_tax:0}});const intent={id:intentId,livemode:false,status:'succeeded',customer:data.session.customer,metadata:data.session.metadata,currency:'usd',amount:pack.priceCents,amount_received:pack.priceCents,latest_charge:chargeId},charge={id:chargeId,livemode:false,customer:data.session.customer,payment_intent:intentId,paid:true,captured:true,currency:'usd',amount:pack.priceCents,amount_refunded:0,refunded:false,disputed:false},lines={has_more:false,data:[{price:`price_${pack.id}`,quantity:1,currency:'usd',amount_subtotal:pack.priceCents,amount_total:pack.priceCents}]};provider.objects.set(`/v1/payment_intents/${intentId}`,intent);provider.objects.set(`/v1/charges/${chargeId}`,charge);provider.objects.set(`/v1/checkout/sessions/${data.session.id}/line_items`,lines);return {intent,charge,lines};}
async function seedUsage(count:number){const context=await billingUsageContext(env,actor);await env.AGENT_DB.prepare("INSERT INTO mayor_billing_usage_periods(tenant_id,period_key,kind,count) VALUES(?,?,'turn',?) ON CONFLICT(tenant_id,period_key,kind) DO UPDATE SET count=excluded.count").bind(actor.tenantId,context.periodKey,count).run();}
async function seedPro(){const result=await createCheckout(env,actor,crypto.randomUUID(),provider),row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_checkouts WHERE tenant_id=?').bind(actor.tenantId).first<any>(),session=provider.objects.get('/v1/checkout/sessions/'+row.stripe_session_id)!,start=Math.floor(Date.now()/1000)-60,end=start+30*86400,subId=`sub_${crypto.randomUUID().replaceAll('-','')}`,inId=`in_${crypto.randomUUID().replaceAll('-','')}`,pi=`pi_${crypto.randomUUID().replaceAll('-','')}`;Object.assign(session,{status:'complete',payment_status:'paid',subscription:subId});const invoice={id:inId,livemode:false,customer:session.customer,parent:{subscription_details:{subscription:subId}},status:'paid',currency:'usd',subtotal:1400,total:1400,amount_paid:1400,amount_remaining:0,billing_reason:'subscription_create',lines:{has_more:false,data:[{amount:1400,currency:'usd',quantity:1,pricing:{price_details:{price:'price_Pro'}},period:{start,end},proration:false}]},payments:{has_more:false,data:[{status:'paid',livemode:false,currency:'usd',invoice:inId,amount_paid:1400,payment:{type:'payment_intent',payment_intent:pi}}]}};provider.objects.set('/v1/subscriptions/'+subId,{id:subId,livemode:false,metadata:metadata(actor.tenantId,row.id),customer:session.customer,status:'active',cancel_at_period_end:false,latest_invoice:inId,items:{has_more:false,data:[{quantity:1,price:provider.objects.get('/v1/prices/price_Pro')}]}});provider.objects.set('/v1/invoices/'+inId,invoice);provider.objects.set('/v1/payment_intents/'+pi,{id:pi,livemode:false,status:'succeeded',currency:'usd',amount_received:1400,customer:session.customer});await processBillingEvent(env,event('invoice.paid',invoice),provider);return {result,start,end};}
it('publishes exact one-time pack catalog with no grant from a successful return URL',async()=>{const status=await billingStatus(env,actor);expect(status.creditPacks.map(pack=>[pack.priceCents,pack.replyAttempts,pack.voiceMinutes])).toEqual([[400,200,15],[800,500,45],[1200,800,90]]);expect(status.readiness.creditPacks).toBe(true);const response=await handleBillingRequest(new Request(`${env.APP_ORIGIN}/api/businesses/${actor.tenantId}/billing?billing=credits&paid=true`),env,actor,provider);expect((await response!.json() as any).usage.replies.limit).toBe(100);expect(provider.posts).toHaveLength(0);});
it('allows only current business owner/billing purchase and rejects origins, periods and client amounts',async()=>{const context=await billingUsageContext(env,actor),request=(body:any,origin=env.APP_ORIGIN)=>new Request(`${env.APP_ORIGIN}/api/businesses/${actor.tenantId}/billing/credit-checkout`,{method:'POST',headers:{origin,'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)});await env.AGENT_DB.prepare("UPDATE agent_memberships SET role='manager' WHERE tenant_id=?").bind(actor.tenantId).run();await expect(handleBillingRequest(request({packId:'small',periodKey:context.periodKey}),env,actor,provider)).rejects.toMatchObject({code:'permission_denied'});await env.AGENT_DB.prepare("UPDATE agent_memberships SET role='billing' WHERE tenant_id=?").bind(actor.tenantId).run();await expect(handleBillingRequest(request({packId:'small',periodKey:context.periodKey},'https://bad.example'),env,actor,provider)).rejects.toMatchObject({code:'invalid_origin'});await expect(handleBillingRequest(request({packId:'small',periodKey:context.periodKey,priceCents:1}),env,actor,provider)).rejects.toThrow();await expect(createCreditCheckout(env,actor,crypto.randomUUID(),'small','free:1900-01',provider)).rejects.toMatchObject({code:'credit_period_changed'});expect(provider.posts).toHaveLength(0);});
it('replays the original checkout and rejects changed quotes and concurrent duplicate purchases',async()=>{const data=await checkout(),again=await createCreditCheckout(env,actor,data.key,'small',data.row.period_key,provider);expect(again.replay).toBe(true);await expect(createCreditCheckout(env,actor,data.key,'large',data.row.period_key,provider)).rejects.toMatchObject({code:'credit_request_changed'});await expect(checkout('small')).rejects.toMatchObject({code:'credit_checkout_pending'});expect(provider.posts.filter(post=>post.path==='/v1/checkout/sessions')).toHaveLength(1);expect((await billingStatus(env,actor)).credits.checkout).toMatchObject({pending:true,requestId:data.key,packId:'small'});await env.AGENT_DB.prepare("UPDATE agent_memberships SET role='staff' WHERE tenant_id=?").bind(actor.tenantId).run();expect((await billingStatus(env,actor)).credits.checkout).toEqual({pending:true});});
it('recovers an unknown provider response with identical expiry and all original Stripe parameters',async()=>{const context=await billingUsageContext(env,actor),key=crypto.randomUUID();provider.unknown=true;await expect(createCreditCheckout(env,actor,key,'small',context.periodKey,provider)).rejects.toThrow('uncertain_network_response');const now=Date.now();const spy=vi.spyOn(Date,'now').mockReturnValue(now+7000);try{await createCreditCheckout(env,actor,key,'small',context.periodKey,provider);}finally{spy.mockRestore();}const posts=provider.posts.filter(post=>post.path==='/v1/checkout/sessions');expect(posts).toHaveLength(2);expect(posts[1]).toEqual(posts[0]);expect(provider.requests.size).toBe(2);});
it('stops an in-flight quote if billing authority is revoked before submission',async()=>{provider.beforeCheckout=async()=>{await env.AGENT_DB.prepare('DELETE FROM agent_memberships WHERE tenant_id=? AND user_id=?').bind(actor.tenantId,actor.userId).run();};await expect(checkout()).rejects.toMatchObject({code:'workspace_not_found'});expect(provider.posts.some(post=>post.path==='/v1/checkout/sessions')).toBe(false);});
it('returns no payable URL if authority is revoked while the provider checkout is pending',async()=>{provider.afterCheckout=async()=>{await env.AGENT_DB.prepare('DELETE FROM agent_memberships WHERE tenant_id=? AND user_id=?').bind(actor.tenantId,actor.userId).run();};await expect(checkout()).rejects.toMatchObject({code:'workspace_not_found'});const row=await env.AGENT_DB.prepare('SELECT checkout_url FROM mayor_billing_credit_checkouts WHERE tenant_id=?').bind(actor.tenantId).first<any>();expect(row.checkout_url).toBeNull();});
it('returns no stale payable URL if a Pro upgrade completes while the provider checkout is pending',async()=>{provider.afterCheckout=async()=>{await seedPro();};await expect(checkout()).rejects.toMatchObject({code:'credit_period_changed'});const row=await env.AGENT_DB.prepare('SELECT checkout_url,status FROM mayor_billing_credit_checkouts WHERE tenant_id=?').bind(actor.tenantId).first<any>();expect(row.checkout_url).toBeNull();expect(row.status).toBe('expired');});
it('admits only one actual provider checkout from simultaneous distinct purchase requests',async()=>{const period=(await billingUsageContext(env,actor)).periodKey,results=await Promise.allSettled([createCreditCheckout(env,actor,crypto.randomUUID(),'small',period,provider),createCreditCheckout(env,actor,crypto.randomUUID(),'medium',period,provider),createCreditCheckout(env,actor,crypto.randomUUID(),'large',period,provider)]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(provider.posts.filter(post=>post.path==='/v1/checkout/sessions')).toHaveLength(1);});
it('does not let a stale Free status read retire a newly created valid Pro quote',async()=>{let invoked=false;const wrapped={...env,AGENT_DB:{prepare(sql:string){const stmt=env.AGENT_DB.prepare(sql);if(!sql.startsWith('UPDATE mayor_billing_credit_checkouts AS'))return stmt;return {bind(...args:any[]){const bound=stmt.bind(...args);return {async run(){if(!invoked){invoked=true;await seedPro();await checkout('medium');}return bound.run();}};}};}} as unknown as D1Database};await billingStatus(wrapped,actor);const row=await env.AGENT_DB.prepare('SELECT status,period_key FROM mayor_billing_credit_checkouts WHERE tenant_id=?').bind(actor.tenantId).first<any>();expect(row.status).toBe('open');expect(row.period_key.startsWith('pro:')).toBe(true);});
it('does not return a stale resume URL when an upgrade commits during quote reconciliation',async()=>{const data=await checkout();let invoked=false;const wrapped={...env,AGENT_DB:{prepare(sql:string){const stmt=env.AGENT_DB.prepare(sql);if(!sql.startsWith('UPDATE mayor_billing_credit_checkouts AS'))return stmt;return {bind(...args:any[]){const bound=stmt.bind(...args);return {async run(){if(!invoked){invoked=true;await seedPro();}return bound.run();}};}};}} as unknown as D1Database};await expect(createCreditCheckout(wrapped,actor,data.key,'small',data.row.period_key,provider)).rejects.toMatchObject({code:'credit_quote_changed'});const row=await env.AGENT_DB.prepare('SELECT status FROM mayor_billing_credit_checkouts WHERE id=?').bind(data.row.id).first<any>();expect(row.status).toBe('expired');});
it('rejects a misconfigured amount, recurring pack or catalog revision before Checkout',async()=>{const price=provider.objects.get('/v1/prices/price_small')!;price.unit_amount=1;await expect(checkout()).rejects.toMatchObject({code:'credit_price_mismatch'});price.unit_amount=400;price.metadata.mayor_credit_version='old';const row=await env.AGENT_DB.prepare('SELECT request_id FROM mayor_billing_credit_checkouts WHERE tenant_id=?').bind(actor.tenantId).first<any>();await expect(createCreditCheckout(env,actor,row.request_id,'small',freePeriod().periodKey,provider)).rejects.toMatchObject({code:'credit_price_mismatch'});expect(provider.posts).toHaveLength(0);});
it.each(CREDIT_PACKS.map(pack=>[pack.id,pack.replyAttempts,pack.voiceMinutes] as const))('grants %s pack once after exact paid proof without resetting consumed usage',async(packId,replies,minutes)=>{await seedUsage(77);const data=await checkout(packId);pay(data);const paid=event('checkout.session.completed',data.session);expect(await processBillingEvent(env,paid,provider)).toMatchObject({outcome:'processed'});expect(await processBillingEvent(env,paid,provider)).toMatchObject({outcome:'duplicate'});await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const status=await billingStatus(env,actor);expect(status.usage.replies).toEqual({used:77,limit:100+replies,remaining:23+replies});expect(status.usage.voiceMinutes.limit).toBe(10+minutes);expect(status.credits.purchases[0].status).toBe('paid');expect((await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_grants WHERE tenant_id=?').bind(actor.tenantId).all()).results).toHaveLength(1);});
it('does not grant unpaid or authentication-required credit payments',async()=>{const data=await checkout();const proof=pay(data);data.session.payment_status='unpaid';await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);data.session.payment_status='paid';proof.intent.status='requires_action';await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'credit_payment_unverified'});expect((await billingStatus(env,actor)).usage.replies.limit).toBe(100);});
it('rejects mismatched tenant, period metadata, currency, amount and line quantity without grants',async()=>{const data=await checkout(),proof=pay(data),original=structuredClone(data.session.metadata);data.session.metadata={...original,mayor_tenant_id:'f'.repeat(32)};await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'credit_ownership_mismatch'});data.session.metadata=original;proof.lines.data[0].quantity=2;await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'credit_payment_mismatch'});proof.lines.data[0].quantity=1;proof.intent.amount_received=399;await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'credit_payment_unverified'});proof.intent.amount_received=400;proof.intent.currency='eur';await expect(processBillingEvent(env,event('checkout.session.completed',data.session),provider)).rejects.toMatchObject({code:'credit_payment_unverified'});expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);});
it('shares the last purchased reply atomically across concurrent members',async()=>{const data=await checkout();pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await seedUsage(299);const staff={...actor,userId:crypto.randomUUID()};await env.AGENT_DB.prepare("INSERT INTO agent_memberships(tenant_id,user_id,role) VALUES(?,?,'staff')").bind(actor.tenantId,staff.userId).run();const context=await billingUsageContext(env,actor),results=await Promise.all([reserveMonthlyUsage(env,actor,context,'turn'),reserveMonthlyUsage(env,staff,context,'turn'),reserveMonthlyUsage(env,actor,context,'turn')]);expect(results.filter(value=>value!==undefined)).toEqual([300]);expect((await usageBalance(env,actor)).usage.replies.remaining).toBe(0);});
it('revokes refunded credits against stale usage contexts and never restores them on paid replay',async()=>{const data=await checkout(),proof=pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await seedUsage(150);const stale=await billingUsageContext(env,actor);proof.charge.amount_refunded=1;const refund=event('charge.refunded',proof.charge);await processBillingEvent(env,refund,provider);expect(await reserveMonthlyUsage(env,actor,stale,'turn')).toBeUndefined();expect(await processBillingEvent(env,refund,provider)).toMatchObject({outcome:'duplicate'});await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const status=await billingStatus(env,actor);expect(status.usage.replies).toEqual({used:150,limit:100,remaining:0});expect(status.credits.purchases[0].status).toBe('refunded');});
it('handles refund or dispute before the paid event without resurrecting allowance',async()=>{const data=await checkout(),proof=pay(data);proof.charge.disputed=true;await processBillingEvent(env,event('charge.dispute.created',{id:'dp_fixture',charge:proof.charge.id}),provider);proof.charge.disputed=false;await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);expect((await billingStatus(env,actor)).credits.purchases[0].status).toBe('disputed');});
it('expires credits at the purchased Free month and never rolls over or resets usage',async()=>{const data=await checkout();pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const future=data.row.period_end*1000,stale=await billingUsageContext(env,actor);expect((await billingStatus(env,actor,future)).usage.replies.limit).toBe(100);expect(await reserveMonthlyUsage(env,actor,stale,'turn',future)).toBeUndefined();});
it('records a late paid completion honestly as expired, without granting the next period',async()=>{const data=await checkout();pay(data);const spy=vi.spyOn(Date,'now').mockReturnValue(data.row.period_end*1000+1000);try{await processBillingEvent(env,event('checkout.session.completed',data.session),provider);}finally{spy.mockRestore();}const row=await env.AGENT_DB.prepare('SELECT status FROM mayor_billing_credit_checkouts WHERE id=?').bind(data.row.id).first<any>();expect(row.status).toBe('paid_expired');expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);});
it('permanently expires Free credits on upgrade and does not resurrect them after downgrade',async()=>{const data=await checkout();pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);await seedUsage(145);await seedPro();expect((await billingStatus(env,actor)).usage.replies).toEqual({used:145,limit:1000,remaining:855});await env.AGENT_DB.prepare('UPDATE mayor_billing_paid_periods SET invalidated=1 WHERE tenant_id=?').bind(actor.tenantId).run();await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect((await billingStatus(env,actor)).usage.replies).toEqual({used:145,limit:100,remaining:0});expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);});
it('does not let replay of a refunded Pro invoice expire a newly paid Free pack',async()=>{await seedPro();const period=await env.AGENT_DB.prepare('SELECT stripe_invoice_id,stripe_payment_intent_id FROM mayor_billing_paid_periods WHERE tenant_id=?').bind(actor.tenantId).first<any>(),invoice=provider.objects.get('/v1/invoices/'+period.stripe_invoice_id)!,charge={id:'ch_RefundedPro',livemode:false,customer:invoice.customer,payment_intent:period.stripe_payment_intent_id,amount:1400,amount_refunded:1400,refunded:true};provider.objects.set('/v1/charges/'+charge.id,charge);await processBillingEvent(env,event('charge.refunded',charge),provider);const data=await checkout();pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);expect((await billingStatus(env,actor)).usage.replies.limit).toBe(300);await processBillingEvent(env,event('invoice.paid',invoice),provider);expect((await billingStatus(env,actor)).plan.id).toBe('free');expect((await billingStatus(env,actor)).usage.replies.limit).toBe(300);expect((await billingStatus(env,actor)).credits.purchases[0].status).toBe('paid');});
it('requires review before repeating a provider attempt beyond the safe idempotency window',async()=>{const context=await billingUsageContext(env,actor),key=crypto.randomUUID();provider.unknown=true;await expect(createCreditCheckout(env,actor,key,'small',context.periodKey,provider)).rejects.toThrow();await env.AGENT_DB.prepare('UPDATE mayor_billing_credit_checkouts SET provider_started_at=? WHERE tenant_id=?').bind(Date.now()-24*3600000,actor.tenantId).run();await expect(createCreditCheckout(env,actor,key,'small',context.periodKey,provider)).rejects.toMatchObject({code:'credit_checkout_needs_review'});expect(provider.posts.filter(post=>post.path==='/v1/checkout/sessions')).toHaveLength(1);});
it('retires an unpaid Free quote on upgrade and cannot activate it after Pro then Free',async()=>{const data=await checkout();await seedPro();expect((await billingStatus(env,actor)).credits.checkout.pending).toBe(false);expect((await checkout('medium')).row.period_key.startsWith('pro:')).toBe(true);await env.AGENT_DB.prepare('UPDATE mayor_billing_paid_periods SET invalidated=1 WHERE tenant_id=?').bind(actor.tenantId).run();pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const status=await billingStatus(env,actor);expect(status.credits.replyAttempts).toBe(0);expect(status.credits.checkout.pending).toBe(false);expect(status.credits.purchases[0].status).toBe('paid_expired');});
it('retires an old pending quote at the natural calendar boundary without blocking the next purchase',async()=>{const data=await checkout(),spy=vi.spyOn(Date,'now').mockReturnValue(data.row.period_end*1000+1000);try{const status=await billingStatus(env,actor);expect(status.credits.checkout.pending).toBe(false);expect((await checkout('medium')).row.period_key).not.toBe(data.row.period_key);}finally{spy.mockRestore();}});
it('ties a Pro pack to its verified paid period and does not transfer on a new period or refund',async()=>{const paid=await seedPro(),data=await checkout('medium');pay(data);await processBillingEvent(env,event('checkout.session.completed',data.session),provider);const status=await billingStatus(env,actor);expect(status.usage.replies.limit).toBe(1500);expect(status.usage.voiceMinutes.limit).toBe(165);expect(status.credits.expiresAt).toBe(new Date(paid.end*1000).toISOString());expect((await billingStatus(env,actor,paid.end*1000)).usage.replies.limit).toBe(100);await env.AGENT_DB.prepare('UPDATE mayor_billing_paid_periods SET invalidated=1 WHERE tenant_id=?').bind(actor.tenantId).run();expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(0);});
it('reconciles a paid pending pack through explicit sync and canonical expiration before another purchase',async()=>{const data=await checkout();pay(data);await syncBilling(env,actor,provider);expect((await billingStatus(env,actor)).credits.replyAttempts).toBe(200);const next=await checkout('medium');next.session.status='expired';await syncBilling(env,actor,provider);expect((await billingStatus(env,actor)).credits.checkout.pending).toBe(false);expect((await checkout('large')).session.mode).toBe('payment');});
