import {describe,it,expect} from 'vitest';
import {verifyEmailWebhook,readEmailWebhookBody} from '../src/email/webhook-signature';
// Published Svix known-answer vector, not generated by the implementation under test.
const raw='{"event_type":"ping","data":{"success":true}}',secret='whsec_plJ3nmyCDGBKInavdOK15jsl',now=1731705121000;
function headers(){return new Headers({'svix-id':'msg_loFOjxBNrRLzqYUf','svix-timestamp':'1731705121','svix-signature':'v1,rAvfW3dJ/X/qxhsaXPOyyCGmRKsaKWcsNccKXlIktD0='});}
describe('platform email webhook signature',()=>{
  it('matches the published provider vector and supports a matching signature during rotation',async()=>{
    expect(await verifyEmailWebhook(raw,headers(),secret,now)).toBe('msg_loFOjxBNrRLzqYUf');
    const h=headers();h.set('svix-signature',`v2,unsupported v1,${'A'.repeat(43)}= ${h.get('svix-signature')}`);expect(await verifyEmailWebhook(raw,h,secret,now)).toBe('msg_loFOjxBNrRLzqYUf');
  });
  it('rejects changed bytes, metadata, stale/future delivery timestamps and malformed signatures',async()=>{
    await expect(verifyEmailWebhook(raw+' ',headers(),secret,now)).rejects.toMatchObject({code:'invalid_email_webhook_signature'});
    for(const [name,value] of [['svix-id','msg_other'],['svix-timestamp','1731705122'],['svix-signature','v1,bad'],['svix-signature','x'.repeat(2049)]]){const h=headers();h.set(name,value);await expect(verifyEmailWebhook(raw,h,secret,now)).rejects.toMatchObject({code:'invalid_email_webhook_signature'});}
    for(const offset of [-301000,301000])await expect(verifyEmailWebhook(raw,headers(),secret,now+offset)).rejects.toMatchObject({code:'invalid_email_webhook_signature'});
  });
  it('bounds raw bytes and rejects invalid UTF-8 without changing signed whitespace',async()=>{
    expect(await readEmailWebhookBody(new Request('https://example.test',{method:'POST',body:' '+raw+'\n'}))).toBe(' '+raw+'\n');
    await expect(readEmailWebhookBody(new Request('https://example.test',{method:'POST',body:'x'.repeat(65537)}))).rejects.toMatchObject({code:'email_webhook_too_large'});
    await expect(readEmailWebhookBody(new Request('https://example.test',{method:'POST',body:new Uint8Array([255])}))).rejects.toMatchObject({code:'invalid_email_webhook'});
  });
});
