import {getIndustryPack} from './automations';
const prompts:Record<string,string>={services:'Which services should the agent describe?',service_durations:'How long does each service take?',staff_and_chair_ownership:'Which staff members and chairs can be scheduled?',deposits:'What deposit rules should be explained?',no_show_rules:'What are your no-show rules?',service_area:'Which areas do you serve?',job_types:'Which job types do you accept?',hazard_escalation:'Who should handle inquiries mentioning hazards?',estimate_rules:'What rules apply before an estimate can be offered?',consultation_scope:'What is included in an initial consultation?',confidentiality:'What confidentiality rules should staff follow?',conflict_rules:'Which conflicts require human review?',professional_escalation:'Who handles questions needing professional judgment?',vehicle_fields:'What minimum vehicle details are needed for intake?',service_types:'Which vehicle services do you offer?',mechanic_escalation:'Who should receive technical vehicle questions?',property_ids:'Which authorized property identifiers should be used?',agent_assignment:'How are inquiries assigned to agents?',showing_rules:'What rules apply before a showing is confirmed?',menus:'Which approved menu information can be shared?',hours:'What are your business hours?',catering:'What catering services can be discussed?',private_event_rules:'What rules apply to private-event inquiries?',classes:'Which classes do you offer?',trainer_room_rules:'Which trainers and rooms can be scheduled?',minimum_pet_details:'What minimum pet details are needed for service intake?',preparation_rules:'What preparation instructions are approved?',pickup_rules:'What pickup rules should customers receive?',products:'Which products can the agent describe?',marketing_consent:'How is marketing consent verified?',approved_public_information:'Which approved public information may the agent share? Do not enter patient data.',staff_handoff:'Where should public inquiries be handed to staff?',urgent_care_boundary:'What approved public notice and staff handoff should be used for urgent questions? Do not enter patient details.'};
const shared:Record<string,string>={services:'services',service_durations:'serviceDuration',staff_and_chair_ownership:'staffResources',service_area:'serviceArea',service_types:'services',hours:'hours',products:'services',staff_handoff:'escalationDestination'};
export function industryQuestions(fields:Record<string,string>,answers:Record<string,string>){
  return (getIndustryPack(fields.industryPack)?.requiredFacts??[]).map(field=>{
    const inherited=shared[field]?fields[shared[field]]??'':'',answer=answers[field]?.trim()||inherited.trim();
    return {field,question:prompts[field]??`What are your approved ${field.replaceAll('_',' ')}?`,answer,answered:!!answer,fromBrief:!answers[field]?.trim()&&!!inherited.trim()};
  });
}
