import { CATALOG_VERSION, deepFreeze } from "./catalog";

export interface ProductPriceEvidence {
  readonly label: string; readonly amountCents: number; readonly cadence: "one_time" | "week" | "month" | "year";
  readonly status: "observed_source_not_live_billing" | "future_proposal_not_authorized";
}
export interface ProductReadInterface {
  readonly method: "GET"; readonly origin: string; readonly path: string; readonly queryKeys: readonly string[];
  readonly purpose: "payment_status" | "order_status" | "deliverable";
  readonly sourceVerified: true; readonly liveVerified: false;
}
export interface PortfolioProduct {
  readonly id: string; readonly name: string; readonly site: string; readonly version: string;
  readonly purpose: string; readonly repositories: readonly string[];
  readonly sourceCoverage: "integration_source_reviewed" | "empty_repository" | "readme_only" | "placeholder" | "no_billing_source" | "source_deployment_mismatch";
  readonly billingSystem: "legacy_central" | "independent_base44" | "unverified" | "affiliate";
  readonly legacySkus: readonly string[]; readonly checkoutMetadataKeys: readonly string[];
  readonly priceEvidence: readonly ProductPriceEvidence[]; readonly observedOn: "2026-09-16";
  readonly agentOperations: readonly ["read_verified_status", "draft_owner_support"];
  readonly proposedCapabilities: readonly string[]; readonly limits: readonly string[];
  readonly readInterfaces: readonly ProductReadInterface[];
  readonly access: { readonly mode: "read_only"; readonly ownershipVerificationRequired: true; readonly emailMatchLinksAccounts: false; readonly canModifyLegacy: false; readonly canTriggerLegacyFulfillment: false; readonly canReplayWebhooks: false; readonly canCreateLegacyPurchase: false };
  readonly readiness: { readonly integration: "pending_read_adapter_and_live_verification"; readonly executorEnabled: false; readonly missing: readonly string[] };
}
const price = (label: string, amountCents: number, cadence: ProductPriceEvidence["cadence"] = "one_time", proposed = false): ProductPriceEvidence => ({ label, amountCents, cadence, status: proposed ? "future_proposal_not_authorized" : "observed_source_not_live_billing" });
const read = (origin: string, path: string, purpose: ProductReadInterface["purpose"] = "order_status"): ProductReadInterface => ({ method: "GET", origin, path, queryKeys: ["token"], purpose, sourceVerified: true, liveVerified: false });
const centralStatus = read("https://mehyar.us", "/api/pay/status", "payment_status");
type ProductInput = Omit<PortfolioProduct, "version" | "observedOn" | "agentOperations" | "access" | "readiness"> & { missing?: string[] };
function product(input: ProductInput): PortfolioProduct {
  const { missing = [], ...fields } = input;
  return { ...fields, version: CATALOG_VERSION, observedOn: "2026-09-16", agentOperations: ["read_verified_status", "draft_owner_support"],
    access: { mode: "read_only", ownershipVerificationRequired: true, emailMatchLinksAccounts: false, canModifyLegacy: false, canTriggerLegacyFulfillment: false, canReplayWebhooks: false, canCreateLegacyPurchase: false },
    readiness: { integration: "pending_read_adapter_and_live_verification", executorEnabled: false, missing: ["verified_owner_authorization", "read_adapter_implementation", "live_read_acceptance", "read_only_billing_reconciliation", ...missing] } };
}

/** Evidence map only. Existing purchase and fulfillment code is neither imported nor executed. */
export const PORTFOLIO: readonly PortfolioProduct[] = deepFreeze([
  product({ id: "rizza", name: "Rizza", site: "https://rizza.app", purpose: "Private dating-conversation reply suggestions", repositories: ["mehyar500/rizza-app"], sourceCoverage: "integration_source_reviewed", billingSystem: "independent_base44", legacySkus: [], checkoutMetadataKeys: ["trial", "plan"], priceEvidence: [price("Pro monthly", 999, "month"), price("Pro weekly", 300, "week")], proposedCapabilities: ["private_reply_suggestions", "account_support", "entitlement_checks"], limits: ["preserve_free_20_replies_per_month_and_existing_unlimited_promises", "no_automatic_dating_messages", "no_personality_from_photo_claims", "preserve_independent_base44_billing"], readInterfaces: [], missing: ["documented_base44_read_interface"] }),
  product({ id: "aimech", name: "AiMech", site: "https://aimech.app", purpose: "Informational vehicle diagnostics and maintenance help", repositories: ["mehyar500/ai-mechanic"], sourceCoverage: "integration_source_reviewed", billingSystem: "independent_base44", legacySkus: [], checkoutMetadataKeys: ["priceId", "plan"], priceEvidence: [price("DIY monthly", 499, "month"), price("DIY annual", 4788, "year"), price("Mechanic monthly", 1499, "month"), price("Mechanic annual", 14388, "year")], proposedCapabilities: ["vehicle_intake", "informational_assistance", "maintenance_reminders"], limits: ["qualified_mechanic_for_safety_critical_issues", "preserve_independent_base44_billing"], readInterfaces: [], missing: ["documented_base44_read_interface"] }),
  product({ id: "babypeek", name: "BabyPeek", site: "https://baby.mehyar.us", purpose: "Entertainment future-baby portrait", repositories: ["mehyar-us/venture-babypeek"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["baby-peek"], checkoutMetadataKeys: ["gid"], priceEvidence: [price("Portrait unlock", 500)], proposedCapabilities: ["consent_aware_intake", "preview", "private_delivery", "deletion_support"], limits: ["legacy_redeem_and_generation_are_not_read_operations", "protect_parent_photos"], readInterfaces: [centralStatus] }),
  product({ id: "roastme", name: "RoastMe", site: "https://roast.mehyar.us", purpose: "Playful AI roast cards", repositories: ["mehyar500/venture-roast"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["roast-card"], checkoutMetadataKeys: ["roast_id"], priceEvidence: [price("One card", 500), price("Future three-card proposal", 1200, "one_time", true)], proposedCapabilities: ["moderation", "card_generation", "optional_user_directed_share"], limits: ["no_legacy_unlock_calls", "new_pack_not_authorized_for_sale"], readInterfaces: [centralStatus] }),
  product({ id: "crayonkid", name: "Crayon Kid", site: "https://crayonkid.mehyar.us", purpose: "Personalized printable coloring book", repositories: ["mehyar500/venture-crayonkid"], sourceCoverage: "placeholder", billingSystem: "unverified", legacySkus: [], checkoutMetadataKeys: [], priceEvidence: [price("Future 12-page PDF proposal", 900, "one_time", true)], proposedCapabilities: ["parent_led_intake", "line_art_checks", "name_placement", "print_ready_pdf"], limits: ["coming_soon_source_is_not_working_fulfillment", "child_data_minimization", "price_requires_image_cost_gate"], readInterfaces: [], missing: ["product_runtime", "payment_contract"] }),
  product({ id: "mehyarjobs", name: "mehyar.jobs", site: "https://jobs.mehyar.us", purpose: "Career discovery and explained fit scoring", repositories: ["mehyar500/mehyar-jobs"], sourceCoverage: "no_billing_source", billingSystem: "unverified", legacySkus: [], checkoutMetadataKeys: [], priceEvidence: [price("Future daily matching proposal", 1900, "month", true)], proposedCapabilities: ["source_refresh", "deduplication", "freshness_checks", "fit_explanations", "digests"], limits: ["free_weekly_digest_is_future_proposal", "no_autonomous_mass_applications", "source_access_and_freshness_required"], readInterfaces: [], missing: ["verified_billing_contract", "authorized_read_api"] }),
  product({ id: "stuffprettygood", name: "Stuff Pretty Good", site: "https://stuffprettygood.com", purpose: "Affiliate shopping guides and digital guides", repositories: ["mehyar-us/stuffprettygood.com", "mehyar-us/stuffprettygood-api"], sourceCoverage: "source_deployment_mismatch", billingSystem: "affiliate", legacySkus: [], checkoutMetadataKeys: [], priceEvidence: [price("Home Office PDF", 900), price("Gift-Proof PDF", 700)], proposedCapabilities: ["catalog_checks", "editorial_drafts", "affiliate_disclosure", "subscriber_preferences"], limits: ["public_guide_prices_not_proof_of_source_checkout", "merchant_controlled_purchases", "do_not_invent_reviews"], readInterfaces: [], missing: ["source_deployed_guide_contract_reconciliation"] }),
  product({ id: "designful", name: "Designful", site: "https://designful.mehyar.us", purpose: "Fixed-scope design outputs", repositories: ["mehyar500/venture-designful"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["designful-homepage-teardown", "designful-logo-refresh", "designful-ad-creative-pack", "designful-social-launch-kit", "designful-hero-rewrite", "designful-bundle-3", "designful-studio-pass"], checkoutMetadataKeys: ["url", "hero_copy", "product_description", "brand_blurb", "brand_name", "industry", "current_logo_desc", "choices"], priceEvidence: [price("Individual feature", 4900), price("Any three", 9900), price("Studio Pass", 14900)], proposedCapabilities: ["brief_status_observation", "order_status_observation", "support_drafts"], limits: ["preserve_exact_bundle_entitlements", "no_second_generator_or_sender", "no_legacy_backfill"], readInterfaces: [centralStatus, read("https://designful.mehyar.us", "/api/designful/deliverable", "deliverable")] }),
  product({ id: "hustlekit", name: "HustleKit", site: "https://hustlekit.mehyar.us", purpose: "Three-track personalized side-hustle playbook", repositories: ["mehyar500/venture-hustlekit"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["hustlekit-starter"], checkoutMetadataKeys: ["track", "skills", "hours_per_week", "income_goal", "experience_level", "niche"], priceEvidence: [price("Starter playbook", 2700)], proposedCapabilities: ["intake", "sample", "playbook_quality_checks", "optional_progress_reminders"], limits: ["no_income_guarantee", "legacy_generation_unchanged"], readInterfaces: [centralStatus, read("https://hustlekit.mehyar.us", "/api/hustlekit/status")] }),
  product({ id: "sprint30", name: "Sprint30", site: "https://sprint30.mehyar.us", purpose: "30-day mission challenge and progress dashboard", repositories: ["mehyar500/venture-sprint30"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["sprint30-challenge"], checkoutMetadataKeys: ["source", "product"], priceEvidence: [price("Challenge", 3700)], proposedCapabilities: ["enrollment_status", "progress_observation", "support_drafts"], limits: ["preserve_first_three_days_preview", "no_second_daily_scheduler", "no_legacy_resume_unsubscribe_or_resend_effects"], readInterfaces: [centralStatus, read("https://sprint30.mehyar.us", "/api/sprint30/status")] }),
  product({ id: "bizbuilder", name: "BizBuilder", site: "https://bizbuilder.mehyar.us", purpose: "Business plan, landing copy and five-email sequence", repositories: ["mehyar500/venture-bizbuilder"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["bizbuilder-plan"], checkoutMetadataKeys: ["idea", "audience", "price_point"], priceEvidence: [price("Plan", 1700)], proposedCapabilities: ["idea_intake", "plan_quality_checks", "export_support"], limits: ["copy_does_not_authorize_deployment_or_sending", "no_legacy_backfill"], readInterfaces: [centralStatus, read("https://bizbuilder.mehyar.us", "/api/bizbuilder/deliverable", "deliverable")] }),
  product({ id: "creditfixkit", name: "CreditFix Kit", site: "https://creditfixkit.mehyar.us", purpose: "DIY credit education and document templates", repositories: ["mehyar500/venture-creditfixkit"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["creditfix-kit"], checkoutMetadataKeys: ["name", "situation", "state", "goal", "accounts"], priceEvidence: [price("Kit", 4700)], proposedCapabilities: ["educational_templates", "document_completeness", "reminder_design"], limits: ["no_credit_bureau_connection", "no_automatic_dispute_filing", "no_score_improvement_promise", "sensitive_financial_data_review"], readInterfaces: [centralStatus, read("https://creditfixkit.mehyar.us", "/api/creditfix/deliverable", "deliverable")] }),
  product({ id: "prepguide", name: "PrepGuide", site: "https://prepguide.mehyar.us", purpose: "Household preparedness plan", repositories: ["mehyar-us/venture-prepguide"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["prepguide-playbook"], checkoutMetadataKeys: [], priceEvidence: [price("Playbook", 3700)], proposedCapabilities: ["household_intake", "deterministic_quantity_checks", "sourced_guidance", "private_pdf"], limits: ["verify_household_metadata_schema_before_adapter", "no_unverified_safety_advice"], readInterfaces: [centralStatus], missing: ["exact_flat_household_metadata_schema"] }),
  product({ id: "truesketch", name: "TrueSketch", site: "https://truesketch.mehyar.us", purpose: "Entertainment portrait and personal reading", repositories: ["mehyar500/venture-truesketch"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["truesketch-reading"], checkoutMetadataKeys: ["intake_id", "name"], priceEvidence: [price("Reading and sketch", 3700)], proposedCapabilities: ["private_gallery_status", "delivery_support", "deletion_support"], limits: ["entertainment_only", "no_factual_prediction_claims", "billing_token_must_not_be_rewritten"], readInterfaces: [centralStatus, read("https://truesketch.mehyar.us", "/api/order-status")] }),
  product({ id: "tiktokgrowth", name: "TikTok Growth System", site: "https://tiktokgrowth.mehyar.us", purpose: "30-day content plan, hooks and bio pack", repositories: ["mehyar500/venture-tiktokgrowth"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["tiktokgrowth-system"], checkoutMetadataKeys: ["niche", "on_camera", "hours_per_week", "handle"], priceEvidence: [price("Growth playbook", 2700)], proposedCapabilities: ["plan_status_observation", "export_support", "publishing_recommendations"], limits: ["preserve_five_hook_teaser", "publishing_requires_separate_approved_capability", "no_legacy_drive_backfill_or_generator_calls"], readInterfaces: [centralStatus, read("https://tiktokgrowth.mehyar.us", "/api/tiktok/deliverable", "deliverable")] }),
  product({ id: "plrvault", name: "PLR Vault", site: "https://plrvault.mehyar.us", purpose: "Licensed rebrandable digital packs", repositories: ["mehyar500/venture-plrvault"], sourceCoverage: "integration_source_reviewed", billingSystem: "legacy_central", legacySkus: ["plrvault-bundle"], checkoutMetadataKeys: [], priceEvidence: [price("Vault bundle", 995)], proposedCapabilities: ["entitlement_observation", "license_support", "download_support"], limits: ["verify_asset_resale_rights", "preserve_original_download_links"], readInterfaces: [centralStatus] }),
  product({ id: "freelanceros", name: "FreelancerOS", site: "https://freelanceros.mehyar.us", purpose: "Freelance client tracker, invoices, board and templates", repositories: ["mehyar500/venture-freelanceros"], sourceCoverage: "readme_only", billingSystem: "legacy_central", legacySkus: ["freelanceros-os"], checkoutMetadataKeys: [], priceEvidence: [price("Lifetime dashboard and templates", 2900)], proposedCapabilities: ["purchase_status_observation", "optional_separate_agent_subscription"], limits: ["preserve_lifetime_entitlement", "do_not_convert_purchase_into_subscription", "satellite_runtime_not_verified"], readInterfaces: [centralStatus], missing: ["satellite_source_and_dashboard_contract"] }),
  product({ id: "promptpack", name: "PromptPack Pro", site: "https://promptpack.mehyar.us", purpose: "50 trade-specific prompts and 10 swipe files", repositories: ["mehyar500/venture-promptpack"], sourceCoverage: "empty_repository", billingSystem: "legacy_central", legacySkus: [], checkoutMetadataKeys: ["profession"], priceEvidence: [price("Prompt pack", 1900)], proposedCapabilities: ["order_status_observation", "completeness_review_design", "private_delivery_support"], limits: ["preserve_five_prompt_teaser", "no_replacement_browser_driven_generation", "sku_unverified_in_remote_source"], readInterfaces: [centralStatus], missing: ["satellite_source", "verified_sku", "generation_contract"] }),
]);

export const INTERNAL_FIRST_TENANT = deepFreeze({ name: "MehyarSoft", scope: "explicitly_authorized_internal_business", observedOffers: ["free_audit", "five_dollar_report", "199_deep_audit_request", "330_technical_audit_request", "service_qualification", "proposals", "scheduling", "followup", "paid_onboarding"], legacyAccess: "read_only", invoiceRequestIsPayment: false });
export function getProduct(id: string): PortfolioProduct | undefined { return PORTFOLIO.find((item) => item.id === id); }
export function portfolioCatalog() { return JSON.parse(JSON.stringify({ version: CATALOG_VERSION, products: PORTFOLIO, firstInternalTenant: INTERNAL_FIRST_TENANT })); }

/** Static allowlist check only; the broker must separately verify tenant/order ownership and live readiness. */
export function assertPortfolioReadContract(productId: string, method: string, rawUrl: string): ProductReadInterface {
  if (method !== "GET") throw new Error("legacy_write_prohibited");
  const product = getProduct(productId);
  if (!product) throw new Error("unknown_product");
  let url: URL;
  try { url = new URL(rawUrl); } catch { throw new Error("invalid_read_url"); }
  if (url.username || url.password || url.hash) throw new Error("invalid_read_url");
  const contract = product.readInterfaces.find((entry) => entry.origin === url.origin && entry.path === url.pathname);
  if (!contract) throw new Error("unverified_legacy_read_interface");
  for (const key of url.searchParams.keys()) if (!contract.queryKeys.includes(key)) throw new Error("unexpected_read_parameter");
  if (contract.queryKeys.some((key) => url.searchParams.getAll(key).length !== 1 || !url.searchParams.get(key))) throw new Error("missing_or_duplicate_read_parameter");
  return contract;
}
