-- Additive tenant-scoped goals/skills and operator-specific bounded agent runs.
CREATE TABLE mayor_harness_state(tenant_id TEXT PRIMARY KEY REFERENCES agent_tenants(id),revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0));
CREATE TABLE mayor_harness_identity(tenant_id TEXT PRIMARY KEY REFERENCES agent_tenants(id),mission TEXT NOT NULL,tone TEXT NOT NULL CHECK(tone IN ('warm','professional','direct')),principles_json TEXT NOT NULL,working_style TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>0),updated_by TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE mayor_harness_goals(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES agent_tenants(id),title TEXT NOT NULL,description TEXT NOT NULL,metric_json TEXT,deadline TEXT,archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)),revision INTEGER NOT NULL CHECK(revision>0),created_by TEXT NOT NULL,updated_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX mayor_harness_goals_tenant ON mayor_harness_goals(tenant_id,archived);
CREATE TABLE mayor_harness_skills(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES agent_tenants(id),title TEXT NOT NULL,instructions TEXT NOT NULL,allowed_tools_json TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)),revision INTEGER NOT NULL CHECK(revision>0),created_by TEXT NOT NULL,updated_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX mayor_harness_skills_tenant ON mayor_harness_skills(tenant_id,archived);
CREATE TABLE mayor_harness_configs(tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)),goal_ids_json TEXT NOT NULL,skill_ids_json TEXT NOT NULL,connector_options_json TEXT NOT NULL,schedule_json TEXT,revision INTEGER NOT NULL CHECK(revision>0),next_run_at TEXT,due_local_date TEXT,lease_token TEXT,lease_until TEXT,last_run_at TEXT,last_status TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(tenant_id,user_id),FOREIGN KEY(tenant_id,user_id) REFERENCES agent_memberships(tenant_id,user_id),CHECK(enabled=0 OR (schedule_json IS NOT NULL AND next_run_at IS NOT NULL AND due_local_date IS NOT NULL)));
CREATE INDEX mayor_harness_due ON mayor_harness_configs(enabled,next_run_at,lease_until);
CREATE TABLE mayor_harness_runs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,config_revision INTEGER NOT NULL,data_revision INTEGER NOT NULL,memory_revision INTEGER NOT NULL DEFAULT 0,dedupe_key TEXT NOT NULL,trigger_kind TEXT NOT NULL CHECK(trigger_kind IN ('manual','scheduled')),state TEXT NOT NULL CHECK(state IN ('processing','ready','failed','blocked','canceled')),lease_token TEXT,lease_until TEXT,report_json TEXT,error_code TEXT,reply_attempt_counted INTEGER NOT NULL DEFAULT 0 CHECK(reply_attempt_counted IN (0,1)),model_started_at TEXT,read_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,user_id,dedupe_key),FOREIGN KEY(tenant_id,user_id) REFERENCES mayor_harness_configs(tenant_id,user_id),CHECK(state!='ready' OR report_json IS NOT NULL));
CREATE INDEX mayor_harness_history ON mayor_harness_runs(tenant_id,user_id,updated_at);
CREATE TABLE mayor_harness_proposals(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('goal','skill','config','task','identity')),input_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('pending','confirmed')),expires_at TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(tenant_id,user_id) REFERENCES agent_memberships(tenant_id,user_id));
CREATE INDEX mayor_harness_proposals_scope ON mayor_harness_proposals(tenant_id,user_id,state,expires_at);
CREATE TABLE mayor_harness_task_acceptances(tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,run_id TEXT NOT NULL REFERENCES mayor_harness_runs(id),draft_id TEXT NOT NULL,task_id TEXT NOT NULL REFERENCES mayor_tasks(id),input_json TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(tenant_id,run_id,draft_id),FOREIGN KEY(tenant_id,user_id) REFERENCES agent_memberships(tenant_id,user_id));
