import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, ShieldCheck } from "lucide-react";
import VisualExplorer from "@/components/VisualExplorer";
const sectors=[
  {id:"technology",label:"Technology",title:"Keep engineering knowledge useful.",intro:"Turn approved product, support and engineering documentation into a practical assistant for your team.",steps:["Retrieve from reviewed documentation with source references","Prepare support responses and incident summaries","Route uncertain answers and proposed changes to their owners"],ask:"Show a proposed workflow for an enterprise technology team's knowledge and support assistant, with sources and human review."},
  {id:"health",label:"Healthcare",title:"Give administrative work a clear next step.",intro:"Explore approved service information, administrative intake and staff knowledge workflows with defined data boundaries.",steps:["Start with public or explicitly approved non-clinical knowledge","Limit who can access each record or system","Route clinical questions and sensitive decisions to qualified staff"],ask:"Show an administrative AI workflow for a healthcare organization with restricted access and human handoff, without clinical decision making."},
  {id:"pharma",label:"Pharma & life sciences",title:"Build around quality and change control.",intro:"Scope an internal knowledge or document-assistance pilot around your existing quality system and approval process.",steps:["Identify controlled documents and approved versions","Prepare drafts with traceable references and review state","Agree validation evidence and change-control responsibilities before use"],ask:"Show a proposed pharmaceutical document-assistance pilot with controlled sources, traceability, quality review and change control. Do not claim validated compliance."},
  {id:"finance",label:"Finance",title:"Make operational knowledge easier to use.",intro:"Connect approved policy and product information to staff workflows, with permissions and clear review boundaries.",steps:["Respect access roles and information boundaries","Draft summaries and operational replies for review","Keep lending, investment and other sensitive decisions with accountable people"],ask:"Compare an internal financial-services knowledge assistant with a search portal. Include data access, approval, traceability and high-stakes decision boundaries."},
  {id:"enterprise",label:"Enterprise operations",title:"Connect the work between systems.",intro:"Explore cross-team requests, knowledge, reporting and approved actions without replacing the tools that already work.",steps:["Map the workflow, systems, data owners and access roles","Start with a measurable, limited pilot","Define monitoring, failure recovery, approvals and support ownership"],ask:"Show a cross-team enterprise AI pilot with approved knowledge, access roles, integrations, review, monitoring and rollback."},
];
export default function Enterprise(){const[sector,setSector]=useState(sectors[0]);return <>
  <section className="site-hero px-4"><div className="site-shell enterprise-intro"><div><p className="site-eyebrow"><ShieldCheck size={16}/> Enterprise & regulated teams</p><h1 className="site-display mt-4">AI that fits the way<br/>your organization works.</h1><p className="site-lede mt-5">Custom software and AI for larger teams, complex systems and work that needs clear accountability. Start with a useful pilot and explicit controls.</p><Link className="mayor-primary w-fit" href="/contact?service=automation-sprint&source=enterprise">Discuss a pilot <ArrowRight size={17}/></Link></div><figure><img src="/assets/sales-system/ai-system.webp" alt="Illustrative concept of knowledge and tools connected in an AI workflow" width="800" height="600" loading="eager"/><figcaption className="mt-3 text-xs text-muted-foreground">System concept, not a live customer integration.</figcaption></figure></div></section>
  <section className="px-4 py-12"><div className="site-shell"><p className="site-eyebrow">Different work. Deliberate boundaries.</p><div className="enterprise-sector-tabs" role="group" aria-label="Enterprise sectors">{sectors.map(s=><button key={s.id} aria-pressed={s.id===sector.id} onClick={()=>setSector(s)}>{s.label}</button>)}</div><article className="enterprise-detail"><div><h2>{sector.title}</h2><p>{sector.intro}</p><Link href={`/explore?topic=${encodeURIComponent(sector.ask)}`} className="inline-flex min-h-11 items-center gap-2 underline">Ask The Mayor about this <ArrowRight size={17}/></Link></div><ol>{sector.steps.map((step,i)=><li key={step}><span className="site-eyebrow mr-3">0{i+1}</span>{step}</li>)}</ol></article>
  <div className="enterprise-guardrails">{[["Data & access","Agree approved sources, data handling, roles, retention and integration permissions before connecting a system."],["Review & evidence","Define test cases, references, human approvals and the evidence your team needs to assess the pilot."],["Operations & ownership","Agree monitoring, usage costs, support, change control, failure recovery and who owns each action."]].map(([title,text])=><div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><p className="mt-9 max-w-4xl text-sm leading-7 text-muted-foreground">These are workflows to scope, not certifications or a promise of regulatory compliance. Suitability, contractual controls and validation requirements need review by your organization's responsible teams. This public assistant does not receive or connect to patient, financial or proprietary records.</p></div></section>
  <section className="px-4 py-12 bg-secondary"><div className="site-shell grid gap-10 md:grid-cols-2"><div><p className="site-eyebrow">A small start inside a larger system</p><h2 className="mt-4 text-3xl font-semibold">Define the pilot before expanding it.</h2><p className="mt-5 leading-8 text-muted-foreground">Choose one workflow, approved knowledge, a small user group, review rules and success measures. Test the failure cases alongside the happy path. Expand when the evidence supports it.</p><Link href="/portfolio" className="mt-4 inline-flex min-h-11 items-center underline">Explore illustrative delivery patterns</Link></div><VisualExplorer topic={sector.ask}/></div></section>
</>;}
