import { Link } from "wouter";
import { ArrowRight, Check } from "lucide-react";
import MayorPlans from "@/components/MayorPlans";
import { useExplorer } from "@/components/MayorStore";
import { industryOffers } from "@/data/industry-offers";

export default function Mayor() {
  const mayor=useExplorer();
  return <>
    <section className="site-hero"><div className="site-shell enterprise-intro">
      <div><p className="site-eyebrow">The Mayor · AI for your business</p><h1 className="site-display mt-4">Meet the Mayor<br/>of your business.</h1><p className="site-lede mt-5">A little clarity for every workday. Bring your business knowledge, customers, tasks and appointments together, with an AI assistant you can talk to.</p><div className="flex flex-wrap gap-4 mt-6"><a className="mayor-primary" href="https://mayor.mehyar.us" target="_blank" rel="noopener noreferrer">Sign in & start free <ArrowRight size={17}/></a><button className="inline-flex items-center gap-2 min-h-11 underline" onClick={()=>mayor.launch('What can The Mayor help me manage in my local business? Show useful examples.')}>Try a public conversation <ArrowRight size={17}/></button></div><p className="mt-4 text-sm text-muted-foreground">Free $0 · Pro $14 USD/month. Your private workspace needs sign-in. Public questions here need no account.</p></div>
      <figure><img src="/assets/agent-services/mobile-command-assistant.webp" alt="Illustrative concept of a business owner working with an AI assistant" width="800" height="600" loading="eager"/><figcaption className="mt-3 text-xs text-muted-foreground">Illustrative concept. Features and connected actions depend on account setup.</figcaption></figure>
    </div></section>
    <section className="px-4 py-14"><div className="site-shell"><p className="site-eyebrow">Less scattered. More useful.</p><h2 className="text-3xl font-semibold mt-3">Make the next step easier.</h2><div className="grid md:grid-cols-3 gap-8 mt-8">{[
      ['Know your business','Keep confirmed business facts, services and booking rules close. Save goals, update progress yourself and give The Mayor context for more useful conversations.'],
      ['Plan the next move','Review customers, tasks and Mayor-created appointments. Choose reusable playbooks for priorities, callbacks and booking preparation. Run a planning review or enable daily or weekday reports.'],
      ['Stay in control','Automatic reviews start paused. Reports offer draft recommendations; review and confirm a suggested task before saving it. Calendar connections and bookings need separate setup and approvals.']
    ].map(([title,copy])=><article key={title} className="border-t border-border pt-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{copy}</p></article>)}</div><p className="mt-7 text-sm leading-7 text-muted-foreground">Owners and managers can open <strong className="font-medium text-foreground">Today → Business agent</strong> to choose goals, skills and a review schedule. Add reusable instructions and choose how The Mayor should work with you.</p></div></section>
    <section className="px-4 py-14 bg-secondary"><div className="site-shell"><div className="studio-section-heading"><div><p className="site-eyebrow">Your neighborhood. Your way of working.</p><h2>Built around the business you run.</h2></div><Link href="/enterprise">Larger team? Explore custom AI <ArrowRight size={17}/></Link></div><div className="studio-image-grid">{[industryOffers[0],industryOffers[3],industryOffers[5]].map(industry=><Link href={`/industries/${industry.id}`} key={industry.id} className="studio-image-link"><img src={industry.heroImage} alt={`${industry.shortName}; illustrative business setting`} width="800" height="600" loading="lazy"/><span><strong>{industry.shortName}</strong><small>Explore workflows for your business</small><ArrowRight size={20}/></span></Link>)}</div><p className="mt-6 leading-7 text-muted-foreground">Salons, restaurants, trades, retail, studios and professional services. Enterprise, health, pharma and finance teams can discuss a separately scoped system with the access, review and controls their work requires.</p></div></section>
    <MayorPlans/>
    <section className="px-4 py-14"><div className="site-shell grid md:grid-cols-2 gap-10"><div><p className="site-eyebrow">From a question to your workspace</p><h2 className="text-3xl font-semibold mt-3">Start small. Make it useful.</h2><ol className="mt-6 space-y-4 leading-7"><li>1. Sign in to The Mayor with an account you control.</li><li>2. Tell it about your business and confirm the details.</li><li>3. Add your tasks, customers and first goal. Choose the playbooks that fit your work.</li><li>4. Review your plan and usage inside the workspace. Pro payment and activation happen there.</li></ol><a href="https://mayor.mehyar.us" target="_blank" rel="noopener noreferrer" className="mayor-primary mt-6 w-fit">Open your Mayor workspace <ArrowRight size={17}/></a></div><div className="rounded-2xl border border-border p-7"><h3 className="text-xl font-semibold">Know what you’re connecting.</h3><ul className="mt-5 space-y-4 text-sm leading-7">{['Signing in does not grant calendar or inbox access. Optional report sources need an explicit selection and existing permission.','Planning reports do not send messages, publish posts, take payments or change calendars.','Bookings need a working connection, rules and confirmation. Phone services and other integrations need separate setup and provider charges.','This public site cannot read your private Mayor account. Saved public chats do not sync to it.'].map(text=><li key={text} className="flex gap-3"><Check size={18} className="shrink-0 mt-1 text-primary"/><span>{text}</span></li>)}</ul><p className="mt-5 text-sm leading-7 text-muted-foreground">Sensitive regulated workflows need an appropriate agreement and configuration.</p></div></div></section>
  </>;
}
