import {defineConfig} from 'vite';
import {resolve} from 'node:path';
import {readdirSync} from 'node:fs';

/** Static vertical sales pages generated by scripts/gen-sales-verticals.mjs. */
function verticalInputs(){
  const entries={};
  let files=[];
  try{files=readdirSync('web/sales').filter(f=>f.endsWith('.html'));}catch{files=[];}
  for(const file of files){
    const slug=file.replace(/\.html$/,'');
    entries[`sales-${slug}`]=resolve(`web/sales/${file}`);
  }
  return entries;
}

export default defineConfig({root:'web',css:{postcss:{plugins:[]}},build:{outDir:'../public',emptyOutDir:true,rollupOptions:{input:{main:resolve('web/index.html'),audit:resolve('web/business-audit.html'),sales:resolve('web/sales.html'),...verticalInputs()}}},server:{host:'127.0.0.1',port:5175,proxy:{'/api':'http://127.0.0.1:8790','/agents':{target:'ws://127.0.0.1:8790',ws:true}}}});
