import {runBusinessAudits,type BusinessAuditEnv,type AuditInference} from '../../src/business-audit';
import {AUDIT_ANALYSIS_MODEL,AUDIT_REVIEW_MODEL} from '../../src/business-audit-schema';
interface ProbeEnv extends BusinessAuditEnv {PROBE_KEY:string;}
function queuedContextMetadata(input:Record<string,unknown>){
 const request=(input.requests as {external_reference?:string;messages?:{role:string;content:string}[]}[]|undefined)?.[0];
 if(!request)return {};
 const content=request.messages?.find(message=>message.role==='user')?.content;
 try{
  const payload=JSON.parse(content??'null') as {task?:unknown;review?:unknown;server_quality_diagnostics?:unknown;server_quality_guidance?:unknown}|null;
  const knownCodes=new Set(['action_placeholder','unsupported_scope_claim','unsupported_trust_absence','customer_permission_unverified','customer_pilot_unverified','unsupported_measurement_target','existing_tools_unverified','unsupported_copy_promise']);
  const diagnostics=Array.isArray(payload?.server_quality_diagnostics)?payload.server_quality_diagnostics.slice(0,32):[];
  const codes=diagnostics.flatMap(item=>item&&typeof item==='object'&&'code' in item&&typeof item.code==='string'&&knownCodes.has(item.code)?[item.code]:[]);
  const guidance=Array.isArray(payload?.server_quality_guidance)?payload.server_quality_guidance.slice(0,8):[],guidanceCodes=guidance.flatMap(item=>item&&typeof item==='object'&&'code' in item&&typeof item.code==='string'&&knownCodes.has(item.code)?[item.code]:[]);
  return {requestStage:request.external_reference?.split(':')[2]??null,requestTask:typeof payload?.task==='string'?payload.task:null,priorReviewIncluded:!!payload&&Object.prototype.hasOwnProperty.call(payload,'review'),qualityDiagnosticCount:diagnostics.length,qualityDiagnosticCodes:[...new Set(codes)],qualityGuidanceCount:guidanceCodes.length,qualityGuidanceCodes:[...new Set(guidanceCodes)]};
 }catch{return {requestStage:null,requestTask:null,priorReviewIncluded:null};}
}
export default {async fetch(request:Request,env:ProbeEnv){
 if(!env.PROBE_KEY||request.headers.get('x-mayor-probe-key')!==env.PROBE_KEY)return Response.json({error:'unauthorized'},{status:401});
 const path=new URL(request.url).pathname;
 try{
  if(request.method==='GET'&&path==='/ready')return Response.json({ready:true});
  if(request.method==='POST'&&path==='/models'){
   const binding=env.AI as unknown as {run:AuditInference},results=[];
   for(const model of [AUDIT_ANALYSIS_MODEL,AUDIT_REVIEW_MODEL]){const started=Date.now();try{const output=await binding.run(model,{messages:[{role:'system',content:'Return only JSON with the boolean field probe set to true.'},{role:'user',content:'This is a synthetic model availability probe.'}],max_completion_tokens:512,reasoning_effort:'none',stream:false,store:false,response_format:{type:'json_schema',json_schema:{name:'mayor_probe',strict:true,schema:{type:'object',properties:{probe:{type:'boolean'}},required:['probe'],additionalProperties:false}}}});const response=output as {choices?:{finish_reason?:string;message?:{content?:string}}[];usage?:unknown};results.push({model,elapsedMs:Date.now()-started,finishReason:response.choices?.[0]?.finish_reason??null,content:response.choices?.[0]?.message?.content??null,usage:response.usage??null});}catch(error){const message=error instanceof Error?error.message:'';results.push({model,elapsedMs:Date.now()-started,failureCategory:/paid|billing|credits/i.test(message)?'paid_access_required':/schema|response_format|validation|parameter/i.test(message)?'input_schema_rejected':/not found|not supported|not enabled|model.*unavailable/i.test(message)?'model_not_available':'provider_error'});}}
   return Response.json({synthetic:true,models:results});
  }
  if(request.method==='GET'&&path==='/network'){
   const website=new URL(request.url).searchParams.get('website');if(!website||!/^https:\/\/mayor-audit-site-[a-f0-9]+\.[a-z0-9-]+\.workers\.dev\/$/.test(website))return Response.json({error:'unsafe_fixture'},{status:400});
   const results=await Promise.all(['cloudflare','google'].flatMap(provider=>['A','AAAA'].map(async type=>{try{const endpoint=provider==='cloudflare'?'https://cloudflare-dns.com/dns-query':'https://dns.google/resolve';const response=await fetch(`${endpoint}?name=${new URL(website).hostname}&type=${type}`,{redirect:'manual',headers:{accept:'application/dns-json'}});let data:any=null;try{data=await response.json();}catch{}return {provider,type,httpStatus:response.status,contentType:response.headers.get('content-type'),location:response.headers.get('location'),dnsStatus:data?.Status??null,answers:data?.Answer?.filter((item:any)=>item.type===1||item.type===28).map((item:any)=>({type:item.type,address:item.data}))??null};}catch{return {provider,type,failure:'network_error'};}})));return Response.json({synthetic:true,dns:results});
  }
  if(request.method==='POST'&&path==='/init'){
   const body=await request.json() as {website?:string};if(typeof body.website!=='string'||!/^https:\/\/mayor-audit-site-[a-f0-9]+\.[a-z0-9-]+\.workers\.dev\/$/.test(body.website))return Response.json({error:'unsafe_fixture'},{status:400});
   const id=crypto.randomUUID(),date=new Date().toISOString(),intake={contactName:'Synthetic Test Buyer',email:'synthetic-audit@example.com',businessName:'Cedar Bike Service (synthetic test)',website:body.website,goals:'Help neighborhood commuter riders understand our bicycle repair and seasonal tune-up services, request an appointment, and return for maintenance. Verify request handoffs and define a measurement plan before adding software.',notes:'Our customers use bicycles to commute and run errands. Our workshop offers commuter bicycle repairs, brake adjustments, flat-tire repair, wheel checks and seasonal maintenance, as described on our public pages. Inquiry ownership and follow-up handoffs need verification. Response times, conversion and retention baselines are unknown. No private tools or customer records have been supplied.',acceptedTerms:true};
   await env.AGENT_DB.prepare("INSERT INTO mayor_audit_orders(id,mode,request_id,request_hash,status_token_hash,intake_json,payment_status,fulfillment_status,paid_at,created_at,updated_at) VALUES(?,'test',?,?,?,?,'paid','queued',?,?,?)").bind(id,crypto.randomUUID(),'a'.repeat(64),crypto.randomUUID().replaceAll('-','')+'b'.repeat(32),JSON.stringify(intake),date,date,date).run();return Response.json({orderId:id,synthetic:true});
  }
  const id=new URL(request.url).searchParams.get('order');if(!id||!/^[0-9a-f-]{36}$/.test(id))return Response.json({error:'order_required'},{status:400});
  const calls:unknown[]=[];
  let summary:unknown=null;if(request.method==='POST'&&path==='/run'){
   const binding=env.AI as unknown as {run:AuditInference};summary=await runBusinessAudits({...env,MAYOR_STRIPE_MODE:'test'},{allowTest:true,orderId:id,dependencies:{infer:async(model,input,settings)=>{const started=Date.now();try{const output=await binding.run(model,input,settings);const response=output as {choices?:{finish_reason?:string}[];usage?:unknown;status?:string;request_id?:string;results?:{result?:{choices?:{finish_reason?:string}[];usage?:unknown}}[]};calls.push({...queuedContextMetadata(input),model,elapsedMs:Date.now()-started,operation:input.request_id?'poll':settings?.queueRequest?'queue':'synchronous',providerStatus:response.status??null,jobId:response.request_id??null,finishReason:response.choices?.[0]?.finish_reason??response.results?.[0]?.result?.choices?.[0]?.finish_reason??null,usage:response.usage??response.results?.[0]?.result?.usage??null});return output;}catch(error){const message=error instanceof Error?error.message:'';calls.push({model,elapsedMs:Date.now()-started,failureCategory:/paid|billing|credits/i.test(message)?'paid_access_required':/schema|response_format|validation|parameter/i.test(message)?'input_schema_rejected':/not found|not supported|not enabled|model.*unavailable/i.test(message)?'model_not_available':/429|rate limit/i.test(message)?'provider_rate_limit':'provider_error'});throw error;}}}});
  }else if(request.method!=='GET'||path!=='/status')return Response.json({error:'not_found'},{status:404});
  const row=await env.AGENT_DB.prepare('SELECT analysis_stage,analysis_attempts,analysis_stage_attempts,analysis_review_count,analysis_error_code,analysis_next_attempt_at,analysis_job_id,analysis_job_model,analysis_job_started_at,fulfillment_status,evidence_json,draft_json,report_json,review_json,report_created_at FROM mayor_audit_orders WHERE id=?').bind(id).first<any>();if(!row)return Response.json({error:'missing_order'},{status:404});
  const {evidence_json,draft_json,report_json,review_json,...state}=row;return Response.json({synthetic:true,summary,state,calls,evidence:evidence_json?JSON.parse(evidence_json):null,draft:draft_json?JSON.parse(draft_json):null,report:report_json?JSON.parse(report_json):null,review:review_json?JSON.parse(review_json):null},{headers:{'cache-control':'no-store'}});
 }catch(error){const message=error instanceof Error?error.message:'';return Response.json({error:'probe_failed',stage:path,category:/D1_ERROR|SQLITE|no such table|constraint/i.test(message)?'database_error':/json|parse/i.test(message)?'invalid_json':'runtime_error'},{status:500});}
}} satisfies ExportedHandler<ProbeEnv>;
