import {z} from 'zod';
import type {Actor} from '../env';
import {digest,HttpError,json,readJson} from '../http';
import {requireMembership,BILLING_ROLES} from '../permissions';
import {auditDraftSchema,auditReviewSchema} from '../business-audit-schema';
import {validateAuditRoadmapReferences} from '../business-audit-roadmap';
import {assertMode,baseConfiguration,clientFor,mode,objectId,stripeUrl,type BillingEnv,type StripeClient,type StripeEvent,type StripeObject} from './stripe';

export const AUDIT_DOMAIN='mayor_business_audit';
export const AUDIT_OFFER=Object.freeze({name:'Extensive business audit',priceCents:33000,currency:'USD',payment:'one_time',scope:['Website and customer journey','Services and booking','Customer retention','Local visibility','Daily operations','Priorities and a 30/60/90-day plan'],delivery:'An automatically generated and independently reviewed audit report after intake analysis. Payment queues the audit; it does not mean a report is complete.'});
const webUrl=z.string().trim().max(2048).url().refine(value=>{const url=new URL(value),host=url.hostname.toLowerCase();return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password&&!url.port&&/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host)&&!/(?:^|\.)(localhost|local|internal|test|example|invalid|onion)$/.test(host);},'Use a public website domain without credentials or a custom port.').transform(value=>{const url=new URL(value);url.protocol='https:';url.hash='';return url.href;});
const primaryWebsite=webUrl.refine(value=>!new URL(value).search,'Use the main website address without query parameters.');
export const auditIntakeSchema=z.object({contactName:z.string().trim().min(2).max(120),email:z.email().max(254).transform(value=>value.toLowerCase()),businessName:z.string().trim().min(2).max(160),website:primaryWebsite,goals:z.string().trim().min(10).max(4000),notes:z.string().trim().max(4000).optional(),links:z.array(webUrl).max(10).optional(),acceptedTerms:z.literal(true)}).strict();
type Intake=z.infer<typeof auditIntakeSchema>;
interface AuditOrder {id:string;mode:'test'|'live';request_id:string;request_hash:string;status_token_hash:string;stripe_session_id:string|null;stripe_payment_intent_id:string|null;checkout_url:string|null;expires_at:number|null;provider_started_at:number|null;payment_status:string;fulfillment_status:string;intake_json:string;paid_at:string|null;created_at:string;report_json:string|null;review_json:string|null;report_created_at:string|null;}
function auditStripeConfiguration(env:BillingEnv){const base=baseConfiguration(env);if(!/^price_[A-Za-z0-9]+$/.test(env.MAYOR_STRIPE_AUDIT_PRICE_ID??''))throw new HttpError(503,'audit_not_ready','The audit checkout is being prepared.');return {...base,priceId:env.MAYOR_STRIPE_AUDIT_PRICE_ID!};}
function auditConfiguration(env:BillingEnv){const base=auditStripeConfiguration(env);if((env.MAYOR_AUDIT_STATUS_SECRET?.length??0)<32||base.mode==='live'&&env.MAYOR_AUDIT_FULFILLMENT_READY!=='true')throw new HttpError(503,'audit_not_ready','The audit checkout is being prepared. Please return when it is available.');return base;}
function auditMetadata(id:string){return {mayor_billing_domain:AUDIT_DOMAIN,mayor_audit_order_id:id,mayor_audit_offer:'330-usd-v1'};}
export function auditAllowedOrigins(env:BillingEnv){const defaults=[new URL(env.APP_ORIGIN).origin,'https://mehyar.us','https://www.mehyar.us'];return new Set([...defaults,...(env.MAYOR_AUDIT_ALLOWED_ORIGINS??'').split(',').map(value=>value.trim()).filter(value=>{try{const url=new URL(value);return url.origin===value&&['https:','http:'].includes(url.protocol);}catch{return false;}})]);}
async function tokenFor(env:BillingEnv,id:string){if((env.MAYOR_AUDIT_STATUS_SECRET?.length??0)<32)throw new HttpError(503,'audit_not_ready','The audit checkout is being prepared.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.MAYOR_AUDIT_STATUS_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`mayor-audit-receipt:${id}`))),byte=>byte.toString(16).padStart(2,'0')).join('');}
export function auditOffer(env:BillingEnv){let available=false;try{auditConfiguration(env);available=true;}catch{}const selected=mode(env);return {offer:AUDIT_OFFER,available,mode:selected,message:available?(selected==='test'?'Stripe test checkout. No real charge or audit delivery.':null):'The audit checkout is being prepared. No payment is available yet.'};}
async function publicRate(env:BillingEnv,request:Request,kind:string,max:number){const ip=await digest(request.headers.get('cf-connecting-ip')??'local-anonymous'),bucket=Math.floor(Date.now()/60000);const row=await env.AGENT_DB.prepare(`INSERT INTO mayor_rate_limits(subject,bucket,count) VALUES(?,?,1) ON CONFLICT(subject,bucket) DO UPDATE SET count=count+1 WHERE count<? RETURNING count`).bind(`mayor:audit:${kind}:${ip}`,bucket,max).first();if(!row)throw new HttpError(429,'audit_rate_limited','Please wait a minute and try again.');}
function assertAuditPrice(price:StripeObject,env:BillingEnv){const config=auditStripeConfiguration(env);assertMode(price,config.mode);if(price.id!==config.priceId||!price.active||price.type!=='one_time'||price.recurring!=null||price.currency!=='usd'||price.unit_amount!==33000||price.billing_scheme!=='per_unit'||price.tax_behavior==='inclusive')throw new HttpError(409,'audit_price_mismatch','The audit price could not be verified.');}
export async function createAuditCheckout(env:BillingEnv,intake:Intake,requestId:string,injected?:StripeClient){
 const config=auditConfiguration(env),client=clientFor(env,injected),hash=await digest(JSON.stringify(intake));
 if(env.MAYOR_STRIPE_ACCOUNT_ID){const account=await client.request('/v1/account');if(account.id!==env.MAYOR_STRIPE_ACCOUNT_ID)throw new HttpError(409,'billing_account_mismatch','The billing account could not be verified.');}
 let order=await env.AGENT_DB.prepare('SELECT * FROM mayor_audit_orders WHERE mode=? AND request_id=?').bind(config.mode,requestId).first<AuditOrder>();if(order&&order.request_hash!==hash)throw new HttpError(409,'audit_request_conflict','This request has different intake details. Retry the original request or start a new one.');
 if(!order){const id=crypto.randomUUID(),token=await tokenFor(env,id),created=new Date().toISOString();await env.AGENT_DB.prepare('INSERT INTO mayor_audit_orders(id,mode,request_id,request_hash,status_token_hash,intake_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(mode,request_id) DO NOTHING').bind(id,config.mode,requestId,hash,await digest(token),JSON.stringify(intake),created,created).run();order=await env.AGENT_DB.prepare('SELECT * FROM mayor_audit_orders WHERE mode=? AND request_id=?').bind(config.mode,requestId).first<AuditOrder>();}
 if(!order||order.request_hash!==hash)throw new HttpError(409,'audit_request_conflict','The audit request could not be matched.');const statusToken=await tokenFor(env,order.id);if(await digest(statusToken)!==order.status_token_hash)throw new HttpError(409,'audit_receipt_needs_review','This checkout receipt needs review before it can be retried. Keep your original receipt.');
 if(order.checkout_url&&order.payment_status==='pending'&&(order.expires_at??0)>Date.now()/1000)return {url:stripeUrl(order.checkout_url,'checkout.stripe.com'),statusToken,orderId:order.id,replay:true};
 if(order.payment_status!=='pending')throw new HttpError(409,'audit_checkout_resolved','This checkout has ended. Review its receipt before starting another purchase.');if(order.provider_started_at&&Date.now()-order.provider_started_at>23*3600000)throw new HttpError(409,'audit_checkout_needs_review','This checkout needs review before retrying.');
 assertAuditPrice(await client.request(`/v1/prices/${config.priceId}`),env);await env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET provider_started_at=COALESCE(provider_started_at,?),updated_at=? WHERE id=?').bind(Date.now(),new Date().toISOString(),order.id).run();const origin=new URL(env.APP_ORIGIN).origin;
 const session=await client.request('/v1/checkout/sessions','POST',{mode:'payment',customer_creation:'always',customer_email:intake.email,line_items:[{price:config.priceId,quantity:1}],allowed_payment_method_types:['card'],metadata:auditMetadata(order.id),payment_intent_data:{metadata:auditMetadata(order.id)},success_url:`${origin}/business-audit?receipt=${statusToken}&payment=return`,cancel_url:`${origin}/business-audit?receipt=${statusToken}&payment=canceled`,client_reference_id:order.id,custom_text:{submit:{message:'One-time $330 business audit. Payment queues your intake for an automatically generated and reviewed report; it does not deliver an instant audit. Analysis uses your supplied details and public sources, without private-account access.'}}},`mayor-pwa:audit:${config.mode}:${order.id}`);
 assertMode(session,config.mode);if(!/^cs_(test_|live_)?[A-Za-z0-9]+$/.test(session.id??'')||session.mode!=='payment'||session.metadata?.mayor_billing_domain!==AUDIT_DOMAIN||session.metadata?.mayor_audit_order_id!==order.id||!Number.isSafeInteger(session.expires_at))throw new HttpError(502,'audit_checkout_invalid','The audit checkout could not be verified.');const url=stripeUrl(session.url,'checkout.stripe.com');await env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET stripe_session_id=?,checkout_url=?,expires_at=?,updated_at=? WHERE id=? AND payment_status=\'pending\'').bind(session.id,url,session.expires_at,new Date().toISOString(),order.id).run();return {url,statusToken,orderId:order.id,replay:false};
}
export async function findAuditReceiptOrder(env:BillingEnv,token:string){
 if(!/^[a-f0-9]{64}$/.test(token))throw new HttpError(404,'audit_receipt_unavailable','This audit receipt is unavailable.');const order=await env.AGENT_DB.prepare('SELECT * FROM mayor_audit_orders WHERE status_token_hash=?').bind(await digest(token)).first<AuditOrder>();if(!order||order.mode!==mode(env))throw new HttpError(404,'audit_receipt_unavailable','This audit receipt is unavailable.');return order;
}
// Read completed records structurally. Do not re-run evolving analysis heuristics
// against historical reports or promote an internal draft into a deliverable.
const reportSourceSchema=z.object({id:z.string().regex(/^S[1-8]$/),url:z.url(),title:z.string(),checkedAt:z.iso.datetime(),contentHash:z.string().regex(/^[a-f0-9]{64}$/),excerpt:z.string(),providedBy:z.enum(['website','owner_link']),observations:z.object({titlePresent:z.boolean(),descriptionPresent:z.boolean(),viewportPresent:z.boolean(),h1Count:z.number().int().nonnegative(),imageCount:z.number().int().nonnegative(),imagesMissingAlt:z.number().int().nonnegative(),formCount:z.number().int().nonnegative(),bookingLinkCount:z.number().int().nonnegative(),contactLinkCount:z.number().int().nonnegative()}).strict()}).strict();
const completedReportSchema=auditDraftSchema.extend({schemaVersion:z.literal(1),orderId:z.uuid(),businessName:z.string().min(2).max(160),website:z.url(),generatedAt:z.iso.datetime(),analysisModel:z.string().min(1),reviewModel:z.string().min(1),scope:z.object({method:z.string().min(1),limitations:z.array(z.string()),pagesChecked:z.number().int().min(1).max(8)}).strict(),sources:z.array(reportSourceSchema).min(1).max(8)}).strict();
const completedReviewSchema=auditReviewSchema.extend({model:z.string().min(1),reviewedAt:z.iso.datetime()}).strict();
function approvedReport(order:AuditOrder){
 if(order.payment_status!=='paid'||order.fulfillment_status!=='report_ready'||!order.report_json||!order.review_json||!order.report_created_at||!z.iso.datetime().safeParse(order.report_created_at).success)return null;
 try{
  const report:unknown=JSON.parse(order.report_json),review:unknown=JSON.parse(order.review_json),parsed=completedReportSchema.safeParse(report),checked=completedReviewSchema.safeParse(review);
  if(!parsed.success||!checked.success)return null;
  const value=parsed.data,approval=checked.data;
  if(value.orderId!==order.id||approval.model!==value.reviewModel||!approval.approved||Object.values(approval.verification).some(flag=>flag!==true)||approval.issues.some(issue=>issue.severity==='major'||issue.severity==='critical'))return null;
  const sourceIds=new Set(value.sources.map(source=>source.id)),findingIds=new Set(value.findings.map(finding=>finding.id));
  if(sourceIds.size!==value.sources.length||findingIds.size!==value.findings.length||new Set(value.findings.map(finding=>finding.category)).size!==6||approval.issues.some(issue=>issue.findingId!==null&&!findingIds.has(issue.findingId))||value.scope.pagesChecked!==value.sources.length||new Set(value.roadmap.map(phase=>phase.window)).size!==3||value.findings.some(finding=>finding.citations.some(citation=>!sourceIds.has(citation.sourceId)))||!validateAuditRoadmapReferences(value.roadmap,findingIds,{allowUnmappedLegacy:true}).valid)return null;
  // Return the original stored envelope; validation must not rewrite exports.
  return {report:report as typeof value,review:review as typeof approval};
 }catch{return null;}
}
export async function auditReceipt(env:BillingEnv,token:string){const order=await findAuditReceiptOrder(env,token);return {orderId:order.id,mode:order.mode,paymentStatus:order.payment_status,fulfillmentStatus:order.fulfillment_status,priceCents:33000,currency:'USD',paidAt:order.paid_at,reportAvailable:Boolean(approvedReport(order))};}
export async function auditReport(env:BillingEnv,token:string){const order=await findAuditReceiptOrder(env,token),completed=approvedReport(order);if(!completed)throw new HttpError(409,'audit_report_not_ready','The reviewed audit report is not ready yet.');return {orderId:order.id,...completed,createdAt:order.report_created_at};}
export async function auditOrders(env:BillingEnv,actor:Actor){await requireMembership(env,actor,BILLING_ROLES);if(!(env.MAYOR_AUDIT_OPERATOR_USER_IDS??'').split(',').map(value=>value.trim()).includes(actor.userId))throw new HttpError(403,'audit_operator_required','Your account does not manage audit fulfillment.');const orders=await env.AGENT_DB.prepare('SELECT id,payment_status,fulfillment_status,intake_json,paid_at,created_at FROM mayor_audit_orders WHERE mode=? ORDER BY created_at DESC LIMIT 100').bind(mode(env)??'disabled').all<Pick<AuditOrder,'id'|'payment_status'|'fulfillment_status'|'intake_json'|'paid_at'|'created_at'>>();return {orders:orders.results.map(order=>({orderId:order.id,paymentStatus:order.payment_status,fulfillmentStatus:order.fulfillment_status,intake:JSON.parse(order.intake_json),paidAt:order.paid_at,createdAt:order.created_at}))};}
export async function processAuditEvent(env:BillingEnv,event:StripeEvent,injected?:StripeClient){
 const config=baseConfiguration(env),object=event.data.object;if(event.livemode!==(config.mode==='live'))throw new HttpError(400,'stripe_mode_mismatch','Billing event environment mismatch.');if(event.account&&event.account!==env.MAYOR_STRIPE_ACCOUNT_ID)return {received:true,outcome:'unrelated_account'};
 let orderId=object.metadata?.mayor_billing_domain===AUDIT_DOMAIN?object.metadata.mayor_audit_order_id:undefined,disputedCharge:StripeObject|undefined;if(event.type==='charge.dispute.created'){const chargeId=objectId(object.charge);if(!chargeId||!/^ch_[A-Za-z0-9]+$/.test(chargeId))throw new HttpError(409,'billing_charge_missing','The payment adjustment needs review.');disputedCharge=await clientFor(env,injected).request(`/v1/charges/${chargeId}`);assertMode(disputedCharge,config.mode);}
 const adjustmentIntent=objectId(disputedCharge?.payment_intent)??objectId(object.payment_intent);if(!orderId&&adjustmentIntent){const linked=await env.AGENT_DB.prepare('SELECT id FROM mayor_audit_orders WHERE mode=? AND stripe_payment_intent_id=?').bind(config.mode,adjustmentIntent).first<{id:string}>();orderId=linked?.id;if(!orderId&&(event.type==='charge.refunded'||event.type==='charge.dispute.created')){const intent=await clientFor(env,injected).request(`/v1/payment_intents/${adjustmentIntent}`);assertMode(intent,config.mode);if(intent.metadata?.mayor_billing_domain===AUDIT_DOMAIN)orderId=intent.metadata.mayor_audit_order_id;}}
 if(!orderId)return null;const order=await env.AGENT_DB.prepare('SELECT * FROM mayor_audit_orders WHERE id=? AND mode=?').bind(orderId,config.mode).first<AuditOrder>();if(!order?.stripe_session_id)throw new HttpError(409,'audit_checkout_unmapped','The audit payment is waiting for its checkout record.');
 const hash=await digest(JSON.stringify(event)),now=Date.now(),token=crypto.randomUUID();await env.AGENT_DB.prepare("INSERT INTO mayor_billing_events(mode,event_id,payload_hash,status,event_type,received_at) VALUES(?,?,?,'pending',?,?) ON CONFLICT(mode,event_id) DO NOTHING").bind(config.mode,event.id,hash,event.type,new Date(now).toISOString()).run();const stored=await env.AGENT_DB.prepare('SELECT payload_hash,status FROM mayor_billing_events WHERE mode=? AND event_id=?').bind(config.mode,event.id).first<{payload_hash:string;status:string}>();if(stored?.payload_hash!==hash)throw new HttpError(409,'billing_event_conflict','The billing event needs review.');if(stored.status==='processed')return {received:true,outcome:'duplicate'};
 const claimed=await env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='processing',processing_token=?,lease_expires_at=? WHERE mode=? AND event_id=? AND (status IN ('pending','failed') OR (status='processing' AND lease_expires_at<=?))").bind(token,now+120000,config.mode,event.id,now).run();if(!claimed.meta.changes)throw new HttpError(503,'billing_event_busy','The audit payment is being checked.');
 try{
  const lease=await env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET processing_token=?,lease_expires_at=? WHERE id=? AND (processing_token IS NULL OR lease_expires_at<=?)').bind(token,now+120000,order.id,now).run();if(!lease.meta.changes)throw new HttpError(503,'billing_busy','The audit payment is being checked.');const client=clientFor(env,injected),session=await client.request(`/v1/checkout/sessions/${order.stripe_session_id}?expand[]=line_items.data.price&expand[]=payment_intent`);assertMode(session,config.mode);
  if(session.id!==order.stripe_session_id||session.metadata?.mayor_billing_domain!==AUDIT_DOMAIN||session.metadata?.mayor_audit_order_id!==order.id||session.client_reference_id!==order.id||session.mode!=='payment')throw new HttpError(409,'audit_payment_mismatch','The audit payment could not be matched.');let effects:D1PreparedStatement[]=[];
  if(session.status==='complete'&&session.payment_status==='paid'){
   const lines:StripeObject[]=session.line_items?.data??[],line=lines[0];if(session.currency!=='usd'||session.amount_subtotal!==33000||session.amount_total<33000||session.line_items?.has_more||lines.length!==1||line.quantity!==1||objectId(line.price)!==env.MAYOR_STRIPE_AUDIT_PRICE_ID)throw new HttpError(409,'audit_payment_contract_mismatch','The payment does not match the $330 audit.');assertAuditPrice(typeof line.price==='object'?line.price:await client.request(`/v1/prices/${env.MAYOR_STRIPE_AUDIT_PRICE_ID}`),env);
   const intent=typeof session.payment_intent==='object'?session.payment_intent:await client.request(`/v1/payment_intents/${objectId(session.payment_intent)}`);assertMode(intent,config.mode);const customerId=objectId(session.customer);if(!/^pi_[A-Za-z0-9]+$/.test(intent.id??'')||!customerId||!/^cus_[A-Za-z0-9]+$/.test(customerId)||intent.status!=='succeeded'||intent.currency!=='usd'||intent.amount_received<session.amount_total||objectId(intent.customer)!==customerId||intent.metadata?.mayor_billing_domain!==AUDIT_DOMAIN||intent.metadata?.mayor_audit_order_id!==order.id)throw new HttpError(409,'audit_payment_unverified','The audit payment is not verified yet.');
   const chargeId=objectId(intent.latest_charge);if(!/^ch_[A-Za-z0-9]+$/.test(chargeId??''))throw new HttpError(409,'audit_payment_unverified','The audit payment charge is not verified yet.');const charge=await client.request(`/v1/charges/${chargeId}`);assertMode(charge,config.mode);if(charge.paid!==true||charge.captured!==true||charge.currency!=='usd'||charge.amount!==session.amount_total||objectId(charge.payment_intent)!==intent.id||objectId(charge.customer)!==customerId)throw new HttpError(409,'audit_payment_unverified','The audit payment charge is not verified yet.');
   effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET payment_status='paid',fulfillment_status=CASE WHEN fulfillment_status='awaiting_payment' THEN 'queued' ELSE fulfillment_status END,stripe_payment_intent_id=?,stripe_customer_id=?,paid_at=COALESCE(paid_at,?),updated_at=? WHERE id=? AND payment_status!='refunded'").bind(intent.id,objectId(session.customer)??null,new Date().toISOString(),new Date().toISOString(),order.id));
   if(charge.refunded===true||charge.amount_refunded>0)effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET payment_status='refunded',fulfillment_status='needs_review',analysis_token=NULL,analysis_lease_expires_at=NULL,analysis_error_code='payment_refunded',updated_at=? WHERE id=?").bind(new Date().toISOString(),order.id));
   else if(charge.disputed===true)effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET fulfillment_status='needs_review',analysis_token=NULL,analysis_lease_expires_at=NULL,analysis_error_code='payment_disputed',updated_at=? WHERE id=?").bind(new Date().toISOString(),order.id));
  }else if(session.status==='expired')effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET payment_status='expired',updated_at=? WHERE id=? AND payment_status='pending'").bind(new Date().toISOString(),order.id));
  else if(event.type==='checkout.session.async_payment_failed')effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET payment_status='failed',updated_at=? WHERE id=? AND payment_status='pending'").bind(new Date().toISOString(),order.id));
  const canonicalIntentId=objectId(session.payment_intent);
  if(event.type==='charge.refunded'){const charge=await client.request(`/v1/charges/${object.id}`);assertMode(charge,config.mode);if(objectId(charge.payment_intent)!==canonicalIntentId||objectId(charge.customer)!==objectId(session.customer))throw new HttpError(409,'audit_payment_mismatch','The refund owner could not be verified.');if(charge.refunded===true||charge.amount_refunded>0)effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET payment_status='refunded',fulfillment_status='needs_review',analysis_token=NULL,analysis_lease_expires_at=NULL,analysis_error_code='payment_refunded',updated_at=? WHERE id=?").bind(new Date().toISOString(),order.id));}
  if(disputedCharge){if(objectId(disputedCharge.payment_intent)!==canonicalIntentId||objectId(disputedCharge.customer)!==objectId(session.customer))throw new HttpError(409,'audit_payment_mismatch','The dispute owner could not be verified.');effects.push(env.AGENT_DB.prepare("UPDATE mayor_audit_orders SET fulfillment_status='needs_review',analysis_token=NULL,analysis_lease_expires_at=NULL,analysis_error_code='payment_disputed',updated_at=? WHERE id=?").bind(new Date().toISOString(),order.id));}
  const fence=env.AGENT_DB.prepare('INSERT INTO mayor_billing_fences(token,verified_token) VALUES(?,(SELECT o.processing_token FROM mayor_audit_orders o JOIN mayor_billing_events e ON e.mode=o.mode WHERE o.id=? AND e.event_id=? AND o.processing_token=? AND e.processing_token=? AND o.lease_expires_at>? AND e.lease_expires_at>?))').bind(token,order.id,event.id,token,token,Date.now(),Date.now());await env.AGENT_DB.batch([fence,...effects,env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET processing_token=NULL,lease_expires_at=NULL WHERE id=? AND processing_token=?').bind(order.id,token),env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='processed',processing_token=NULL,lease_expires_at=NULL WHERE mode=? AND event_id=? AND processing_token=?").bind(config.mode,event.id,token),env.AGENT_DB.prepare('DELETE FROM mayor_billing_fences WHERE token=?').bind(token)]);return {received:true,outcome:'processed'};
 }catch(error){await env.AGENT_DB.batch([env.AGENT_DB.prepare('UPDATE mayor_audit_orders SET processing_token=NULL,lease_expires_at=NULL WHERE id=? AND processing_token=?').bind(order.id,token),env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='failed',processing_token=NULL,lease_expires_at=NULL,error_code=? WHERE mode=? AND event_id=? AND processing_token=?").bind(error instanceof HttpError?error.code:'audit_processing_failed',config.mode,event.id,token)]);throw error;}
}
export async function handleAuditPublic(request:Request,env:BillingEnv,injected?:StripeClient):Promise<Response|null>{
 const path=new URL(request.url).pathname;if(!['/api/business-audit/offer','/api/business-audit/checkout','/api/business-audit/status','/api/business-audit/report'].includes(path))return null;const origin=request.headers.get('origin'),allowed=origin&&auditAllowedOrigins(env).has(origin);const decorate=(response:Response)=>{if(allowed){response.headers.set('access-control-allow-origin',origin);response.headers.set('vary','Origin');response.headers.set('access-control-allow-methods','GET,POST,OPTIONS');response.headers.set('access-control-allow-headers','Content-Type,Idempotency-Key,X-Idempotency-Key,Authorization');}return response;};
 try{if(request.method==='OPTIONS'){if(!allowed)throw new HttpError(403,'invalid_origin','Open the official audit page to continue.');return decorate(new Response(null,{status:204}));}if(path.endsWith('/offer')&&request.method==='GET')return decorate(json(auditOffer(env)));if((path.endsWith('/status')||path.endsWith('/report'))&&request.method==='GET'){await publicRate(env,request,'status',60);const token=(request.headers.get('authorization')??'').replace(/^Bearer /,'');return decorate(json(path.endsWith('/report')?await auditReport(env,token):await auditReceipt(env,token)));}
  if(path.endsWith('/checkout')&&request.method==='POST'){if(!allowed)throw new HttpError(403,'invalid_origin','Open the official audit page to continue.');await publicRate(env,request,'checkout',6);const key=request.headers.get('idempotency-key')??request.headers.get('x-idempotency-key');if(!key||!z.uuid().safeParse(key).success)throw new HttpError(400,'idempotency_key_required','Retry with the same unique checkout request.');const intake=auditIntakeSchema.parse(await readJson(request,131072));return decorate(json(await createAuditCheckout(env,intake,key,injected)));}throw new HttpError(405,'method_not_allowed','This audit action is unavailable.');
 }catch(error){return decorate(error instanceof HttpError?json({error:error.code,message:error.message},error.status):error instanceof z.ZodError?json({error:'invalid_intake',message:'Review the contact details, business website, goals, and terms before continuing.'},400):json({error:'audit_request_failed',message:'The audit request could not be completed. Retry the same request.'},500));}
}
