import type {Actor} from '../env';
import {digest,HttpError} from '../http';
import {BILLING_ROLES,requireMembership} from '../permissions';
import {CREDIT_PACK_DOMAIN,CREDIT_PACK_VERSION,CREDIT_PACKS,freePeriod,type CreditPackId} from './plans';
import {ACTIVE_PERIOD_SQL,billingUsageContext} from './state';
import {assertAccount,ensureCustomer} from './service';
import {acquireLease,commitLease,releaseLease} from './locking';
import {assertMode,baseConfiguration,clientFor,mode,objectId,stripeUrl,type BillingEnv,type StripeClient,type StripeEvent,type StripeObject} from './stripe';

interface CreditCheckout {id:string;tenant_id:string;mode:'test'|'live';request_id:string;pack_id:CreditPackId;catalog_version:string;price_id:string;period_key:string;period_start:number;period_end:number;status:string;stripe_session_id:string|null;stripe_payment_intent_id:string|null;checkout_url:string|null;expires_at:number|null;provider_started_at:number|null;created_at:string;}
export function creditPriceId(env:BillingEnv,packId:CreditPackId){return {small:env.MAYOR_STRIPE_CREDIT_PRICE_SMALL,medium:env.MAYOR_STRIPE_CREDIT_PRICE_MEDIUM,large:env.MAYOR_STRIPE_CREDIT_PRICE_LARGE}[packId];}
function packFor(id:CreditPackId){const pack=CREDIT_PACKS.find(pack=>pack.id===id);if(!pack)throw new HttpError(400,'credit_pack_invalid','Choose an available credit pack.');return pack;}
export function creditConfiguration(env:BillingEnv,packId:CreditPackId){const config=baseConfiguration(env),priceId=creditPriceId(env,packId);if(!/^price_[A-Za-z0-9]+$/.test(priceId??''))throw new HttpError(503,'credit_packs_not_ready','Credit packs are being prepared.');return {...config,priceId:priceId!};}
function assertCreditPrice(price:StripeObject,env:BillingEnv,packId:CreditPackId){const config=creditConfiguration(env,packId),pack=packFor(packId);assertMode(price,config.mode);if(price.id!==config.priceId||price.active!==true||price.unit_amount!==pack.priceCents||price.currency!=='usd'||price.type!=='one_time'||price.recurring!=null||price.billing_scheme!=='per_unit'||price.tax_behavior==='inclusive'||price.metadata?.mayor_credit_pack!==packId||price.metadata?.mayor_credit_version!==CREDIT_PACK_VERSION)throw new HttpError(409,'credit_price_mismatch','The credit pack price could not be verified.');}
function creditMetadata(row:CreditCheckout){return {mayor_billing_domain:CREDIT_PACK_DOMAIN,mayor_credit_version:row.catalog_version,mayor_tenant_id:row.tenant_id,mayor_credit_checkout_id:row.id,mayor_credit_pack:row.pack_id,mayor_period_key:row.period_key,mayor_period_start:String(row.period_start),mayor_period_end:String(row.period_end),mayor_credit_price_id:row.price_id};}
function assertCreditMetadata(object:StripeObject,row:CreditCheckout){const expected=creditMetadata(row);for(const [name,value] of Object.entries(expected))if(object.metadata?.[name]!==value)throw new HttpError(409,'credit_ownership_mismatch','Credit pack payment ownership could not be verified.');}
function periodGuard(row:CreditCheckout,seconds:number){const active=`EXISTS(SELECT 1 FROM mayor_billing_paid_periods p JOIN mayor_billing_subscriptions s ON s.tenant_id=p.tenant_id AND s.mode=p.mode AND s.stripe_subscription_id=p.stripe_subscription_id WHERE p.tenant_id=? AND p.mode=? AND p.invalidated=0 AND p.period_start<=? AND p.period_end>?${row.period_key.startsWith('pro:')?' AND p.period_key=?':''})`;return {sql:row.period_key.startsWith('pro:')?active:`NOT ${active}`,bindings:[row.tenant_id,row.mode,seconds,seconds,...(row.period_key.startsWith('pro:')?[row.period_key]:[])]};}
async function retireObsoleteQuotes(env:BillingEnv,actor:Actor,selected:'test'|'live',seconds:number){
 seconds=Math.max(seconds,Math.floor(Date.now()/1000));
 const active=`EXISTS(SELECT 1 FROM mayor_billing_paid_periods p JOIN mayor_billing_subscriptions s ON s.tenant_id=p.tenant_id AND s.mode=p.mode AND s.stripe_subscription_id=p.stripe_subscription_id WHERE p.tenant_id=c.tenant_id AND p.mode=c.mode AND p.invalidated=0 AND p.period_start<=? AND p.period_end>?)`;
 const same=active.replace('p.period_end>?)','p.period_end>? AND p.period_key=c.period_key)');
 // Compare every quote against current DB state, never a context read before an awaited transition.
 await env.AGENT_DB.prepare(`UPDATE mayor_billing_credit_checkouts AS c SET status='expired',updated_at=? WHERE tenant_id=? AND mode=? AND status IN ('pending','open') AND period_start<=? AND (period_end<=? OR (period_key LIKE 'free:%' AND ${active}) OR (period_key LIKE 'pro:%' AND NOT ${same}))`).bind(new Date(seconds*1000).toISOString(),actor.tenantId,selected,seconds,seconds,seconds,seconds,seconds,seconds).run();
}
async function currentCheckoutUrl(env:BillingEnv,actor:Actor,row:CreditCheckout,sessionId?:string){
 const seconds=Math.floor(Date.now()/1000),guard=periodGuard(row,seconds),stored=await env.AGENT_DB.prepare(`SELECT checkout_url FROM mayor_billing_credit_checkouts WHERE id=? AND status='open' AND period_start<=? AND period_end>? AND expires_at>?${sessionId?' AND stripe_session_id=?':''} AND ${guard.sql} AND EXISTS(SELECT 1 FROM agent_memberships m JOIN agent_tenants t ON t.id=m.tenant_id AND t.status='active' WHERE m.tenant_id=? AND m.user_id=? AND m.role IN ('owner','billing') AND m.status='active' AND (m.expires_at IS NULL OR m.expires_at>?))`).bind(row.id,seconds,seconds,seconds,...(sessionId?[sessionId]:[]),...guard.bindings,actor.tenantId,actor.userId,new Date(Date.now()).toISOString()).first<{checkout_url:string}>();if(!stored?.checkout_url)throw new HttpError(409,'credit_quote_changed','Your checkout quote changed. Refresh your allowance.');return stripeUrl(stored.checkout_url,'checkout.stripe.com');
}
export async function creditStatus(env:BillingEnv,actor:Actor,canManage:boolean,now=Date.now()){
 const context=await billingUsageContext(env,actor,now),selected=mode(env),seconds=Math.floor(now/1000);
 // Retire obsolete local quotes without creating any provider write or a new charge.
 if(selected)await retireObsoleteQuotes(env,actor,selected,seconds);
 const grants=selected?await env.AGENT_DB.prepare('SELECT COALESCE(SUM(reply_attempts),0) AS replies,COALESCE(SUM(voice_minutes),0) AS minutes FROM mayor_billing_credit_grants WHERE tenant_id=? AND mode=? AND period_key=? AND invalidated=0 AND period_start<=? AND period_end>?').bind(actor.tenantId,selected,context.periodKey,seconds,seconds).first<{replies:number;minutes:number}>():null;
 const pending=selected?await env.AGENT_DB.prepare("SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND status IN ('pending','open') AND (expires_at IS NULL OR expires_at>?)").bind(actor.tenantId,selected,seconds).first<CreditCheckout>():null;
 const rows=selected?await env.AGENT_DB.prepare('SELECT c.id,c.pack_id,c.status,c.period_end,g.paid_at FROM mayor_billing_credit_checkouts c LEFT JOIN mayor_billing_credit_grants g ON g.checkout_id=c.id WHERE c.tenant_id=? AND c.mode=? AND c.period_key=? ORDER BY c.created_at DESC LIMIT 30').bind(actor.tenantId,selected,context.periodKey).all<{id:string;pack_id:string;status:string;period_end:number;paid_at:string|null}>():null;
 const available=CREDIT_PACKS.map(pack=>{let ready=false;try{creditConfiguration(env,pack.id);ready=context.periodEnd-seconds>=1800;}catch{}return {...pack,available:ready};});
 return {creditPacks:available,credits:{periodKey:context.periodKey,periodStart:new Date(context.periodStart*1000).toISOString(),expiresAt:new Date(context.periodEnd*1000).toISOString(),replyAttempts:grants?.replies??0,voiceMinutes:grants?.minutes??0,purchases:(rows?.results??[]).map(row=>({id:row.id,packId:row.pack_id,status:row.status,paidAt:row.paid_at,expiresAt:new Date(row.period_end*1000).toISOString()})),checkout:{pending:Boolean(pending),...(pending&&canManage?{requestId:pending.request_id,packId:pending.pack_id,periodKey:pending.period_key,...(pending.checkout_url?{url:stripeUrl(pending.checkout_url,'checkout.stripe.com')}:{})}:{})},note:'One-time credits are shared by this business, expire with the purchased billing period, and do not transfer when plans change. No rollover or automatic purchase. Refunds or disputes revoke the pack allowance; consumed usage stays counted.'},ready:available.some(pack=>pack.available)};
}
export async function createCreditCheckout(env:BillingEnv,actor:Actor,requestId:string,packId:CreditPackId,periodKey:string,injected?:StripeClient){
 await requireMembership(env,actor,BILLING_ROLES);const config=creditConfiguration(env,packId),client=clientFor(env,injected),pack=packFor(packId);await assertAccount(env,client);
 let row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND request_id=?').bind(actor.tenantId,config.mode,requestId).first<CreditCheckout>();
 if(row&&(row.pack_id!==packId||row.period_key!==periodKey))throw new HttpError(409,'credit_request_changed','Retry the original credit pack request, or start a new purchase.');
 if(row&&!['pending','open'].includes(row.status))throw new HttpError(409,'credit_checkout_resolved','This credit pack checkout has ended. Check your balance before buying again.');
 const current=await billingUsageContext(env,actor),seconds=Math.floor(Date.now()/1000);
 await retireObsoleteQuotes(env,actor,config.mode,seconds);
 if(periodKey!==current.periodKey||row&&row.period_end!==current.periodEnd)throw new HttpError(409,'credit_period_changed','Your billing period changed. Refresh the allowance before purchasing credits.');
 if(current.periodEnd-seconds<1800)throw new HttpError(409,'credit_period_ending','This period ends soon. Purchase credits in the next billing period.');
 if(row?.checkout_url&&row.status==='open'&&(row.expires_at??0)>seconds){
  return {url:await currentCheckoutUrl(env,actor,row),requestId,replay:true};
 }
 if(!row){
  const pending=await env.AGENT_DB.prepare("SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND status IN ('pending','open')").bind(actor.tenantId,config.mode).first<CreditCheckout>();
  if(pending?.stripe_session_id){const effects=await creditSessionEffects(env,pending,client);const lease=await acquireLease(env,actor.tenantId,config.mode);try{await commitLease(env,actor.tenantId,config.mode,lease,effects);}catch(error){await releaseLease(env,actor.tenantId,config.mode,lease);throw error;}const unresolved=await env.AGENT_DB.prepare("SELECT id FROM mayor_billing_credit_checkouts WHERE id=? AND status IN ('pending','open')").bind(pending.id).first();if(unresolved)throw new HttpError(409,'credit_checkout_pending','Resume the original credit pack checkout before buying again.');}
  else if(pending)throw new HttpError(409,'credit_checkout_pending','Retry the original credit pack request.');
  const id=crypto.randomUUID(),created=new Date(Date.now()).toISOString();try{await env.AGENT_DB.prepare("INSERT INTO mayor_billing_credit_checkouts(id,tenant_id,mode,request_id,pack_id,catalog_version,price_id,period_key,period_start,period_end,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'pending',?,?)").bind(id,actor.tenantId,config.mode,requestId,packId,CREDIT_PACK_VERSION,config.priceId,current.periodKey,current.periodStart,current.periodEnd,created,created).run();}catch{const same=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND request_id=?').bind(actor.tenantId,config.mode,requestId).first<CreditCheckout>();if(!same)throw new HttpError(409,'credit_checkout_pending','Retry the original credit pack request.');if(same.pack_id!==packId||same.period_key!==periodKey)throw new HttpError(409,'credit_request_changed','Retry the original credit pack request.');}
  row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND request_id=?').bind(actor.tenantId,config.mode,requestId).first<CreditCheckout>();
 }
 if(!row)throw new HttpError(503,'credit_checkout_unavailable','Credit checkout is temporarily unavailable.');
 if(row.provider_started_at&&Date.now()-row.provider_started_at>23*3600000)throw new HttpError(409,'credit_checkout_needs_review','This credit purchase needs a billing status check before retry.');
 if(row.price_id!==config.priceId||row.catalog_version!==CREDIT_PACK_VERSION)throw new HttpError(409,'credit_quote_changed','The original credit pack price needs review.');
 assertCreditPrice(await client.request(`/v1/prices/${row.price_id}`),env,packId);const customer=await ensureCustomer(env,actor,client),origin=new URL(env.APP_ORIGIN).origin;
 await env.AGENT_DB.prepare('UPDATE mayor_billing_credit_checkouts SET provider_started_at=COALESCE(provider_started_at,?),updated_at=? WHERE id=?').bind(Date.now(),new Date().toISOString(),row.id).run();
 const expiry=Math.min(Math.floor(Date.parse(row.created_at)/1000)+86400,row.period_end);
 await env.AGENT_DB.prepare('UPDATE mayor_billing_credit_checkouts SET expires_at=COALESCE(expires_at,?) WHERE id=?').bind(expiry,row.id).run();
 const quoted=await env.AGENT_DB.prepare('SELECT expires_at FROM mayor_billing_credit_checkouts WHERE id=?').bind(row.id).first<{expires_at:number}>();
 await requireMembership(env,actor,BILLING_ROLES);
 const beforeSubmit=await billingUsageContext(env,actor);if(beforeSubmit.periodKey!==row.period_key||beforeSubmit.periodEnd!==row.period_end)throw new HttpError(409,'credit_period_changed','Your billing period changed. Refresh before purchasing credits.');
 if(!row.provider_started_at&&quoted!.expires_at-Math.floor(Date.now()/1000)<1800)throw new HttpError(409,'credit_period_ending','This checkout quote ends soon. Refresh billing before a new purchase.');
 const metadata=creditMetadata(row),expires=quoted!.expires_at,session=await client.request('/v1/checkout/sessions','POST',{mode:'payment',customer,line_items:[{price:row.price_id,quantity:1}],allowed_payment_method_types:['card'],metadata,payment_intent_data:{metadata},expires_at:expires,client_reference_id:row.id,success_url:`${origin}/?billing=credits&business=${actor.tenantId}`,cancel_url:`${origin}/?billing=credits-canceled&business=${actor.tenantId}`,custom_text:{submit:{message:`${pack.name} credits: ${pack.replyAttempts} reply attempts and ${pack.voiceMinutes} reserved microphone minutes, shared by this business. Expire ${new Date(row.period_end*1000).toISOString()}. No rollover, plan transfer, subscription or automatic purchase.`}}},`mayor-pwa:credits:${config.mode}:${row.id}`);
 assertMode(session,config.mode);assertCreditMetadata(session,row);if(!/^cs_(test_|live_)?[A-Za-z0-9]+$/.test(session.id??'')||objectId(session.customer)!==customer||session.mode!=='payment'||session.client_reference_id!==row.id||!Number.isSafeInteger(session.expires_at)||session.expires_at>row.period_end)throw new HttpError(502,'credit_checkout_invalid','Credit checkout could not be verified.');const url=stripeUrl(session.url,'checkout.stripe.com');
 // Preserve the owned provider receipt even if authorization or plan changed during the POST.
 // Mapping a receipt does not reopen a retired quote or expose its payable URL.
 await env.AGENT_DB.prepare('UPDATE mayor_billing_credit_checkouts SET stripe_session_id=?,expires_at=?,updated_at=? WHERE id=? AND (stripe_session_id IS NULL OR stripe_session_id=?)').bind(session.id,session.expires_at,new Date().toISOString(),row.id,session.id).run();
 await requireMembership(env,actor,BILLING_ROLES);const afterSubmit=await billingUsageContext(env,actor);if(afterSubmit.periodKey!==row.period_key||afterSubmit.periodEnd!==row.period_end)throw new HttpError(409,'credit_period_changed','Your billing period changed during checkout. Refresh your allowance.');
 const guard=periodGuard(row,Math.floor(Date.now()/1000));
 await env.AGENT_DB.prepare(`UPDATE mayor_billing_credit_checkouts SET stripe_session_id=?,checkout_url=?,expires_at=?,status='open',updated_at=? WHERE id=? AND status='pending' AND ${guard.sql} AND EXISTS(SELECT 1 FROM agent_memberships m JOIN agent_tenants t ON t.id=m.tenant_id AND t.status='active' WHERE m.tenant_id=? AND m.user_id=? AND m.role IN ('owner','billing') AND m.status='active' AND (m.expires_at IS NULL OR m.expires_at>?))`).bind(session.id,url,session.expires_at,new Date().toISOString(),row.id,...guard.bindings,actor.tenantId,actor.userId,new Date(Date.now()).toISOString()).run();
 return {url:await currentCheckoutUrl(env,actor,row,session.id),requestId,replay:false};
}
export async function creditSessionEffects(env:BillingEnv,row:CreditCheckout,client:StripeClient):Promise<D1PreparedStatement[]>{
 if(!row.stripe_session_id)return [];const config=creditConfiguration(env,row.pack_id),pack=packFor(row.pack_id);await assertAccount(env,client);
 const session=await client.request(`/v1/checkout/sessions/${row.stripe_session_id}`);assertMode(session,config.mode);assertCreditMetadata(session,row);
 const customer=await env.AGENT_DB.prepare('SELECT stripe_customer_id FROM mayor_billing_customers WHERE tenant_id=? AND mode=?').bind(row.tenant_id,row.mode).first<{stripe_customer_id:string}>();
 if(session.id!==row.stripe_session_id||session.mode!=='payment'||objectId(session.customer)!==customer?.stripe_customer_id||session.client_reference_id!==row.id||row.mode!==config.mode||row.catalog_version!==CREDIT_PACK_VERSION||row.price_id!==config.priceId)throw new HttpError(409,'credit_ownership_mismatch','Credit pack payment ownership could not be verified.');
 const updated=new Date().toISOString();if(session.status==='expired')return [env.AGENT_DB.prepare("UPDATE mayor_billing_credit_checkouts SET status='expired',updated_at=? WHERE id=? AND status IN ('pending','open')").bind(updated,row.id)];
 if(session.status!=='complete'||session.payment_status!=='paid')return [];
 const lines=await client.request(`/v1/checkout/sessions/${row.stripe_session_id}/line_items?limit=2`),line=lines.data?.[0];if(lines.has_more||lines.data?.length!==1||objectId(line?.price)!==row.price_id||line.quantity!==1||line.currency!=='usd'||line.amount_subtotal!==pack.priceCents||line.amount_total!==pack.priceCents||session.currency!=='usd'||session.amount_subtotal!==pack.priceCents||session.amount_total!==pack.priceCents||session.total_details?.amount_discount!==0||session.total_details?.amount_tax!==0)throw new HttpError(409,'credit_payment_mismatch','The credit pack payment does not match the quoted purchase.');
 assertCreditPrice(await client.request(`/v1/prices/${row.price_id}`),env,row.pack_id);
 const intentId=objectId(session.payment_intent);if(!/^pi_[A-Za-z0-9]+$/.test(intentId??''))throw new HttpError(409,'credit_payment_unverified','Credit payment is not verified.');const intent=await client.request(`/v1/payment_intents/${intentId}`);assertMode(intent,config.mode);assertCreditMetadata(intent,row);if(intent.status!=='succeeded'||intent.currency!=='usd'||intent.amount!==pack.priceCents||intent.amount_received!==pack.priceCents||objectId(intent.customer)!==customer?.stripe_customer_id)throw new HttpError(409,'credit_payment_unverified','Credit payment is not verified.');
 const chargeId=objectId(intent.latest_charge);if(!/^ch_[A-Za-z0-9]+$/.test(chargeId??''))throw new HttpError(409,'credit_payment_unverified','The credit payment charge is not verified.');const charge=await client.request(`/v1/charges/${chargeId}`);assertMode(charge,config.mode);if(charge.paid!==true||charge.captured!==true||charge.amount!==pack.priceCents||charge.currency!=='usd'||objectId(charge.payment_intent)!==intentId||objectId(charge.customer)!==customer?.stripe_customer_id)throw new HttpError(409,'credit_payment_unverified','The credit payment charge is not verified.');
 const seconds=Math.floor(Date.now()/1000),guard=periodGuard(row,seconds),inPeriod=seconds>=row.period_start&&seconds<row.period_end&&(row.period_key.startsWith('pro:')||row.period_key===freePeriod().periodKey),invalidated=charge.refunded===true||charge.amount_refunded>0||charge.disputed===true;
 const valid=`(${inPeriod&&!invalidated?1:0}=1 AND ${guard.sql})`,status=invalidated?(charge.disputed?'disputed':'refunded'):'paid_expired';
 return [env.AGENT_DB.prepare(`UPDATE mayor_billing_credit_checkouts SET stripe_payment_intent_id=?,status=CASE WHEN status IN ('refunded','disputed','paid_expired') THEN status WHEN status='expired' THEN 'paid_expired' WHEN ${valid} THEN 'paid' ELSE ? END,updated_at=? WHERE id=?`).bind(intentId,...guard.bindings,status,updated,row.id),env.AGENT_DB.prepare(`INSERT INTO mayor_billing_credit_grants(checkout_id,tenant_id,mode,period_key,period_start,period_end,reply_attempts,voice_minutes,invalidated,paid_at) SELECT ?,?,?,?,?,?,?,?,CASE WHEN ${valid} AND (SELECT status FROM mayor_billing_credit_checkouts WHERE id=?)='paid' THEN 0 ELSE 1 END,? ON CONFLICT(checkout_id) DO NOTHING`).bind(row.id,row.tenant_id,row.mode,row.period_key,row.period_start,row.period_end,pack.replyAttempts,pack.voiceMinutes,...guard.bindings,row.id,updated),...(invalidated?[env.AGENT_DB.prepare('UPDATE mayor_billing_credit_grants SET invalidated=1 WHERE checkout_id=?').bind(row.id)]:[])];
}
export async function syncCreditEffects(env:BillingEnv,actor:Actor,client:StripeClient){const selected=mode(env),row=selected?await env.AGENT_DB.prepare("SELECT * FROM mayor_billing_credit_checkouts WHERE tenant_id=? AND mode=? AND status IN ('pending','open')").bind(actor.tenantId,selected).first<CreditCheckout>():null;return row?creditSessionEffects(env,row,client):[];}
export async function processCreditEvent(env:BillingEnv,event:StripeEvent,injected?:StripeClient){
 const config=baseConfiguration(env),client=clientFor(env,injected),object=event.data.object;let row:CreditCheckout|null=null,charge:StripeObject|undefined;
 if(event.type.startsWith('checkout.session.')){row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE stripe_session_id=? AND mode=?').bind(object.id,config.mode).first<CreditCheckout>();if(!row){if(object.metadata?.mayor_billing_domain===CREDIT_PACK_DOMAIN)throw new HttpError(409,'credit_checkout_unmapped','This payment is waiting for its checkout record.');return null;}}
 else if(event.type==='charge.refunded'||event.type==='charge.dispute.created'){const chargeId=event.type==='charge.refunded'?object.id:objectId(object.charge);if(!/^ch_[A-Za-z0-9]+$/.test(chargeId??''))return null;charge=await client.request(`/v1/charges/${chargeId}`);assertMode(charge,config.mode);const intentId=objectId(charge.payment_intent);row=intentId?await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE stripe_payment_intent_id=? AND mode=?').bind(intentId,config.mode).first<CreditCheckout>():null;if(!row&&intentId){const intent=await client.request(`/v1/payment_intents/${intentId}`);assertMode(intent,config.mode);if(intent.metadata?.mayor_billing_domain===CREDIT_PACK_DOMAIN)row=await env.AGENT_DB.prepare('SELECT * FROM mayor_billing_credit_checkouts WHERE id=? AND mode=?').bind(intent.metadata.mayor_credit_checkout_id??'',config.mode).first<CreditCheckout>();}if(!row)return null;}
 else return null;
 const hash=await digest(JSON.stringify(event)),updated=new Date().toISOString(),token=crypto.randomUUID();await env.AGENT_DB.prepare("INSERT INTO mayor_billing_events(mode,event_id,payload_hash,status,event_type,received_at) VALUES(?,?,?,'pending',?,?) ON CONFLICT(mode,event_id) DO NOTHING").bind(config.mode,event.id,hash,event.type,updated).run();const stored=await env.AGENT_DB.prepare('SELECT payload_hash,status FROM mayor_billing_events WHERE mode=? AND event_id=?').bind(config.mode,event.id).first<{payload_hash:string;status:string}>();if(stored?.payload_hash!==hash)throw new HttpError(409,'billing_event_conflict','This credit event needs review.');if(stored.status==='processed')return {received:true,outcome:'duplicate'};
 const claimed=await env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='processing',processing_token=?,lease_expires_at=?,error_code=NULL WHERE mode=? AND event_id=? AND (status IN ('pending','failed') OR (status='processing' AND lease_expires_at<=?))").bind(token,Date.now()+120000,config.mode,event.id,Date.now()).run();if(!claimed.meta.changes)throw new HttpError(503,'billing_event_busy','The credit payment is being processed.');let lease:string|undefined;
 try{lease=await acquireLease(env,row.tenant_id,config.mode);let effects:D1PreparedStatement[];
  if(charge){await assertAccount(env,client);const customer=await env.AGENT_DB.prepare('SELECT stripe_customer_id FROM mayor_billing_customers WHERE tenant_id=? AND mode=?').bind(row.tenant_id,row.mode).first<{stripe_customer_id:string}>();if(objectId(charge.customer)!==customer?.stripe_customer_id)throw new HttpError(409,'credit_ownership_mismatch','The payment adjustment owner could not be verified.');const intentId=objectId(charge.payment_intent),intent=await client.request(`/v1/payment_intents/${intentId}`);assertMode(intent,config.mode);assertCreditMetadata(intent,row);effects=[env.AGENT_DB.prepare("UPDATE mayor_billing_credit_checkouts SET stripe_payment_intent_id=?,status=?,updated_at=? WHERE id=?").bind(intentId,event.type==='charge.dispute.created'?'disputed':'refunded',updated,row.id),env.AGENT_DB.prepare('UPDATE mayor_billing_credit_grants SET invalidated=1 WHERE checkout_id=?').bind(row.id)];}
  else effects=await creditSessionEffects(env,row,client);
  const fence=`${token}:credit-event`;effects.unshift(env.AGENT_DB.prepare('INSERT INTO mayor_billing_fences(token,verified_token) VALUES(?,(SELECT processing_token FROM mayor_billing_events WHERE mode=? AND event_id=? AND processing_token=? AND lease_expires_at>?))').bind(fence,config.mode,event.id,token,Date.now()));effects.push(env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='processed',processing_token=NULL,lease_expires_at=NULL WHERE mode=? AND event_id=? AND processing_token=?").bind(config.mode,event.id,token),env.AGENT_DB.prepare('DELETE FROM mayor_billing_fences WHERE token=?').bind(fence));await commitLease(env,row.tenant_id,config.mode,lease,effects);return {received:true,outcome:'processed'};
 }catch(error){if(lease)await releaseLease(env,row.tenant_id,config.mode,lease);await env.AGENT_DB.prepare("UPDATE mayor_billing_events SET status='failed',processing_token=NULL,lease_expires_at=NULL,error_code=? WHERE mode=? AND event_id=? AND processing_token=?").bind(error instanceof HttpError?error.code:'credit_processing_failed',config.mode,event.id,token).run();throw error;}
}
