// Auto-tender pipeline:
//   GET  /api/admin/auto-tender        → recent runs (last 20)
//   POST /api/admin/auto-tender        → kick off the morning pipeline over Discovery-stage SAM items
//                                        with response_deadline 1..10 days out. Idempotent per SAM
//                                        row per calendar day (one draft per SAM per day).
//
// The actual LLM-driven draft generation is delegated to functions/api/_shared/autoTenderPipeline.js
// (generated by Agent B). This thin handler simply persists the run + draft and exposes operations.

import { verifyAdminToken, json, corsHeaders } from "../../_shared/adminAuth.js";
import {
  generateAutoTenderDraft,
  findTenderableOpportunities,
  PIPELINE_LIMIT,
  DEADLINE_WINDOW_DAYS,
} from "../../_shared/autoTenderPipeline.js";

export async function onRequestOptions({ request, env }) {
  return new Response(null, { status: 204, headers: corsHeaders(request, env) });
}

export async function onRequestGet({ request, env }) {
  const auth = await verifyAdminToken(request, env);
  if (!auth.ok) return json({ ok: false, error: auth.message }, auth.status, request, env);
  if (!env?.LEADS_DB) return json({ ok: false, error: "missing_db" }, 500, request, env);
  try {
    const url = new URL(request.url);
    const limit = Math.min(parseInt(url.searchParams.get("limit") || "20", 10) || 20, 100);

    const rows = await env.LEADS_DB.prepare(`
      SELECT id, triggered_at, sam_item_id, sam_item_title, sam_item_deadline,
             sam_item_stage, sam_item_fit_score, status, status_detail, draft_id,
             drafts_count, errors_json, created_at, completed_at
      FROM auto_tender_runs
      ORDER BY triggered_at DESC
      LIMIT ?
    `).bind(limit).all();

    const items = (rows.results || []).map((r) => ({
      ...r,
      errors: safeParse(r.errors_json, []),
    }));

    return json({
      ok: true,
      items,
      total: items.length,
      window: DEADLINE_WINDOW_DAYS,
      per_run_limit: PIPELINE_LIMIT,
      updatedAt: new Date().toISOString(),
    }, 200, request, env);
  } catch (err) {
    return json({ ok: false, error: "list_failed", details: String(err?.message || err) }, 500, request, env);
  }
}

export async function onRequestPost({ request, env }) {
  const auth = await verifyAdminToken(request, env);
  if (!auth.ok) return json({ ok: false, error: auth.message }, auth.status, request, env);
  if (!env?.LEADS_DB) return json({ ok: false, error: "missing_db" }, 500, request, env);

  let body;
  try { body = await request.json(); } catch { body = {}; }
  const singleSamId = body?.sam_id || null;
  const maxItems = Math.min(parseInt(body?.max || "" || PIPELINE_LIMIT, 10) || PIPELINE_LIMIT, 25);

  try {
    let opps;
    if (singleSamId) {
      const row = await env.LEADS_DB.prepare(`
        SELECT id, title, agency, office, source, source_url, opportunity_type,
               set_aside, naics_codes_json, posted_date, response_deadline,
               estimated_value, summary, fit_score, confidence, stage,
               raw_json
        FROM gov_opportunities WHERE id = ? LIMIT 1
      `).bind(singleSamId).first();
      opps = row ? [row] : [];
    } else {
      opps = await findTenderableOpportunities(env.LEADS_DB);
      opps = opps.slice(0, maxItems);
    }
    if (!opps.length) {
      return json({ ok: true, drafted: 0, runs: [], note: "no_tenderable_opportunities" }, 200, request, env);
    }

    const runs = [];
    const now = new Date();
    const day = now.toISOString().slice(0, 10);

    for (const opp of opps) {
      // Idempotency: skip if a successful draft already exists for this SAM id today.
      const already = await env.LEADS_DB.prepare(`
        SELECT id FROM auto_tender_runs
        WHERE sam_item_id = ? AND date(triggered_at) = ? AND status IN ('completed', 'running')
        ORDER BY triggered_at DESC LIMIT 1
      `).bind(opp.id, day).first();
      if (already) {
        runs.push({ sam_id: opp.id, title: opp.title, skipped: true, reason: "already_drafted_today", run_id: already.id });
        continue;
      }

      const runId = crypto.randomUUID();
      const startIso = now.toISOString();

      // Persist a 'running' row up front so the user can watch progress.
      try {
        await env.LEADS_DB.prepare(`
          INSERT INTO auto_tender_runs (id, triggered_at, sam_item_id, sam_item_title,
            sam_item_deadline, sam_item_stage, sam_item_fit_score, status, status_detail,
            drafts_count, errors_json, created_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, 'running', '', 0, '[]', ?)
        `).bind(
          runId, startIso, opp.id, opp.title,
          opp.response_deadline || null, opp.stage || null,
          opp.fit_score ?? null, startIso,
        ).run();
      } catch (e) {
        runs.push({ sam_id: opp.id, title: opp.title, skipped: true, reason: "insert_failed", error: String(e?.message || e) });
        continue;
      }

      let result;
      try { result = await generateAutoTenderDraft({ env, opp, runId, now }); }
      catch (e) { result = { draftId: null, status: "failed", errors: [`generate_exception: ${e?.message || e}`], draft: null }; }

      const errors = result.errors || [];
      const status = result.status === "completed" && errors.length === 0 ? "completed"
                    : result.status === "completed" ? "completed" : "failed";
      const statusDetail = errors.length ? errors.slice(0, 3).join("; ") : "ok";

      try {
        await env.LEADS_DB.prepare(`
          UPDATE auto_tender_runs SET
            status = ?, status_detail = ?, draft_id = ?, drafts_count = ?,
            errors_json = ?, completed_at = ?
          WHERE id = ?
        `).bind(
          status, statusDetail, result.draftId || null, result.draft ? 1 : 0,
          JSON.stringify(errors).slice(0, 4000), new Date().toISOString(), runId,
        ).run();
      } catch (e) {
        // non-fatal: pipeline produced a draft, just no run row update
      }

      // Audit (no tokens / no phone numbers)
      try {
        await env.LEADS_DB.prepare(`
          INSERT INTO opportunity_events (id, kind, prospect_id, sam_id, event_type, actor, payload_json, created_at)
          VALUES (?, 'sam', NULL, ?, 'auto_tender', 'system', ?, ?)
        `).bind(
          crypto.randomUUID(),
          opp.id,
          JSON.stringify({ runId, status, errors: errors.slice(0, 3), draftId: result.draftId || null }).slice(0, 4000),
          new Date().toISOString(),
        ).run();
      } catch {}

      runs.push({
        sam_id: opp.id,
        title: opp.title,
        run_id: runId,
        status,
        draft_id: result.draftId,
        errors,
      });
    }

    return json({
      ok: true,
      drafted: runs.filter((r) => r.status === "completed").length,
      runs,
      updated_at: new Date().toISOString(),
    }, 200, request, env);
  } catch (err) {
    return json({ ok: false, error: "run_failed", details: String(err?.message || err) }, 500, request, env);
  }
}

function safeParse(s, fallback) {
  if (!s) return fallback;
  try { return JSON.parse(s); } catch { return fallback; }
}
