import type {AuditReview,BusinessAuditReport} from '../src/business-audit-schema';
import {parseAuditRoadmapDeliverable,validateAuditRoadmapReferences} from '../src/business-audit-roadmap.ts';

export type AuditReportEnvelope={orderId:string;report:BusinessAuditReport;review:AuditReview;createdAt:string};
const categories={offer:'Offer & service clarity',journey:'Customer journey & retention',trust:'Trust & local visibility',conversion:'Inquiries & booking',operations:'Daily operations',measurement:'Measurement & priorities'};
const levels=['low','medium','high'] as const;
export function reportHighlights(report:BusinessAuditReport){
 return {pages:report.sources.length,findings:report.findings.length,priorities:{P1:report.findings.filter(item=>item.priority==='P1').length,P2:report.findings.filter(item=>item.priority==='P2').length,P3:report.findings.filter(item=>item.priority==='P3').length},coverage:Object.entries(categories).map(([id,label])=>({id,label,count:report.findings.filter(item=>item.category===id).length})),matrix:[...levels].reverse().map(impact=>({impact,cells:levels.map(effort=>({effort,ids:report.findings.filter(item=>item.impact===impact&&item.effort===effort).map(item=>item.id)}))}))};
}
export function reportRoadmapActions(report:BusinessAuditReport){
 const verified=validateAuditRoadmapReferences(report.roadmap,report.findings.map(finding=>finding.id),{allowUnmappedLegacy:true});
 if(!verified.valid)throw new Error('The saved roadmap action references could not be verified.');
 const findings=new Map(report.findings.map(finding=>[finding.id,finding]));
 const findingLink=(id:string)=>{const finding=findings.get(id);if(!finding||typeof finding.title!=='string'||!finding.title.trim())throw new Error('The saved roadmap finding title could not be verified.');return {id,title:finding.title,href:`#finding-${id}`};};
 return report.roadmap.map(phase=>({window:phase.window,mode:verified.mode,relatedFindings:phase.findingIds.map(findingLink),actions:phase.deliverables.map(value=>{
  const action=parseAuditRoadmapDeliverable(value);
  if(action.kind==='invalid')throw new Error('The saved roadmap action could not be verified.');
  return {text:action.text,findings:action.kind==='mapped'?action.findingIds.map(findingLink):[]};
 })}));
}
export function verifiedReportEnvelope(value:unknown):AuditReportEnvelope{
 const object=value as AuditReportEnvelope|undefined,r=object?.report,review=object?.review;
 if(!object||typeof object.orderId!=='string'||!r||r.schemaVersion!==1||r.orderId!==object.orderId||typeof r.businessName!=='string'||typeof r.website!=='string'||typeof object.createdAt!=='string'||!r.summary||Object.values(r.summary).some(item=>typeof item!=='string')||!r.business||!r.scope||!Array.isArray(r.scope.limitations)||!Array.isArray(r.sources)||r.sources.length<1||r.sources.length>8||!Array.isArray(r.findings)||r.findings.length<6||r.findings.length>12||!Array.isArray(r.roadmap)||r.roadmap.length!==3||!Array.isArray(r.unknowns)||!Array.isArray(r.questionsToResolve)||!review?.approved||!review.verification||(['citationGrounding','scopeHonesty','actionability','noFabricatedMetrics'] as const).some(key=>review.verification[key]!==true)||!Array.isArray(review.issues)||review.issues.some(item=>item.severity==='critical'||item.severity==='major'))throw new Error('The saved report and automatic review could not be verified.');
 const sourceIds=new Set(r.sources.map(source=>source.id)),findingIds=new Set(r.findings.map(finding=>finding.id));
 if(sourceIds.size!==r.sources.length||findingIds.size!==r.findings.length||r.findings.some(finding=>!/^F(?:0[1-9]|1[0-2])$/.test(finding.id)||!(finding.category in categories)||!['P1','P2','P3'].includes(finding.priority)||!levels.includes(finding.impact)||!levels.includes(finding.effort)||!Array.isArray(finding.citations)||finding.citations.length<1||finding.citations.some(citation=>!sourceIds.has(citation.sourceId)||typeof citation.quote!=='string')||!Array.isArray(finding.nextSteps)||!finding.measurement||finding.measurement.currentBaseline!==null)||new Set(r.roadmap.map(step=>step.window)).size!==3||r.roadmap.some(step=>!['30_days','60_days','90_days'].includes(step.window)||!Array.isArray(step.deliverables)||!Array.isArray(step.findingIds)||step.findingIds.some(id=>!findingIds.has(id))))throw new Error('The saved report references could not be verified.');
 reportRoadmapActions(r);
 return object;
}
export function reportSourceUrl(raw:string){try{const url=new URL(raw);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}}
export function reportDownloadName(name:string){return `${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'business'}-mayor-audit.json`;}

function node<K extends keyof HTMLElementTagNameMap>(tag:K,className='',text?:string){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element;}
function paragraph(text:string,className=''){return node('p',className,text);}
function link(label:string,href:string,className=''){const element=node('a',className,label);element.href=href;return element;}
function list(items:string[],ordered=false){const element=node(ordered?'ol':'ul','report-list');for(const item of items)element.append(node('li','',item));return element;}
function roadmapActionList(actions:ReturnType<typeof reportRoadmapActions>[number]['actions']){const element=node('ul','report-list roadmap-actions');for(const action of actions){const item=node('li');item.append(node('span','roadmap-action-text',action.text));if(action.findings.length){const references=node('div','roadmap-action-findings');for(const finding of action.findings)references.append(link(finding.title,finding.href,'roadmap-finding-link'));item.append(references);}element.append(item);}return element;}
function pill(text:string,className=''){return node('span',`report-pill ${className}`,text);}
function section(id:string,kicker:string,title:string){const element=node('section','report-section');element.id=id;element.tabIndex=-1;const heading=node('div','report-section-title'),label=node('h2','',title);label.id=`${id}-heading`;element.setAttribute('aria-labelledby',label.id);heading.append(node('span','section-kicker',kicker),label);element.append(heading);return element;}
function field(label:string,value:string){const item=node('div','report-field');item.append(node('h4','',label),paragraph(value));return item;}
function date(raw:string){const parsed=new Date(raw);return Number.isNaN(parsed.valueOf())?'Date unavailable':new Intl.DateTimeFormat('en-US',{dateStyle:'long',timeZone:'UTC'}).format(parsed);}

export function renderAuditReport(envelope:AuditReportEnvelope,test:boolean){
 const {report:r,review}=envelope,highlights=reportHighlights(r),roadmapActions=reportRoadmapActions(r),main=document.getElementById('audit-content')!;
 document.title=`${r.businessName} · Private business audit · The Mayor`;
 const robots=document.createElement('meta');robots.name='robots';robots.content='noindex, nofollow';document.head.append(robots);
 document.querySelector('link[rel="canonical"]')?.remove();
 const header=document.querySelector('.site-header')!,navigation=header.querySelector('nav');header.classList.add('report-header');navigation?.setAttribute('aria-label','Report sections');navigation?.replaceChildren(link('Priorities','#priorities'),link('Plan','#roadmap'),link('Evidence','#evidence'));
 const headerAction=header.querySelector<HTMLAnchorElement>('.button');if(headerAction){headerAction.href='/business-audit';headerAction.textContent='Audit details';}
 const footerTerms=document.querySelector<HTMLAnchorElement>('.site-footer a[href="#audit-terms"]');if(footerTerms)footerTerms.href='/business-audit#audit-terms';
 main.className='report-page page-width';main.replaceChildren();
 const toolbar=node('div','report-toolbar'),exports=node('details','report-export'),exportToggle=node('summary','button button-outline button-small','Export report'),exportActions=node('div','report-export-actions'),print=node('button','button button-small','Print / save as PDF'),download=node('button','button button-outline button-small','Download report data'),copy=node('button','button button-outline button-small','Copy report data'),exportStatus=paragraph('','small-copy report-export-status');
 exportStatus.setAttribute('role','status');exportActions.id='report-export-actions';exportActions.setAttribute('role','group');exportActions.setAttribute('aria-label','Report exports');exportToggle.setAttribute('aria-controls',exportActions.id);const chevron=node('span','report-export-chevron','⌄');chevron.setAttribute('aria-hidden','true');exportToggle.append(chevron);print.type=download.type=copy.type='button';
 const closeExports=()=>{exports.open=false;exportToggle.focus();};
 exports.addEventListener('keydown',event=>{if(event.key==='Escape'&&exports.open){event.preventDefault();event.stopPropagation();closeExports();}});
 exports.addEventListener('focusout',event=>{if(event.relatedTarget instanceof Node&&!exports.contains(event.relatedTarget))exports.open=false;});
 print.addEventListener('click',()=>{closeExports();window.print();});
 download.addEventListener('click',()=>{closeExports();const url=URL.createObjectURL(new Blob([JSON.stringify(envelope,null,2)],{type:'application/json'})),anchor=link('',url);anchor.download=reportDownloadName(r.businessName);anchor.hidden=true;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);exportStatus.textContent='Report data prepared. Check your browser’s downloads, or use Copy report data.';});
 copy.addEventListener('click',()=>{closeExports();copy.disabled=true;void navigator.clipboard?.writeText(JSON.stringify(envelope,null,2)).then(()=>{exportStatus.textContent='Report data copied. Paste it into a file to keep your own copy.';}).catch(()=>{exportStatus.textContent='Clipboard access is unavailable. Use Download report data or select the report text.';}).finally(()=>{copy.disabled=false;});if(!navigator.clipboard){exportStatus.textContent='Clipboard access is unavailable. Use Download report data or select the report text.';copy.disabled=false;}});
 exportActions.append(print,download,copy);exports.append(exportToggle,exportActions);toolbar.append(link('← Your request','/business-audit','text-link'),exports);main.append(toolbar,exportStatus);
 if(test)main.append(paragraph('TEST REPORT · This report belongs to a test payment. It does not confirm a live $330 purchase.','test-notice'));
 const cover=node('section','report-cover'),coverCopy=node('div','report-cover-copy');coverCopy.append(node('span','section-kicker','YOUR BUSINESS. A CLEARER NEXT STEP.'),node('h1','',r.businessName),paragraph(r.summary.headline,'report-headline'));
 const site=reportSourceUrl(r.website);if(site)coverCopy.append(link(new URL(site).hostname,site,'report-website'));
 const stats=node('dl','report-stats');for(const [label,value] of [['Pages checked',highlights.pages],['Actionable findings',highlights.findings],['First priorities',highlights.priorities.P1]] as const){const item=node('div');item.append(node('dt','',label),node('dd','',String(value)));stats.append(item);}
 const coverMeta=node('div','report-cover-meta');coverMeta.append(pill('Automatically generated & reviewed'),paragraph(`Prepared ${date(r.generatedAt)} · $330 USD one-time audit`),paragraph('Evidence-backed recommendations. Impact and effort are estimates, not measured business results.','small-copy'));cover.append(coverCopy,stats,coverMeta);main.append(cover);
 const summary=section('summary','THE BUSINESS PICTURE','Where to focus. Where to begin.');summary.append(paragraph(r.summary.overview,'report-lead'));const summaryCards=node('div','report-summary-cards');summaryCards.append(field('Biggest opportunity',r.summary.biggestOpportunity),field('Starting point',r.summary.startingPoint));summary.append(summaryCards);
 const business=node('div','report-business');business.append(field('Offer',r.business.offer),field('Audience',r.business.audience),field('Service area',r.business.serviceArea??'Not verified from the available evidence'));summary.append(business);main.append(summary);
 const coverage=section('coverage','SIX CONNECTED AREAS','The shape of your audit.');coverage.append(paragraph('Each area below links to findings in this report. Counts describe report coverage; they are not business scores.'));const coverageGrid=node('div','report-coverage');for(const item of highlights.coverage){const card=link('',`#category-${item.id}`,'report-coverage-item');card.append(node('strong','',String(item.count)),node('span','',item.label));coverageGrid.append(card);}coverage.append(coverageGrid);main.append(coverage);
 const priorities=section('priorities','THE ORDER OF ACTION','Make attention count.');priorities.append(paragraph('P1: begin here. P2: improve next. P3: consider after the foundations. Estimated impact, effort, and confidence help you compare recommendations; none is a measured performance score.'));
 const priorityTotals=node('div','report-priority-totals');for(const key of ['P1','P2','P3'] as const)priorityTotals.append(pill(`${key} · ${highlights.priorities[key]} findings`,key.toLowerCase()));priorities.append(priorityTotals);
 const tableWrap=node('div','report-table-wrap'),table=node('table','report-table'),caption=node('caption','','Prioritized findings and estimated implementation effort');caption.id='priority-table-caption';tableWrap.tabIndex=0;tableWrap.setAttribute('role','region');tableWrap.setAttribute('aria-labelledby',caption.id);tableWrap.setAttribute('aria-describedby','priority-table-hint');table.append(caption);const head=node('thead'),headRow=node('tr');for(const label of ['Priority','Finding','Estimated impact','Estimated effort','Confidence']){const cell=node('th','',label);cell.scope='col';headRow.append(cell);}head.append(headRow);table.append(head);const body=node('tbody');for(const finding of [...r.findings].sort((a,b)=>a.priority.localeCompare(b.priority)||a.id.localeCompare(b.id))){const row=node('tr');const priority=node('td');priority.append(pill(finding.priority,finding.priority.toLowerCase()));const name=node('td');name.append(link(`${finding.id} · ${finding.title}`,`#finding-${finding.id}`));row.append(priority,name,node('td','capitalize',finding.impact),node('td','capitalize',finding.effort),node('td','capitalize',finding.confidence));body.append(row);}table.append(body);tableWrap.append(table);const tableHint=paragraph('Scroll to compare impact, effort, and confidence.','report-table-hint');tableHint.id='priority-table-hint';priorities.append(tableWrap,tableHint);
 const matrixSection=node('div','report-matrix-section');matrixSection.append(node('h3','','Find the practical starting points'),paragraph('Findings are positioned by estimated impact and effort. A high-impact, low-effort finding can be a useful early focus; confirm assumptions before implementation.'));
 const matrixWrap=node('div','report-table-wrap'),matrix=node('table','report-matrix');const matrixCaption=node('caption','','Estimated impact by estimated effort — finding IDs link to evidence');matrixCaption.id='impact-effort-caption';matrixWrap.tabIndex=0;matrixWrap.setAttribute('role','region');matrixWrap.setAttribute('aria-labelledby',matrixCaption.id);matrix.append(matrixCaption);const matrixHead=node('thead'),matrixRow=node('tr');matrixRow.append(node('th','','Impact ↓ / Effort →'));for(const level of levels){const th=node('th','capitalize',level);th.scope='col';matrixRow.append(th);}matrixHead.append(matrixRow);matrix.append(matrixHead);const matrixBody=node('tbody');for(const row of highlights.matrix){const tr=node('tr'),th=node('th','capitalize',row.impact);th.scope='row';tr.append(th);for(const cell of row.cells){const td=node('td',`matrix-cell impact-${row.impact} effort-${cell.effort}`);if(cell.ids.length)for(const id of cell.ids)td.append(link(id,`#finding-${id}`,'matrix-finding'));else td.append(node('span','matrix-empty','—'));tr.append(td);}matrixBody.append(tr);}matrix.append(matrixBody);matrixWrap.append(matrix);matrixSection.append(matrixWrap);priorities.append(matrixSection);main.append(priorities);
 const roadmap=section('roadmap','30 / 60 / 90 DAYS','A plan you can work through.');roadmap.append(paragraph('Suggested planning windows begin when you start implementing. They are a sequence of work, not a report delivery promise.'));const roadmapGrid=node('div','report-roadmap');for(const window of ['30_days','60_days','90_days'] as const){const step=r.roadmap.find(item=>item.window===window)!,plan=roadmapActions.find(item=>item.window===window)!;const card=node('article','roadmap-step');card.append(node('span','section-kicker',`${window.split('_')[0]} DAYS`),node('h3','',step.objective),paragraph(`Suggested owner: ${step.ownerRole}`,'roadmap-owner'),roadmapActionList(plan.actions));if(plan.mode==='legacy'){const related=node('div','roadmap-related');related.append(node('span','','Related findings: '));for(const finding of plan.relatedFindings)related.append(link(finding.title,finding.href,'roadmap-finding-link'));card.append(related);}roadmapGrid.append(card);}roadmap.append(roadmapGrid);main.append(roadmap);
 const findings=section('findings','FROM EVIDENCE TO ACTION','Every finding, in detail.');findings.append(paragraph('Use the source references to inspect the evidence. Recommendations and proposed copy are suggestions to validate with your business.'));
 for(const [category,label] of Object.entries(categories)){const categorySection=node('div','report-category');categorySection.id=`category-${category}`;categorySection.append(node('h3','report-category-heading',label));for(const finding of r.findings.filter(item=>item.category===category)){
  const card=node('article','report-finding');card.id=`finding-${finding.id}`;const findingMeta=node('div','finding-meta');findingMeta.append(node('span','finding-id',finding.id),pill(finding.priority,finding.priority.toLowerCase()),pill(`Impact: ${finding.impact} · effort: ${finding.effort}`),pill(`Confidence: ${finding.confidence}`));card.append(findingMeta,node('h3','',finding.title));
  const rationale=node('div','finding-rationale');rationale.append(field('What the evidence shows',finding.observation),field('Why it matters',finding.whyItMatters));card.append(rationale,field('Recommended action',finding.recommendation));const next=node('div','finding-next-steps');next.append(node('h4','','Next steps'),list(finding.nextSteps,true));card.append(next);
  const citations=node('div','finding-citations');citations.append(node('h4','','Annotated source evidence'));for(const citation of finding.citations){const quote=node('figure','evidence-quote'),blockquote=node('blockquote','',citation.quote),caption=node('figcaption');const source=r.sources.find(item=>item.id===citation.sourceId)!;caption.append(link(`${source.id} · ${source.title||new URL(source.url).hostname}`,`#source-${source.id}`),node('span','',`Checked ${date(source.checkedAt)} · ${source.providedBy==='owner_link'?'Owner-supplied link':'Public website'}`));quote.append(blockquote,caption);citations.append(quote);}card.append(citations);
  const measurement=node('div','finding-measurement');measurement.append(node('span','section-kicker','HOW TO CHECK PROGRESS'),field('Metric',finding.measurement.metric),field('Current baseline','Not measured. Establish a baseline before judging results.'),field('How to collect it',finding.measurement.howToCollect),field('Success signal',finding.measurement.successSignal));card.append(measurement);
  if(finding.copyExample){const example=node('div','finding-copy-example');example.append(node('h4','','Proposed copy to adapt'),paragraph(finding.copyExample));card.append(example);}categorySection.append(card);
 }findings.append(categorySection);}main.append(findings);
 const evidence=section('evidence','AN INSPECTABLE FOUNDATION','What was actually checked.');evidence.append(paragraph(r.scope.method,'report-lead'),paragraph('The checks below are observations from captured static HTML. A link or form count does not prove a booking flow works. Missing metadata or alternate text is a prompt to investigate, not a conversion or accessibility score.'));
 for(const source of r.sources){const card=node('article','report-source');card.id=`source-${source.id}`;card.append(node('span','section-kicker',`${source.id} · ${source.providedBy==='owner_link'?'OWNER-SUPPLIED LINK':'PUBLIC WEBSITE'}`),node('h3','',source.title||'Captured source'));const url=reportSourceUrl(source.url);if(url){const external=link(url,url,'source-url');external.target='_blank';external.rel='noopener noreferrer';card.append(external);}card.append(paragraph(`Checked ${date(source.checkedAt)}`,'small-copy'));const facts=node('dl','source-facts');const o=source.observations;for(const [label,value] of [['Page title',o.titlePresent?'Present':'Not detected'],['Meta description',o.descriptionPresent?'Present':'Not detected'],['Mobile viewport',o.viewportPresent?'Present':'Not detected'],['H1 headings',o.h1Count],['Images',o.imageCount],['Images without alt',o.imagesMissingAlt],['Forms',o.formCount],['Booking links',o.bookingLinkCount],['Contact links',o.contactLinkCount]] as const){const fact=node('div');fact.append(node('dt','',label),node('dd','',String(value)));facts.append(fact);}card.append(facts);const captured=node('details','source-capture');captured.append(node('summary','','Inspect captured text and fingerprint'),paragraph(source.excerpt,'source-excerpt'),paragraph(`SHA-256: ${source.contentHash}`,'source-hash'));card.append(captured,paragraph(`Checked ${source.checkedAt} · SHA-256: ${source.contentHash}`,'source-hash source-print-fingerprint'));evidence.append(card);}main.append(evidence);
 const limits=section('limitations','WHAT STILL NEEDS AN ANSWER','Keep the boundaries visible.');limits.append(field('Collection limitations','These limits describe the evidence available during this audit, not issues confirmed in your business.'),list(r.scope.limitations));const unknownGrid=node('div','report-unknowns');const unknown=node('div'),questions=node('div');unknown.append(node('h3','','Not yet known'),list(r.unknowns));questions.append(node('h3','','Questions to resolve'),list(r.questionsToResolve));unknownGrid.append(unknown,questions);limits.append(unknownGrid);main.append(limits);
 const reviewSection=section('review','AUTOMATIC GENERATION + INDEPENDENT REVIEW','A reviewed, saved deliverable.');reviewSection.append(paragraph(review.summary));const verification=node('div','report-verification');for(const label of ['Citation grounding checked','Scope honesty checked','Actionability checked','No fabricated metrics checked'])verification.append(pill(`✓ ${label}`));reviewSection.append(verification,node('h3','','Review strengths'),list(review.strengths));if(review.issues.length){reviewSection.append(node('h3','','Review notes'));for(const issue of review.issues)reviewSection.append(field(`${issue.severity}${issue.findingId?` · ${issue.findingId}`:''}`,`${issue.message} ${issue.suggestedFix}`));}const provenance=node('dl','report-provenance');for(const [label,value] of [['Analysis model',r.analysisModel],['Review model',review.model],['Reviewed',date(review.reviewedAt)],['Report saved',date(envelope.createdAt)],['Request',envelope.orderId]]){const item=node('div');item.append(node('dt','',label),node('dd','',value));provenance.append(item);}reviewSection.append(provenance);main.append(reviewSection);
 main.append(paragraph('This audit gives you evidence-backed recommendations and an implementation plan. It does not make changes to your business, access private accounts, or guarantee revenue, ranking, retention, or conversion improvements.','report-closing'));
}

export async function mountAuditReport(statusTokenKey:string,validToken:(raw:unknown)=>raw is string){
 const main=document.getElementById('audit-content')!;main.className='report-page page-width';main.replaceChildren();const loading=node('section','report-loading');loading.append(node('span','section-kicker','YOUR PRIVATE BUSINESS AUDIT'),node('h1','','Opening your report…'),paragraph('Verifying your saved payment, report, and automatic review.','report-loading-message'));main.append(loading);
 const location=new URL(window.location.href),fragment=new URLSearchParams(location.hash.slice(1)),incoming=fragment.get('receipt');let token:string|null=null;
 if(validToken(incoming)){token=incoming;try{sessionStorage.setItem(statusTokenKey,token);}catch{}}
 else if(incoming===null){try{const saved=sessionStorage.getItem(statusTokenKey);if(validToken(saved))token=saved;}catch{}}
 if(location.hash){location.hash='';history.replaceState({},'',location.pathname+location.search);}
 const nav=document.querySelector('.site-header nav');nav?.replaceChildren(link('Audit details','/business-audit'),link('Your request','/business-audit'));
 const headerAction=document.querySelector<HTMLAnchorElement>('.site-header .button');if(headerAction){headerAction.href='/business-audit';headerAction.textContent='Audit details';}
 async function api(path:string){const response=await fetch(path,{headers:{authorization:`Bearer ${token}`},credentials:'same-origin',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(20000)});let data:any;try{data=await response.json();}catch{throw new Error('The saved report could not be verified. Please retry.');}if(!response.ok)throw new Error(typeof data.message==='string'?data.message:'Your report is not available yet. Check your saved request status.');return data;}
 async function load(){try{if(!token)throw new Error('Open the private report link from your saved receipt. No report has been loaded.');const receipt=await api('/api/business-audit/status');if(!['live','test'].includes(receipt.mode)||receipt.priceCents!==33000||receipt.currency!=='USD')throw new Error('The saved request could not be verified.');if(receipt.paymentStatus!=='paid'||receipt.fulfillmentStatus!=='report_ready'||!receipt.reportAvailable)throw new Error('Your report is not ready yet. Your request page shows payment and generation status separately.');const result=verifiedReportEnvelope(await api('/api/business-audit/report'));if(result.orderId!==receipt.orderId)throw new Error('The report does not match this saved request.');renderAuditReport(result,receipt.mode==='test');}catch(error){loading.replaceChildren(node('span','section-kicker','YOUR PRIVATE BUSINESS AUDIT'),node('h1','','Your report is not available here yet.'),paragraph(error instanceof Error?error.message:'Please retry from your saved receipt.'));const actions=node('div','receipt-actions'),retry=node('button','button','Retry');retry.type='button';retry.addEventListener('click',()=>{retry.disabled=true;void load();});actions.append(link('View request status','/business-audit','button button-outline'),retry);loading.append(actions);}}
 await load();
}
