import {playbookActionIcon,playbookMetricIcon,playbookTemplateIcon,playbookThumbnail} from './playbook-visuals';
type Template={id:string;title:string;description:string;cadence:string;steps:string[];assistantPrompt:string};
type Schedule={timeZone:string;frequency:'daily'|'weekdays';hour:number;minute:number};
type Config={enabled:boolean;templateIds:string[];schedule:Schedule|null;revision:number;nextRunAt:string|null;lastRunAt:string|null;lastStatus:string|null;running:boolean};
type Brief={id:string;generatedAt:string;summary:string;metrics:{key:string;label:string;value:number|null}[];priorities:{id:string;title:string;detail:string;assistantPrompt?:string}[];suggestions:{title:string;detail:string;assistantPrompt:string}[];gaps:string[];scope:string};
type Data={catalog:Template[];config:Config;latestBrief:Brief|null;scope:string};
type Hooks={api:(path:string,body?:unknown)=>Promise<any>;tenant:()=>string;ask:(text:string)=>void;onChanged?:()=>void};
const node=<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className='')=>{const el=document.createElement(tag);el.textContent=text;el.className=className;return el;};
const button=(label:string,action:()=>void,className='secondary')=>{const el=node('button',label,className);el.prepend(playbookActionIcon(label));el.type='button';el.onclick=action;return el;};
export function routineConfigReadback(input:{enabled:boolean;templateIds:string[];schedule?:Schedule},catalog:Template[]){
 const titles=input.templateIds.map(id=>catalog.find(item=>item.id===id)?.title??id).join(', ');
 if(!input.enabled){const s=input.schedule;return `Save ${titles} for on-demand briefs and pause automatic reviews?${s?` Your saved review time is ${String(s.hour).padStart(2,'0')}:${String(s.minute).padStart(2,'0')} in ${s.timeZone}; it runs only when you enable automatic reviews.`:''}`;}
 const s=input.schedule!;return `Review ${titles} ${s.frequency==='daily'?'every day':'Monday through Friday'} at ${String(s.hour).padStart(2,'0')}:${String(s.minute).padStart(2,'0')} in ${s.timeZone}? Results appear in this business’s playbook and Notifications. You review every suggested action.`;
}
export function createBusinessRoutines(hooks:Hooks){
 const element=node('section','','business-routines');element.setAttribute('aria-label','Business playbook');
 let version=0,accessEpoch=0,data:Data|null=null,requestId:string|null=null,busy=false;
 const base=()=>`/api/businesses/${hooks.tenant()}/routines`;
 function failure(error:unknown){const status=element.querySelector<HTMLElement>('.routines-status');if(status){status.textContent=error instanceof Error?error.message:'This review could not finish. Try again.';status.setAttribute('role','alert');}}
 async function load(){const captured=++version;element.replaceChildren(node('h2','Business playbook'),node('p','Loading your routines…','routines-status'));try{const result=await hooks.api(base()) as Data;if(captured!==version)return;data=result;render();}catch(error){if(captured!==version)return;failure(error);element.append(button('Try again',()=>void load()));}}
 function render(){if(!data)return;const current=data;element.replaceChildren();const header=node('div','','routines-heading'),copy=node('div');copy.append(node('h2','Business playbook'),node('p','Saved flows, reminders, and next steps.'));
 const headerActions=node('div','','routine-actions');headerActions.append(button('Refresh playbook',()=>void load()));if(current.config.revision){const run=button(requestId?'Check this review again':'Review my business now',()=>void runNow(),'primary');run.disabled=busy;headerActions.append(run);}header.append(copy,headerActions);element.append(header);
 const status=node('p','','routines-status');status.setAttribute('role','status');element.append(status);
 const config=current.config,schedule=config.schedule;const state=node('p','','routine-state');state.textContent=config.enabled?`${schedule?.frequency==='weekdays'?'Weekdays':'Daily'} · ${schedule?`${String(schedule.hour).padStart(2,'0')}:${String(schedule.minute).padStart(2,'0')} · ${schedule.timeZone}`:''}`:'Automatic reviews are paused. Run a saved playbook whenever you need it.';
 if(config.running)state.append(node('span',' A review is in progress.'));
 if(config.nextRunAt&&schedule)state.append(node('span',` Next review: ${new Date(config.nextRunAt).toLocaleString(undefined,{timeZone:schedule.timeZone})}.`));
 if(config.lastStatus==='failed')state.append(node('span',' The last review could not finish. Refresh or try an on-demand review.'));
 state.setAttribute('role','status');element.append(state);if(current.latestBrief)briefView(current.latestBrief);
 const form=node('form','','routine-form'),catalog=node('fieldset','','routine-catalog');catalog.append(node('legend','Choose the flows that fit your business'));
 const choices:HTMLInputElement[]=[];
 for(const item of current.catalog){const card=node('article','','routine-template'),label=node('label','','routine-choice'),input=node('input');input.type='checkbox';input.value=item.id;input.checked=config.templateIds.includes(item.id);choices.push(input);label.append(input,node('span',item.title));card.append(playbookThumbnail(item.id),label,node('p',item.description),node('span',item.cadence,'routine-cadence'));const details=node('details'),summary=node('summary','See the flow'),list=node('ol');for(const step of item.steps)list.append(node('li',step));details.append(summary,list,button('Draft with Mayor',()=>hooks.ask(item.assistantPrompt)));card.append(details);catalog.append(card);}form.append(catalog);
 const settings=node('div','','routine-settings'),enableLabel=node('label','','routine-enable'),enabled=node('input');enabled.type='checkbox';enabled.checked=config.enabled;enableLabel.append(enabled,node('span','Review this playbook automatically'));settings.append(enableLabel);
 function field(label:string,input:HTMLInputElement|HTMLSelectElement){const group=node('label','','form-field');group.append(node('span',label),input);settings.append(group);return input;}
 const frequency=node('select');frequency.append(new Option('Every day','daily'),new Option('Weekdays','weekdays'));frequency.value=schedule?.frequency??'weekdays';field('Frequency',frequency);
 const time=node('input');time.type='time';time.step='300';time.required=true;time.value=`${String(schedule?.hour??9).padStart(2,'0')}:${String(schedule?.minute??0).padStart(2,'0')}`;field('Local review time',time);
 const zone=node('input');zone.maxLength=100;zone.value=schedule?.timeZone??Intl.DateTimeFormat().resolvedOptions().timeZone;zone.required=true;field('Time zone',zone);
 const preview=node('p','Choose a time in five-minute increments. Results normally appear within five minutes of the scheduled time. Clock changes follow the selected time zone.','subtle');settings.append(preview);form.append(settings);
 const actions=node('div','','routine-actions'),save=node('button','Review playbook settings','primary');save.type='submit';actions.append(save);form.append(actions);form.onsubmit=event=>{event.preventDefault();const templateIds=choices.filter(choice=>choice.checked).map(choice=>choice.value);if(!templateIds.length){status.textContent='Choose at least one business flow.';return;}const [hour,minute]=time.value.split(':').map(Number);if(!Number.isInteger(hour)||!Number.isInteger(minute)||minute%5){status.textContent='Choose a review time in five-minute increments.';return;}try{new Intl.DateTimeFormat('en',{timeZone:zone.value.trim()});}catch{status.textContent='Choose a valid time zone, such as America/New_York.';return;}const input={revision:config.revision,enabled:enabled.checked,templateIds,schedule:{frequency:frequency.value as Schedule['frequency'],hour,minute,timeZone:zone.value.trim()}};review(input,current.catalog);};
 const setup=node('details','','routine-configuration');setup.append(node('summary',config.revision?`Manage ${config.templateIds.length} saved ${config.templateIds.length===1?'flow':'flows'} & review schedule`:'Choose flows & set a daily review'),form);if(!config.revision)setup.append(node('p','Save your playbook first. Automatic reviews start only when you enable and confirm them.','subtle'));element.append(setup);
 const scope=node('details','','routine-scope');scope.append(node('summary','What this review uses'),node('p',current.scope));element.append(scope);
 }
 function review(input:{revision:number;enabled:boolean;templateIds:string[];schedule?:Schedule},catalog:Template[]){
  const dialog=node('dialog','','workday-dialog routine-review'),title=node('h2','Review your playbook'),copy=node('p',routineConfigReadback(input,catalog)),status=node('p');
  title.id='routine-review-'+crypto.randomUUID();dialog.setAttribute('aria-labelledby',title.id);status.setAttribute('role','status');
  const confirm=button('Confirm settings',()=>{confirm.disabled=true;back.disabled=true;const captured=accessEpoch;void (async()=>{try{await hooks.api(base(),input);if(captured!==accessEpoch)return;requestId=null;dialog.close();dialog.remove();hooks.onChanged?.();await load();if(data?.config.revision===input.revision+1){const heading=element.querySelector<HTMLElement>('.routines-heading h2');if(heading){heading.tabIndex=-1;heading.focus();}}}catch(error){if(captured===accessEpoch){status.textContent=error instanceof Error?error.message:'Settings could not be saved.';confirm.disabled=back.disabled=false;}}})();},'primary'),back=button('Back',()=>{dialog.close();dialog.remove();});
  dialog.append(title,copy,status,confirm,back);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();confirm.focus();
 }
 async function runNow(){if(busy||!data?.config.revision)return;busy=true;requestId??=crypto.randomUUID();const captured=accessEpoch;render();const status=element.querySelector<HTMLElement>('.routines-status')!;status.textContent='Reviewing your saved business records…';try{const result=await hooks.api(base()+'/run',{requestId});if(captured!==accessEpoch)return;requestId=null;busy=false;hooks.onChanged?.();await load();if(data?.latestBrief?.id===result.brief.id){const heading=element.querySelector<HTMLElement>('.routine-brief>h3');if(heading){heading.tabIndex=-1;heading.focus();}}}catch(error){if(captured!==accessEpoch)return;busy=false;render();failure(error);}}
 function briefView(brief:Brief){const section=node('section','','routine-brief');section.append(node('span','YOUR LATEST BUSINESS REVIEW','eyebrow'),node('h3','A clearer next step'),node('p',new Date(brief.generatedAt).toLocaleString(),'subtle'),node('p',brief.summary,'routine-brief-lead'));
 const metrics=node('div','','routine-metrics');for(const metric of brief.metrics){const card=node('div');card.append(playbookMetricIcon(metric.key),node('strong',metric.value===null?'Unknown':metric.value.toLocaleString()),node('span',metric.label));metrics.append(card);}section.append(metrics);
 const priorities=node('div','','routine-priorities');priorities.append(node('h4','Reminders from your records'));if(!brief.priorities.length)priorities.append(node('p','No open reminders were found in the records checked.'));for(const item of brief.priorities){const card=node('article');card.append(node('h4',item.title),node('p',item.detail));if(item.assistantPrompt)card.append(button('Work through this with Mayor',()=>hooks.ask(item.assistantPrompt!)));priorities.append(card);}section.append(priorities);
 const suggestions=node('div','','routine-suggestions');suggestions.append(node('h4','Opportunities to explore'));for(const item of brief.suggestions){const card=node('article');card.append(playbookTemplateIcon(data?.catalog.find(template=>template.title===item.title)?.id??''),node('span','SUGGESTED NEXT STEP','eyebrow'),node('h4',item.title),node('p',item.detail),button('Prepare a draft with Mayor',()=>hooks.ask(item.assistantPrompt)));suggestions.append(card);}section.append(suggestions);
 if(brief.gaps.length){const gaps=node('details'),summary=node('summary','What Mayor still needs to learn'),list=node('ul');brief.gaps.forEach(gap=>list.append(node('li',gap)));gaps.append(summary,list);section.append(gaps);}section.append(node('p',brief.scope,'routine-scope'));section.append(button('Mark this review read',()=>{const captured=accessEpoch;void hooks.api(base()+'/brief/read',{id:brief.id}).then(()=>{if(captured===accessEpoch){hooks.onChanged?.();const status=element.querySelector<HTMLElement>('.routines-status');if(status)status.textContent='Review marked read.';}}).catch(error=>{if(captured===accessEpoch)failure(error);});}));element.append(section);
 }
 return {element,load,clear(){version++;accessEpoch++;data=null;requestId=null;busy=false;element.replaceChildren();document.querySelectorAll<HTMLDialogElement>('.routine-review').forEach(dialog=>{dialog.close();dialog.remove();});}};
}
