import {createIcons,House,Sparkles,CalendarDays,Users,ListTodo,CreditCard,Settings,CircleHelp,Store,Bell,Mic,ArrowUp,ArrowRight,ChevronRight,Plus,Check,Clock,RefreshCw,Copy,X,Search,Phone,CalendarCheck,Menu,Plug} from 'lucide';
import {createBusinessRoutines} from './business-routines';
import {createBusinessAgent} from './business-agent';
import './credit-packs.css';

export type WorkdayView='today'|'chat'|'appointments'|'customers'|'tasks'|'billing'|'connections'|'account'|'help';
type Api=(path:string,body?:unknown,headers?:Record<string,string>)=>Promise<any>;
type Hooks={api:Api;tenant:()=>string;actor:()=>string;canManage:()=>boolean;canChat:()=>boolean;onNavigate:(view:WorkdayView)=>void;ask:(text:string)=>void;onNotice:(message:string)=>void;onSignIn:()=>void;onChanged?:()=>void};
type Appointment={id:string;input:{title:string;appointmentType:string;staff?:string;start:string;end:string;attendees:string[]};status:string;customer?:{id:string;name:string}|null;pendingChangeId?:string|null;canCheck?:boolean};
type Customer={id:string;name:string;email?:string|null;phone?:string|null;revision:number};
type Task={id:string;title:string;dueAt:string|null;priority:string;status:'open'|'completed';revision:number;customer?:{id:string;name:string}|null};
const views:WorkdayView[]=['today','chat','appointments','customers','tasks','billing','connections','account','help'];
const icons={House,Sparkles,CalendarDays,Users,ListTodo,CreditCard,Settings,CircleHelp,Store,Bell,Mic,ArrowUp,ArrowRight,ChevronRight,Plus,Check,Clock,RefreshCw,Copy,X,Search,Phone,CalendarCheck,Menu,Plug};
const $=(id:string)=>document.getElementById(id)!;
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''):HTMLElementTagNameMap[K]{const node=document.createElement(tag);node.textContent=text;node.className=className;return node;}
function icon(name:string){const node=el('i');node.dataset.lucide=name;node.setAttribute('aria-hidden','true');return node;}
function button(label:string,action:()=>void,className='secondary'){const node=el('button',label,className);node.type='button';node.onclick=action;return node;}
function empty(title:string,detail:string,action?:HTMLElement){const node=el('div','','empty-state');node.append(el('h3',title),el('p',detail));if(action)node.append(action);return node;}
function field(form:HTMLElement,label:string,name:string,type='text',value=''){const wrapper=el('label','','form-field');wrapper.append(el('span',label));const input=el('input');input.name=name;input.type=type;input.value=value;input.maxLength=type==='email'?254:200;wrapper.append(input);form.append(wrapper);return input;}
function select(form:HTMLElement,label:string,name:string,choices:{value:string;label:string}[],value=''){const wrapper=el('label','','form-field');wrapper.append(el('span',label));const input=el('select');input.name=name;for(const choice of choices){const option=el('option',choice.label);option.value=choice.value;input.append(option);}input.value=value;wrapper.append(input);form.append(wrapper);return input;}
function dateInZone(timeZone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=(name:string)=>parts.find(p=>p.type===name)!.value;return `${part('year')}-${part('month')}-${part('day')}`;}

export function createWorkday(hooks:Hooks){
 let current:WorkdayView='today',timeZone='UTC',businessDate=dateInZone('UTC'),appointmentDate='',ready=false,workspaceRole='',loadVersion=0;
 let taskVersion=0,customerVersion=0,agendaVersion=0,billingVersion=0;
 let accessVersion=0;const originalApi=hooks.api;
 hooks={...hooks,api:async(path,body,headers)=>{const version=accessVersion;if(!ready)throw new Error('Your workspace access has ended.');const result=await originalApi(path,body,headers);if(version!==accessVersion||!ready)throw new Error('Your workspace access has ended.');return result;}};
 let customerQuery='',customerCursor:string|null=null,taskCursor:string|null=null,agendaCursor:string|null=null,taskStatus='open';
 let customerRows:Customer[]=[],taskRows:Task[]=[],agendaRows:Appointment[]=[];
 const base=()=>`/api/businesses/${hooks.tenant()}`;
 const routines=createBusinessRoutines({api:hooks.api,tenant:hooks.tenant,ask:hooks.ask,onChanged:hooks.onChanged});$('tasks-content').after(routines.element);
 const businessAgent=createBusinessAgent({api:hooks.api,tenant:hooks.tenant,actor:hooks.actor,ask:hooks.ask,onChanged:()=>{hooks.onChanged?.();void refreshOverview(false);}});
 const dateLabel=(date:string)=>new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
 const time=(value:string)=>new Intl.DateTimeFormat(undefined,{timeZone,hour:'numeric',minute:'2-digit'}).format(new Date(value));
 const fullTime=(value:string)=>new Intl.DateTimeFormat(undefined,{timeZone,dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
 $('workday-date').textContent=dateLabel(businessDate);
 function paintIcons(){createIcons({icons,attrs:{'stroke-width':1.7,'aria-hidden':'true'}});}
 function error(target:HTMLElement,reason:unknown,retry:()=>void){target.replaceChildren(empty('Could not load this view.',reason instanceof Error?reason.message:'Please try again.',button('Try again',retry)));}
 function guarded(action:()=>Promise<void>,target?:HTMLElement){return async()=>{if(!ready)return;try{await action();}catch(reason){if(!ready)return;const message=reason instanceof Error?reason.message:'This action could not finish. Please try again.';if(target){target.textContent=message;target.setAttribute('role','alert');}else hooks.onNotice(message);}};}
 function toolbar(target:HTMLElement,description:string,actions:HTMLElement[]){const bar=el('div','','view-toolbar');bar.append(el('p',description,'subtle'));const right=el('div','','toolbar-actions');right.append(...actions);bar.append(right);target.append(bar);}
 function loading(view:WorkdayView){const target=$(`${view}-content`);target.replaceChildren(el('p','Loading your business…','loading-state'));return target;}
 function pagedMore(target:HTMLElement,cursor:string|null,load:()=>void){if(cursor)target.append(button('Load more',load,'secondary load-more'));}
 async function refreshOverview(loadAgent=true){
  if(!ready||!hooks.canManage())return;
  const version=++loadVersion,target=$('today-content'),existing=Boolean(target.querySelector('.today-grid'));if(!existing)loading('today');
  try{const data=await hooks.api(base()+'/overview');if(version!==loadVersion)return;
   timeZone=data.business.timeZone;businessDate=data.date??dateInZone(timeZone);if(!appointmentDate)appointmentDate=businessDate;
   $('business-name').textContent=data.business.name;$('business-name').title=data.business.name;$('workday-date').textContent=`${dateLabel(businessDate)} · ${timeZone}`;
   $('calendar-status').querySelector('span')!.textContent=data.setup.calendarConnected?'Calendar connected':'Connect calendar';
   if(!existing)target.replaceChildren();const grid=el('div','','today-grid'),attention=el('section','','attention-section'),agenda=el('section','','agenda-preview');
   const heading=el('div','','section-heading');heading.append(el('h2','Needs your attention'),el('span',String(data.attention.length),'count-badge'));attention.append(heading);
   if(!data.attention.length)attention.append(empty('You’re all caught up.','No setup items, overdue tasks, or open alerts need your attention.',button('Add a task',()=>hooks.onNavigate('tasks'),'quiet')));
   for(const item of data.attention){const row=el('article','','attention-row'),mark=el('span','','attention-icon');mark.append(icon(item.kind==='callback'||item.kind==='missed_call'?'phone':item.kind==='task'?'list-todo':item.kind==='notification'?'bell':item.kind==='appointment_review'?'calendar-days':'sparkles'));
    const text=el('div','','row-copy');text.append(el('h3',item.title),el('p',item.detail));const link=button(item.action==='chat'?'Continue setup':item.action==='account'?'Connect calendar':item.action==='tasks'?'View tasks':item.action==='callbacks'?'View callbacks':item.action==='notifications'?'Review alerts':item.action==='missed-calls'?'Review missed calls':'Review requests',()=>{if(item.action==='chat')hooks.ask(item.detail);else if(item.action==='notifications')$('notifications-button').click();else if(item.action==='missed-calls')void missedCallsDialog();else hooks.onNavigate(item.action==='account'?'connections':item.action==='tasks'||item.action==='callbacks'?'tasks':'appointments');},'quiet row-action');link.append(icon('chevron-right'));row.append(mark,text,link);attention.append(row);
   }
   const agendaHeading=el('div','','section-heading');agendaHeading.append(el('h2','Up next'),button('View all',()=>hooks.onNavigate('appointments'),'quiet'));agenda.append(agendaHeading);
   if(!data.appointments.length){const blank=el('div','','agenda-empty');blank.append(el('p','No upcoming Mayor bookings today.'),button('New appointment',()=>hooks.onNavigate('appointments'),'quiet'));agenda.append(blank);}
   for(const item of data.appointments as Appointment[])agenda.append(appointmentPreview(item));
   agenda.append(el('p','Mayor bookings only · '+timeZone,'source-note'));grid.append(attention,agenda);const oldGrid=target.querySelector('.today-grid');if(oldGrid)oldGrid.replaceWith(grid);else target.append(grid);
   const taskSection=el('section','','today-tasks');const taskHeading=el('div','','section-heading');taskHeading.append(el('h2','Your next steps'),button(`View tasks (${data.counts.tasksOpen})`,()=>hooks.onNavigate('tasks'),'quiet'));taskSection.append(taskHeading);
   if(data.tasks.length){for(const task of data.tasks as Task[])taskSection.append(taskRow(task));}else taskSection.append(el('p','Your shared task list is clear. Add a next step whenever you need it.','subtle'));
   if(grid.nextSibling!==businessAgent.element)grid.after(businessAgent.element);const oldTasks=target.querySelector('.today-tasks');if(oldTasks)oldTasks.replaceWith(taskSection);else target.append(taskSection);paintIcons();if(loadAgent)await businessAgent.load();
  }catch(reason){if(version===loadVersion){if(existing)hooks.onNotice(reason instanceof Error?reason.message:'Today could not refresh.');else error(target,reason,()=>void refreshOverview());}}
 }
 function appointmentPreview(item:Appointment){const row=el('article','','appointment-preview'),clock=el('div','','appointment-clock');clock.append(el('strong',time(item.input.start)),el('small',time(item.input.end)));const copy=el('div','','row-copy');copy.append(el('h3',item.customer?.name??item.input.title),el('p',item.input.appointmentType+(item.input.staff?' · '+item.input.staff:'')));row.append(clock,copy);return row;}
 function taskRow(task:Task){const row=el('article','','task-row');const toggle=button('',guarded(async()=>{toggle.disabled=true;try{await hooks.api(base()+'/tasks/'+task.id,{revision:task.revision,status:task.status==='open'?'completed':'open'});await (current==='today'?refreshOverview():loadTasks());}finally{toggle.disabled=false;}}),'task-toggle');toggle.setAttribute('aria-label',`${task.status==='completed'?'Reopen':'Complete'} ${task.title}`);toggle.setAttribute('aria-pressed',String(task.status==='completed'));if(task.status==='completed')toggle.append(icon('check'));
  const copy=el('div','','row-copy');copy.append(el('h3',task.title),el('p',[task.dueAt?fullTime(task.dueAt):'No due date',task.priority==='high'?'High priority':'',task.customer?.name??''].filter(Boolean).join(' · ')));row.append(toggle,copy,button('Edit',()=>taskDialog(task),'quiet'));return row;}
 function dialog(title:string){const node=el('dialog','','workday-dialog');node.setAttribute('aria-label',title);const head=el('div','','dialog-heading'),close=button('',()=>node.close(),'icon-button');close.setAttribute('aria-label','Close');close.append(icon('x'));head.append(el('h2',title),close);node.append(head);document.body.append(node);node.addEventListener('close',()=>node.remove());node.addEventListener('click',event=>{if(event.target===node){const box=node.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)node.close();}});node.showModal();paintIcons();return node;}
 function formActions(form:HTMLFormElement,label:string){const actions=el('div','','form-actions'),status=el('p','','form-status');status.setAttribute('role','status');const submit=el('button',label,'primary');submit.type='submit';actions.append(submit);form.append(status,actions);return {submit,status,actions};}
 function localInputDate(iso:string){const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 function taskDialog(task?:Task){
  const node=dialog(task?'Edit task':'Add a next step'),form=el('form');node.append(form);const title=field(form,'What needs doing?','title','text',task?.title??'');title.required=true;title.maxLength=200;
  const due=field(form,'Due time (your device timezone)','due','datetime-local',task?.dueAt?localInputDate(task.dueAt):'');const priority=select(form,'Priority','priority',[{value:'normal',label:'Normal'},{value:'high',label:'High'},{value:'low',label:'Low'}],task?.priority??'normal');const linkedCustomer=customerPicker(form,task?.customer??undefined);const {submit,status}=formActions(form,task?'Save task':'Add task');const requestId=crypto.randomUUID();
  form.onsubmit=event=>{event.preventDefault();submit.disabled=true;void guarded(async()=>{try{const body={title:title.value.trim(),dueAt:due.value?new Date(due.value).toISOString():null,priority:priority.value,customerId:linkedCustomer.value||null,...(task?{revision:task.revision}:{requestId})};await hooks.api(base()+'/tasks'+(task?'/'+task.id:''),body);node.close();await (current==='today'?refreshOverview():loadTasks());}finally{submit.disabled=false;}},status)();};title.focus();
 }
 async function loadTasks(more=false){
  if(!ready||!hooks.canManage())return;const version=++taskVersion;
  const target=more?$('tasks-content'):loading('tasks');
  try{const query=new URLSearchParams({status:taskStatus,limit:'25'});if(more&&taskCursor)query.set('cursor',taskCursor);const [data,callbacks]=await Promise.all([hooks.api(base()+'/tasks?'+query),hooks.api(base()+'/callbacks?limit=25')]);if(version!==taskVersion||!ready)return;if(!more)taskRows=[];taskRows.push(...data.tasks);taskCursor=data.nextCursor;target.replaceChildren();
   const filter=select(el('div'),'Show','task-status',[{value:'open',label:'Open tasks'},{value:'completed',label:'Completed'},{value:'all',label:'All tasks'}],taskStatus);filter.setAttribute('aria-label','Filter tasks');filter.onchange=()=>{taskStatus=filter.value;void loadTasks();};toolbar(target,`${data.counts.open} open · ${data.counts.completed} completed`,[filter,button('Add task',()=>taskDialog(),'primary')]);
   if(!taskRows.length)target.append(empty('A little breathing room.','Add a task to keep your next step in view.'));else{const list=el('div','','record-list');for(const task of taskRows)list.append(taskRow(task));target.append(list);}pagedMore(target,taskCursor,()=>void loadTasks(true));
   const section=el('section','','callback-section');section.append(el('h2',`Callbacks (${callbacks.total})`),el('p','Return contacts are unverified. Follow up using your business phone, then mark the request handled.','subtle'));
   for(const callback of callbacks.callbacks){const row=el('article','','record-row'),copy=el('div','','row-copy');copy.append(el('h3',callback.number??'No return number'),el('p',(callback.reason==='scheduling'?'Scheduling request':'Human assistance')+' · '+fullTime(callback.createdAt)));row.append(copy,button('Mark handled',()=>confirmSimple('Mark callback handled?','Confirm that you have followed up with this request.',async()=>{await hooks.api(base()+'/callbacks/'+callback.id+'/handled',{confirm:true});await loadTasks();}),'secondary'));section.append(row);}if(!callbacks.callbacks.length)section.append(el('p','No pending callbacks.','subtle'));if(callbacks.hasMore)section.append(button('Load more callbacks',()=>void callbackDialog(),'secondary'));target.append(section);paintIcons();
  }catch(reason){if(version===taskVersion&&ready)error(target,reason,()=>void loadTasks());}
 }
 async function callbackDialog(){const node=dialog('Pending callbacks'),list=el('div');node.append(list);let cursor:string|null=null;const load=async()=>{const data=await hooks.api(base()+'/callbacks?limit=50'+(cursor?'&cursor='+encodeURIComponent(cursor):''));for(const item of data.callbacks){const row=el('article','','record-row');row.append(el('p',`${item.number} · ${item.reason} · ${fullTime(item.createdAt)}`),button('Mark handled',()=>confirmSimple('Mark callback handled?','Confirm that you have followed up.',async()=>{await hooks.api(base()+'/callbacks/'+item.id+'/handled',{confirm:true});row.remove();})));list.append(row);}cursor=data.nextCursor;more.hidden=!cursor;};const more=button('Load more',guarded(load));node.append(more);await guarded(load)();}
 type MissedCall={id:string;caller_number:string;source?:string;occurred_at:string;textback_sent_at:string|null;reply_received_at:string|null;booking_id:string|null;status:string};
 async function missedCallsDialog(){
  const node=dialog('Missed calls'),target=el('div');node.append(target);
  const load=async()=>{
   target.replaceChildren(el('p','Loading missed calls…','loading-state'));
   const data=await hooks.api(base()+'/missed-calls');
   const calls=(data.missedCalls??[]) as MissedCall[];
   target.replaceChildren();
   if(!calls.length){target.append(empty('No missed calls yet.','Simulate one from the Business phone card in Account to watch the money loop here.'));return;}
   target.append(el('p','Test calls only simulate the text-back — no real message is ever sent from a simulation.','source-note'));
   const list=el('div','','record-list');
   for(const call of calls){
    const row=el('article','','record-row'),copy=el('div','','row-copy'),state=el('p','','subtle');
    copy.append(el('h3',call.caller_number),el('p',fullTime(call.occurred_at)+' · '+call.status+(call.source==='test'?' · test call':'')));
    state.textContent=call.textback_sent_at?'Text-back sent '+fullTime(call.textback_sent_at)+(call.reply_received_at?' · customer replied':''):'Waiting for a text-back';
    copy.append(state);
    const action=el('span');
    if(call.textback_sent_at)action.append(el('span','Texted','status-tag'));
    else{
     const test=call.source==='test';
     const send=button(test?'Simulate text-back':'Send text-back',guarded(async()=>{send.disabled=true;try{
      await hooks.api(base()+(test?`/phone/test-missed-call/${call.id}/text-back`:`/missed-calls/${call.id}/text-back`),{});
      hooks.onNotice(test?'Simulated text-back recorded. Check Notifications.':'Text-back sent.');
      await load();}finally{send.disabled=false;}},'secondary'));
     action.append(send);
    }
    row.append(copy,action);list.append(row);
   }
   target.append(list);
  };
  await guarded(load,target)();
  paintIcons();
 }
 async function loadCustomers(more=false){
  if(!ready||!hooks.canManage())return;const version=++customerVersion;
  const target=more?$('customers-content'):loading('customers');try{const query=new URLSearchParams({q:customerQuery,limit:'25'});if(more&&customerCursor)query.set('cursor',customerCursor);const data=await hooks.api(base()+'/customers?'+query);if(version!==customerVersion||!ready)return;if(!more)customerRows=[];customerRows.push(...data.customers);customerCursor=data.nextCursor;target.replaceChildren();
   const searchForm=el('form','','search-form'),search=el('input');search.type='search';search.placeholder='Search name, email, or phone';search.setAttribute('aria-label','Search customers');search.value=customerQuery;search.maxLength=160;const submit=el('button','Search','secondary');submit.type='submit';searchForm.append(search,submit);searchForm.onsubmit=event=>{event.preventDefault();customerQuery=search.value.trim();void loadCustomers();};toolbar(target,`${data.total} ${data.total===1?'customer':'customers'}${customerQuery?' in this search':''}`,[button('Add customer',()=>customerDialog(),'primary')]);target.append(searchForm);
   if(!customerRows.length)target.append(empty(customerQuery?'No matching customers.':'Your people, in one place.',customerQuery?'Try a different name, email, or phone number.':'Add a customer to connect their details and bookings.'));else{const list=el('div','','record-list');for(const customer of customerRows){const row=el('article','','record-row'),copy=el('div','','row-copy');copy.append(el('h3',customer.name),el('p',[customer.email,customer.phone].filter(Boolean).join(' · ')||'No contact details'));row.append(copy,button('View customer',()=>void customerDetails(customer),'quiet'));list.append(row);}target.append(list);}pagedMore(target,customerCursor,()=>void loadCustomers(true));paintIcons();
  }catch(reason){if(version===customerVersion&&ready)error(target,reason,()=>void loadCustomers());}
 }
 function customerDialog(customer?:Customer){
  const node=dialog(customer?'Edit customer':'Add customer'),form=el('form');node.append(form);const name=field(form,'Name','name','text',customer?.name??'');name.required=true;name.maxLength=160;const email=field(form,'Email (optional)','email','email',customer?.email??'');const phone=field(form,'Phone (optional, international format)','phone','tel',customer?.phone??'');phone.placeholder='+12125550123';phone.maxLength=20;const {submit,status}=formActions(form,'Review details');
  form.onsubmit=event=>{event.preventDefault();submit.disabled=true;void guarded(async()=>{try{const body={...(customer?{id:customer.id}:{}),name:name.value.trim(),...(email.value.trim()?{email:email.value.trim()}:customer?.email?{email:null}:{}),...(phone.value.trim()?{phone:phone.value.trim()}:customer?.phone?{phone:null}:{})};const {proposal}=await hooks.api(base()+'/customers/prepare',body);reviewProposal(node,proposal,'Save customer',async()=>{await hooks.api(base()+'/customers/confirm',{id:proposal.id,confirm:true});node.close();await loadCustomers();},()=>{node.replaceChildren(form);submit.disabled=false;});}finally{submit.disabled=false;}},status)();};name.focus();
 }
 async function customerDetails(customer:Customer){const node=dialog(customer.name),target=el('div');node.append(target);await guarded(async()=>{const {customer:latest}=await hooks.api(base()+'/customers/'+customer.id);target.append(el('p',[latest.email,latest.phone].filter(Boolean).join(' · ')||'No contact details'),el('p','Contact details are a saved record, not proof of a caller’s identity.','subtle'));const actions=el('div','','form-actions');actions.append(button('Book appointment',()=>{node.close();hooks.onNavigate('appointments');void bookingDialog(latest);}),button('Edit customer',()=>{node.close();customerDialog(latest);}),button('Draft follow-up',()=>{node.close();hooks.ask(`Help me draft a follow-up for ${latest.name}. Ask me about the context before drafting. Do not send it.`);}));target.append(actions);
   // Each stable, independently paginated window stays below the API's 93-day bound.
   const now=Date.now(),boundary=new Date(now).toISOString(),span=90*86400000;
   function bookingWindow(title:string,scope:string,start:string,end:string,kind:string){
    const section=el('section'),heading=el('h3',title),list=el('div'),source=el('p',scope+' · Mayor bookings only · '+timeZone,'source-note'),status=el('p','Loading bookings…','source-note');heading.id='customer-bookings-'+crypto.randomUUID();section.setAttribute('aria-labelledby',heading.id);status.setAttribute('role','status');section.append(heading,source,list,status);target.append(section);
    let cursor:string|null=null,loaded=0;const more=button('Load more '+kind,()=>void load());more.hidden=true;section.append(more);
    const load=guarded(async()=>{more.disabled=true;try{
     const query=new URLSearchParams({customerId:customer.id,start,end,limit:'25'});if(cursor)query.set('cursor',cursor);const data=await hooks.api(base()+'/agenda?'+query);timeZone=data.timeZone;source.textContent=scope+' · Mayor bookings only · '+timeZone;
     if(!data.total&&!loaded)list.append(el('p','No Mayor bookings overlap this window.','subtle'));
     for(const appointment of data.appointments as Appointment[]){const row=el('div','','record-row');row.append(el('p',`${appointment.input.title} · ${fullTime(appointment.input.start)} · ${appointment.status}`));list.append(row);}
     loaded+=data.appointments.length;cursor=data.nextCursor;more.hidden=!cursor;more.textContent='Load more '+kind;status.setAttribute('role','status');status.textContent=`Showing ${loaded} of ${data.total} bookings in this window.`;
    }catch(reason){more.hidden=false;more.textContent='Try again';throw reason;}finally{more.disabled=false;}},status);
    return load;
   }
   const upcoming=bookingWindow('Upcoming bookings','Next 90 days, including appointments underway',boundary,new Date(now+span).toISOString(),'upcoming bookings');
   const history=bookingWindow('Recent bookings','Previous 90 days, including appointments underway',new Date(now-span).toISOString(),boundary,'recent bookings');
   await Promise.all([upcoming(),history()]);},target)();}
 function reviewProposal(node:HTMLDialogElement,proposal:any,label:string,confirm:()=>Promise<void>,back:()=>void){const head=node.querySelector<HTMLElement>('.dialog-heading'),heading=head?.querySelector('h2'),originalTitle=heading?.textContent??'';if(heading)heading.textContent='Review before confirming';node.replaceChildren(head??el('h2','Review before confirming'),el('p',typeof proposal.readback==='string'?proposal.readback:JSON.stringify(proposal.input??proposal.profile,null,2),'proposal-readback'));node.append(el('p',`This review expires ${fullTime(proposal.expiresAt)} (${timeZone}). Confirm only if the details are correct.`,'subtle'));const status=el('p','','form-status');status.setAttribute('role','status');const actions=el('div','','form-actions'),yes=button(label,()=>{yes.disabled=true;no.disabled=true;void guarded(async()=>{try{await confirm();}finally{yes.disabled=false;no.disabled=false;}},status)();},'primary'),no=button('Back',()=>{back();if(head)node.prepend(head);if(heading)heading.textContent=originalTitle;node.querySelector<HTMLElement>('form input,form select,form button')?.focus();});actions.append(no,yes);node.append(status,actions);yes.focus();}
 function confirmSimple(title:string,detail:string,action:()=>Promise<void>){const node=dialog(title);node.append(el('p',detail));const status=el('p','','form-status'),yes=button('Confirm',()=>{yes.disabled=true;void guarded(async()=>{try{await action();node.close();}finally{yes.disabled=false;}},status)();},'primary');node.append(status,yes);}
 async function loadAgenda(more=false){
  if(!ready||!hooks.canManage())return;const version=++agendaVersion;
  const target=more?$('appointments-content'):loading('appointments');try{const query=new URLSearchParams({date:appointmentDate||businessDate,limit:'25'});if(more&&agendaCursor)query.set('cursor',agendaCursor);const data=await hooks.api(base()+'/agenda?'+query);if(version!==agendaVersion||!ready)return;timeZone=data.timeZone;if(!more)agendaRows=[];agendaRows.push(...data.appointments);agendaCursor=data.nextCursor;target.replaceChildren();const date=el('input');date.type='date';date.value=appointmentDate||businessDate;date.setAttribute('aria-label','Appointment date in business timezone');date.onchange=()=>{if(date.value){appointmentDate=date.value;void loadAgenda();}};
   toolbar(target,`${data.total} ${data.total===1?'appointment':'appointments'} · ${timeZone}`,[date,button('New appointment',()=>void bookingDialog(),'primary')]);target.append(el('p',data.source.scope,'source-note'));
   if(!agendaRows.length)target.append(empty('Nothing booked for this day.','Choose another date or add an appointment.'));else{const list=el('div','','record-list');for(const appointment of agendaRows){const row=el('article','','record-row'),copy=el('div','','row-copy');copy.append(el('h3',appointment.input.title),el('p',`${time(appointment.input.start)}–${time(appointment.input.end)} · ${appointment.input.appointmentType}${appointment.customer?' · '+appointment.customer.name:''}`),el('span',appointment.status==='confirmed'?'Confirmed':appointment.status==='cancelled'?'Cancelled':'Needs review','status-tag'));const actions=el('div','','toolbar-actions');if(appointment.status==='confirmed')actions.append(button('Reschedule',()=>changeDialog(appointment,'reschedule'),'quiet'),button('Cancel',()=>changeDialog(appointment,'cancel'),'quiet'));if(['running','uncertain'].includes(appointment.status)&&appointment.pendingChangeId&&appointment.canCheck)actions.append(button('Check result',guarded(async()=>{const result=await hooks.api(base()+'/appointment-changes/reconcile',{id:appointment.pendingChangeId});hooks.onNotice(`Calendar request: ${result.result.status}.`);await loadAgenda();})));row.append(copy,actions);list.append(row);}target.append(list);}pagedMore(target,agendaCursor,()=>void loadAgenda(true));target.append(button('Review pending requests',()=>void requestsDialog(),'secondary'));paintIcons();
  }catch(reason){if(version===agendaVersion&&ready)error(target,reason,()=>void loadAgenda());}
 }
 async function requestsDialog(){const node=dialog('Calendar requests'),target=el('div');node.append(target);await guarded(async()=>{const data=await hooks.api(base()+'/bookings');const items=Array.isArray(data)?data:data.requests??data.bookings??[];if(!items.length)target.append(el('p','No recent booking requests.'));for(const item of items){const row=el('article','','record-row');row.append(el('p',`${item.input.title} · ${fullTime(item.input.start)} · ${item.status}`));if(['running','uncertain'].includes(item.status))row.append(button('Check result',guarded(async()=>{const result=await hooks.api(base()+'/bookings/'+item.id+'/check',{});hooks.onNotice(`Booking request: ${result.status}.`);node.close();await loadAgenda();})));target.append(row);}target.append(el('p','Your most recent 20 booking requests. An uncertain result needs checking before another booking is created.','subtle'));},target)();}
 function customerPicker(form:HTMLFormElement,preset?:Pick<Customer,'id'|'name'>){
  const group=el('fieldset','','booking-customer');group.append(el('legend','Link a saved customer (optional)'));form.append(group);const query=field(group,'Search saved customers','customer-search','search',preset?.name??'');query.maxLength=160;
  const choice=select(group,'Customer record','customer-id',[{value:'',label:'No linked customer'},...(preset?[{value:preset.id,label:preset.name}]:[])],preset?.id??'');const status=el('p','Linking a customer does not send an invitation. Choose “No linked customer” to clear a link.','subtle');status.setAttribute('role','status');const find=button('Find customer',()=>{find.disabled=true;void guarded(async()=>{try{const data=await hooks.api(base()+'/customers?'+new URLSearchParams({q:query.value.trim(),limit:'25'}));const selected=choice.value,selectedName=choice.selectedOptions[0]?.textContent??'';const matches=data.customers as Customer[],retained=selected&&!matches.some(item=>item.id===selected)?[{id:selected,name:selectedName}]:[];choice.replaceChildren();for(const item of [{id:'',name:'No linked customer'},...retained,...matches]){const option=el('option',item.name);option.value=item.id;choice.append(option);}choice.value=selected;status.setAttribute('role','status');status.textContent=(data.hasMore?'Showing 25 matches. Narrow the search to find the right customer.':`${data.total} matching customer records.`)+(retained.length?' Your selected customer remains linked.':'')+' Linking does not send an invitation.';}finally{find.disabled=false;}},status)();});query.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();if(!find.disabled)find.click();}};group.append(find,status);return choice;
 }
 async function bookingDialog(presetCustomer?:Customer){
  const node=dialog('New appointment'),form=el('form');node.append(form);await guarded(async()=>{const data=await hooks.api(base()+'/scheduling-policy');const policy=data.policy;if(!policy){form.append(empty('Finish your booking setup.','Confirm services, hours, timezone, and calendar before creating appointments.',button('Set up with Assistant',()=>{node.close();hooks.ask('Help me finish my scheduling setup.');})));return;}
   form.append(el('p',`Times are entered in your device timezone and reviewed in ${policy.timeZone}. The calendar is checked before confirmation.`,'subtle'));
   const title=field(form,'Appointment title','title');title.required=true;const type=select(form,'Service','appointmentType',policy.appointmentTypes.map((item:any)=>({value:item.name,label:`${item.name} · ${item.durationMinutes} min`})),policy.appointmentTypes[0]?.name??'');const staff=policy.staff.length?select(form,'Staff','staff',policy.staff.map((item:any)=>({value:item.name,label:item.name})),policy.staff[0]?.name??''):null;
   const start=field(form,'Starts (device timezone)','start','datetime-local');start.required=true;const end=field(form,'Ends (device timezone)','end','datetime-local');end.required=true;const attendee=field(form,'Invitation email (optional)','attendee','email');const linkedCustomer=await customerPicker(form,presetCustomer);const {submit,status,actions}=formActions(form,'Review appointment');
   const find=button('Find openings',()=>{find.disabled=true;void guarded(async()=>{try{if(!start.value)throw new Error('Choose a start time to search the next 24 hours.');const result=await hooks.api(base()+'/availability',{start:new Date(start.value).toISOString(),end:new Date(new Date(start.value).getTime()+86400000).toISOString(),appointmentType:type.value,...(staff?{staff:staff.value}:{}),limit:5});openings.replaceChildren();for(const slot of result.openings??result.slots??[]){openings.append(button(`${fullTime(slot.start)}–${time(slot.end)}`,()=>{start.value=localInputDate(slot.start);end.value=localInputDate(slot.end);}));}if(!openings.children.length)openings.append(el('p','No openings returned in this window. Try another starting time.'));}finally{find.disabled=false;}},status)();});actions.prepend(find);const openings=el('div','','openings');form.append(openings);
   form.onsubmit=event=>{event.preventDefault();submit.disabled=true;void guarded(async()=>{try{const body={title:title.value.trim(),appointmentType:type.value,...(staff?{staff:staff.value}:{}),start:new Date(start.value).toISOString(),end:new Date(end.value).toISOString(),attendees:attendee.value.trim()?[attendee.value.trim()]:[],...(linkedCustomer.value?{customerId:linkedCustomer.value}:{})};const {proposal}=await hooks.api(base()+'/appointments/propose',body);reviewProposal(node,proposal,'Confirm booking',async()=>{const {result}=await hooks.api(base()+'/appointments/confirm',{id:proposal.id,confirm:true});if(result.status!=='applied')throw new Error(result.status==='uncertain'?'The calendar result is uncertain. Close this review and check Calendar requests before booking again.':`The appointment was not confirmed (${result.status}). Close this review and choose another time.`);node.close();await loadAgenda();},()=>{node.replaceChildren(form);});}finally{submit.disabled=false;}},status)();};title.focus();
  },form)();
 }
 function changeDialog(appointment:Appointment,kind:'cancel'|'reschedule'){
  const node=dialog(kind==='cancel'?'Cancel appointment':'Reschedule appointment'),form=el('form');node.append(form);form.append(el('p',`${appointment.input.title} · ${fullTime(appointment.input.start)}`));let start:HTMLInputElement|undefined,end:HTMLInputElement|undefined;
  if(kind==='reschedule'){start=field(form,'New start (device timezone)','start','datetime-local',localInputDate(appointment.input.start));end=field(form,'New end (device timezone)','end','datetime-local',localInputDate(appointment.input.end));start.required=end.required=true;form.append(el('p',`Review uses your business timezone: ${timeZone}.`,'subtle'));}
  const {submit,status}=formActions(form,'Review change');form.onsubmit=event=>{event.preventDefault();submit.disabled=true;void guarded(async()=>{try{const {proposal}=await hooks.api(base()+'/appointment-changes/propose',{kind,appointmentId:appointment.id,...(kind==='reschedule'?{start:new Date(start!.value).toISOString(),end:new Date(end!.value).toISOString()}:{})});reviewProposal(node,proposal,kind==='cancel'?'Confirm cancellation':'Confirm reschedule',async()=>{const {result}=await hooks.api(base()+'/appointment-changes/confirm',{id:proposal.id,confirm:true});if(result.status!=='applied')throw new Error(`Calendar change: ${result.status}. Close this review and check its result before submitting another change.`);node.close();await loadAgenda();},()=>node.replaceChildren(form));}finally{submit.disabled=false;}},status)();};
 }
 async function loadBilling(sync=false){
  if(!ready)return;const version=++billingVersion;
  const target=loading('billing');try{let data=await hooks.api(base()+'/billing');if(sync&&data.permissions.canManage){await hooks.api(base()+'/billing/sync',{}, {'Idempotency-Key':crypto.randomUUID()});data=await hooks.api(base()+'/billing');}if(version!==billingVersion||!ready)return;target.replaceChildren();toolbar(target,`${data.plan.name} · ${data.plan.status}`, [button('Refresh payment status',()=>void loadBilling(true),'secondary')]);
   const usage=el('section','','usage-panel');usage.append(el('h2','Your business allowance'),el('p','Shared across this business. Usage resets '+fullTime(data.usage.resetAt)+'.','subtle'));
   for(const [label,item] of [['Assistant replies',data.usage.replies],['Microphone minutes',data.usage.voiceMinutes]] as [string,{used:number;limit:number;remaining:number}][]){const row=el('div','','usage-row'),progress=el('progress');progress.max=item.limit;progress.value=item.used;progress.setAttribute('aria-label',label);row.append(el('strong',label),el('span',`${Math.round(item.used*10)/10} / ${item.limit}`),progress);usage.append(row);}target.append(usage);
   if(data.credits&&Array.isArray(data.creditPacks)){
    const credits=el('section','','credit-packs');credits.append(el('span','A LITTLE EXTRA, WHEN YOU NEED IT','eyebrow'),el('h2','One-time usage packs'),el('p',`Add to this business’s current allowance until ${fullTime(data.credits.expiresAt)}. Unused packs expire when this usage period ends or you change between Free and Pro. They do not roll over.`,'subtle'));
    if(data.credits.replyAttempts||data.credits.voiceMinutes)credits.append(el('p',`Verified packs in this period add ${data.credits.replyAttempts.toLocaleString()} reply attempts and ${data.credits.voiceMinutes} microphone minutes. These are included in the allowance above.`,'inline-note'));
    const pending=data.credits.checkout?.pending;if(pending)credits.append(el('p','A pack checkout is pending. No allowance is added until Stripe verifies payment. Resume it below or refresh payment status after returning.','inline-note'));
    const cards=el('div','','credit-pack-grid');for(const pack of data.creditPacks){const card=el('article','','credit-pack-card'),price=new Intl.NumberFormat(undefined,{style:'currency',currency:pack.currency.toUpperCase(),maximumFractionDigits:0}).format(pack.priceCents/100);card.append(el('h3',pack.name),el('p',`${price} once`,'credit-pack-price'),el('p',`+${pack.replyAttempts.toLocaleString()} reply attempts · +${pack.voiceMinutes} microphone minutes`));const resume=pending&&data.credits.checkout.packId===pack.id,buy=button(resume?'Resume pack checkout':`Choose ${pack.name}`,()=>creditCheckout(pack),'secondary');buy.disabled=!data.permissions.canManage||!data.readiness.creditPacks||pack.available!==true||Boolean(pending&&!resume);card.append(buy);cards.append(card);}credits.append(cards,el('p','Optional on either plan. No subscription, automatic purchase, or overage charge. A refund or dispute removes that pack’s allowance; usage already consumed remains counted.','source-note'));
    if(data.credits.purchases?.length){const history=el('details','','credit-pack-history');history.append(el('summary','Pack purchases this period'));const list=el('ul');for(const purchase of data.credits.purchases){const pack=data.creditPacks.find((item:any)=>item.id===purchase.packId);list.append(el('li',`${pack?.name??'Usage pack'} · ${String(purchase.status).replaceAll('_',' ')}${purchase.paidAt?' · '+fullTime(purchase.paidAt):''}`));}history.append(list);credits.append(history);}target.append(credits);
   }
   if(data.plan.cancelAtPeriodEnd)target.append(el('p','Pro ends at the close of this paid period. Your saved business records remain available on Free.','inline-note'));
   const plans=el('div','','plan-grid');for(const plan of data.plans){const card=el('section','','plan-card'+(plan.id==='pro'?' recommended':''));card.append(el('span',plan.id==='pro'?'FOR A BUSIER BUSINESS':'A GOOD PLACE TO START','eyebrow'),el('h2',plan.name));const price=el('p','','plan-price');price.append(el('strong',new Intl.NumberFormat(undefined,{style:'currency',currency:plan.currency.toUpperCase(),maximumFractionDigits:0}).format(plan.priceCents/100)),el('span',plan.priceCents?' / month':' / month, always'));card.append(price);const list=el('ul','','plan-features');for(const label of [`${plan.replyLimit.toLocaleString()} assistant replies`,`${plan.voiceMinuteLimit} microphone minutes`,'Customers, appointments, and tasks','Calendar connection and saved business profile']){const item=el('li');item.append(icon('check'),el('span',label));list.append(item);}card.append(list);
    if(plan.id===data.plan.id)card.append(el('p','Your current plan','current-plan'));else if(plan.id==='pro'){const upgrade=button(data.checkout.pending?'Resume checkout':'Upgrade to Pro',()=>{void checkout();},'primary');upgrade.disabled=!data.permissions.canManage||!data.readiness.checkout;card.append(upgrade);}else card.append(el('p','Manage a paid subscription below to return to Free.','subtle'));plans.append(card);}target.append(plans);
   const message=el('p',data.readiness.message??'','subtle');target.append(message);if(data.readiness.mode==='test')target.append(el('p','Payment testing is enabled. Checkout uses Stripe test mode; no real payment is taken.','inline-note'));
   if(data.permissions.canManage&&data.readiness.portal)target.append(button('Manage subscription & invoices',()=>void portal(),'secondary'));if(!data.permissions.canManage)target.append(el('p','A business owner or a person with the billing role can manage the subscription.','subtle'));
   target.append(el('p','No automatic overage charges. Paid periods begin after Stripe verifies payment. Carrier charges for a connected business phone are separate.','source-note'));paintIcons();
   async function creditCheckout(pack:any){if(!data.permissions.canManage||!data.readiness.creditPacks||pack.available!==true)return;const price=new Intl.NumberFormat(undefined,{style:'currency',currency:pack.currency.toUpperCase(),maximumFractionDigits:0}).format(pack.priceCents/100),node=dialog(`Review ${pack.name} pack`);node.append(el('p',`${price} once adds ${pack.replyAttempts.toLocaleString()} reply attempts and ${pack.voiceMinutes} microphone minutes to ${$('business-name').textContent}. Stripe verifies payment before adding allowance.`),el('p',`This pack expires ${fullTime(data.credits.expiresAt)}. Unused credits do not transfer if you upgrade or downgrade, and do not roll over. This is a one-time purchase.`,'inline-note'));const checkoutRequestId=data.credits.checkout?.pending&&data.credits.checkout.packId===pack.id?data.credits.checkout.requestId:crypto.randomUUID(),status=el('p'),go=button('Continue to Stripe',()=>{go.disabled=true;void guarded(async()=>{try{const result=await hooks.api(base()+'/billing/credit-checkout',{packId:pack.id,periodKey:data.credits.periodKey},{'Idempotency-Key':checkoutRequestId});stripeRedirect(result.url);}finally{go.disabled=false;}},status)();},'primary');status.setAttribute('role','status');node.append(status,go);}
   async function checkout(){if(!data.permissions.canManage||!data.readiness.checkout){hooks.onNotice(data.readiness.message??'Checkout is not available yet.');return;}const pro=data.plans.find((plan:any)=>plan.id==='pro');if(!pro)throw new Error('The current Pro offer could not be verified. Refresh Plan & usage.');const price=new Intl.NumberFormat(undefined,{style:'currency',currency:pro.currency.toUpperCase(),maximumFractionDigits:0}).format(pro.priceCents/100),node=dialog('Upgrade to Pro');node.append(el('p',`Pro is ${price} per month for this business. Stripe handles payment. Your allowance changes after verified payment.`));if(data.credits?.replyAttempts||data.credits?.voiceMinutes)node.append(el('p','Unused usage packs belong to your current Free period and expire when Pro starts. They do not transfer to your new paid period.','inline-note'));const checkoutRequestId=data.checkout.requestId??crypto.randomUUID(),status=el('p'),go=button('Continue to Stripe',()=>{go.disabled=true;void guarded(async()=>{try{const result=await hooks.api(base()+'/billing/checkout',{planId:'pro'}, {'Idempotency-Key':checkoutRequestId});stripeRedirect(result.url);}finally{go.disabled=false;}},status)();},'primary');node.append(status,go);}
   async function portal(){await guarded(async()=>{const result=await hooks.api(base()+'/billing/portal',{}, {'Idempotency-Key':crypto.randomUUID()});stripeRedirect(result.url);})();}
  }catch(reason){if(version===billingVersion&&ready)error(target,reason,()=>void loadBilling(sync));}
 }
 function stripeRedirect(raw:string){const url=new URL(raw);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname)||url.username||url.password||url.port)throw new Error('Unexpected payment destination. Please try again.');location.assign(url.href);}
 function show(view:WorkdayView){if(current!==view)window.scrollTo({top:0,behavior:'instant'});current=view;document.body.dataset.view=view;for(const name of views){$(`${name}-view`).hidden=name!==view;const tab=$(`${name}-tab`);tab.classList.toggle('active',name===view);if(name===view)tab.setAttribute('aria-current','page');else tab.removeAttribute('aria-current');}
  updateDesktopTabs();updateMobileTabs();
  if(!ready){if(['appointments','customers','tasks','billing'].includes(view))$(`${view}-content`).replaceChildren(empty('Your workspace is waiting.','Sign in to bring your business together.',button('Continue with Google',hooks.onSignIn,'primary')));return;}
  if(!hooks.canManage()&&['today','appointments','customers','tasks','connections'].includes(view)){$(`${view}-content`).replaceChildren(empty('Your workspace is ready.',hooks.canChat()?'Owners and managers manage shared business records. Your role can use the Assistant.':'Owners and managers manage shared business records. Your role can read shared usage in Plan & usage.',button(hooks.canChat()?'Open Assistant':'Plan & usage',()=>hooks.onNavigate(hooks.canChat()?'chat':'billing'),'primary')));return;}
  if(view==='today')void refreshOverview();if(view==='appointments')void loadAgenda();if(view==='customers')void loadCustomers();if(view==='tasks'){void loadTasks();void routines.load();}if(view==='billing')void loadBilling();
 }
 const menuButton=button('',()=>{
  const panel=dialog('Your workspace');panel.classList.add('mobile-navigation');menuButton.setAttribute('aria-expanded','true');
  panel.append(el('p',`${$('business-name').textContent} · ${$('business-role').textContent}`,'subtle'));
  const links=el('div','','mobile-navigation-links');
  for(const [label,view,mark] of [['Today','today','house'],['Assistant','chat','sparkles'],['Appointments','appointments','calendar-days'],['Customers','customers','users'],['Tasks','tasks','list-todo'],['Plan & usage','billing','credit-card'],['Connections','connections','plug'],['Settings','account','settings'],['Help','help','circle-help']] as [string,WorkdayView,string][]){
   if(!ready&&view!=='help')continue;
   if(['today','appointments','customers','tasks','connections'].includes(view)&&!hooks.canManage())continue;
   if(view==='chat'&&!hooks.canChat()||view==='account'&&workspaceRole==='billing')continue;
   const item=button(label,()=>{
    menuButton.setAttribute('aria-expanded','false');panel.close();hooks.onNavigate(view);
    const heading=$(`${view}-view`).querySelector<HTMLElement>('h1');
    if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}
   },'mobile-navigation-link');
   item.prepend(icon(mark));if(current===view)item.setAttribute('aria-current','page');links.append(item);
  }
  panel.append(links);panel.addEventListener('close',()=>menuButton.setAttribute('aria-expanded','false'));paintIcons();
  (links.querySelector<HTMLButtonElement>('[aria-current="page"]')??links.querySelector('button'))?.focus();
 },'icon-button mobile-menu-toggle');
 menuButton.setAttribute('aria-label','Open workspace menu');menuButton.setAttribute('aria-haspopup','dialog');menuButton.setAttribute('aria-expanded','false');menuButton.append(icon('menu'));document.querySelector('.sidebar')!.prepend(menuButton);
 const phoneTabs=el('nav','','mobile-tabs');phoneTabs.setAttribute('aria-label','Mobile navigation');
 for(const [label,view,mark] of [['Today','today','house'],['Assistant','chat','sparkles'],['Bookings','appointments','calendar-days'],['Customers','customers','users']] as [string,WorkdayView,string][]){const tab=button('',()=>hooks.onNavigate(view),'mobile-tab');tab.dataset.view=view;tab.setAttribute('aria-label',view==='appointments'?'Appointments':label);tab.append(icon(mark),el('span',label));phoneTabs.append(tab);}
 const moreTab=button('',()=>menuButton.click(),'mobile-tab');moreTab.setAttribute('aria-label','More workspace tools');moreTab.append(icon('menu'),el('span','More'));phoneTabs.append(moreTab);document.body.append(phoneTabs);
 function updateMobileTabs(){let primary=false,count=1;for(const tab of phoneTabs.querySelectorAll<HTMLButtonElement>('[data-view]')){tab.hidden=!ready||(tab.dataset.view==='chat'?!hooks.canChat():!hooks.canManage());if(!tab.hidden)count++;if(!tab.hidden&&tab.dataset.view===current){tab.setAttribute('aria-current','page');primary=true;}else tab.removeAttribute('aria-current');}phoneTabs.style.gridTemplateColumns=`repeat(${count},minmax(0,1fr))`;if(!primary)moreTab.setAttribute('aria-current','page');else moreTab.removeAttribute('aria-current');}
 function updateDesktopTabs(){for(const view of views){const operator=['today','appointments','customers','tasks','connections'].includes(view);$(`${view}-tab`).hidden=operator?(!ready||!hooks.canManage()):view==='chat'?(ready&&!hooks.canChat()):false;}}
 async function refreshCurrent(){if(!ready)return;if(current==='today')await refreshOverview();if(current==='appointments')await loadAgenda();if(current==='customers')await loadCustomers();if(current==='tasks'){await loadTasks();await routines.load();}if(current==='billing')await loadBilling(true);}
 const mobileTools=el('div','','mobile-tools');mobileTools.setAttribute('aria-label','More workspace tools');for(const [label,view] of [['Tasks','tasks'],['Plan & usage','billing'],['Help','help']] as [string,WorkdayView][])mobileTools.append(button(label,()=>hooks.onNavigate(view)));$('account-view').prepend(mobileTools);
 for(const view of views)$(`${view}-tab`).onclick=()=>hooks.onNavigate(view);
 updateDesktopTabs();updateMobileTabs();paintIcons();
 return {show,refresh:refreshOverview,refreshCurrent,openMissedCalls:()=>{void missedCallsDialog();},ready(name:string,role:string){ready=true;workspaceRole=role;phoneTabs.hidden=false;menuButton.disabled=false;$('business-name').textContent=name;$('business-name').title=name;$('business-role').textContent=role.charAt(0).toUpperCase()+role.slice(1)+' workspace';show(current);const query=new URLSearchParams(location.search);if(query.get('billing')){hooks.onNavigate('billing');void loadBilling(true);}},clear(){ready=false;workspaceRole='';updateDesktopTabs();phoneTabs.hidden=true;menuButton.disabled=true;menuButton.setAttribute('aria-expanded','false');routines.clear();businessAgent.clear();accessVersion++;loadVersion++;taskVersion++;customerVersion++;agendaVersion++;billingVersion++;appointmentDate='';customerRows=[];taskRows=[];agendaRows=[];customerQuery='';customerCursor=taskCursor=agendaCursor=null;for(const view of ['today','appointments','customers','tasks','billing'])$(`${view}-content`).replaceChildren();document.querySelectorAll<HTMLDialogElement>('.workday-dialog').forEach(node=>node.close());$('business-name').textContent='Your business';$('business-name').removeAttribute('title');$('business-role').textContent='Workspace access ended';}};
}
