export const BUSINESS_ROUTINE_CATALOG=Object.freeze([
 {id:'daily-priorities',title:'Daily priorities',description:'Review overdue work, callbacks and upcoming bookings before choosing today’s focus.',cadence:'Daily',steps:['Review saved tasks and callback requests.','Check confirmed Mayor bookings for the next seven days.','Choose up to three priorities and save any new tasks yourself.'],assistantPrompt:'Review my saved tasks, pending callbacks and confirmed Mayor bookings. Help me choose three priorities; ask before changing anything.'},
 {id:'callback-follow-up',title:'Callback follow-up',description:'Prepare a clear, respectful response to requests awaiting review.',cadence:'Weekdays',steps:['Review each pending callback and its recorded reason.','Verify the contact and consent before following up.','Record the outcome only after the follow-up happened.'],assistantPrompt:'Review my pending callback requests and help draft a follow-up. Do not call or send anything, and do not assume contact identity or consent.'},
 {id:'booking-readiness',title:'Booking readiness',description:'Prepare for confirmed visits, sessions and appointments booked through Mayor.',cadence:'Daily',steps:['Review the next seven days of confirmed Mayor bookings.','Prepare supplies, staff handoffs or session notes as appropriate.','Review any suggested task before saving it.'],assistantPrompt:'Help me prepare for upcoming confirmed Mayor bookings using my saved services and business details. Do not change appointments.'},
 {id:'customer-retention',title:'Customer retention',description:'Draft useful follow-up ideas for service, salon, retail, restaurant and online customers.',cadence:'Weekdays',steps:['Review saved customer records and available contact fields.','Choose a useful follow-up idea based on confirmed services.','Verify consent and personalize a draft before sending it yourself.'],assistantPrompt:'Suggest customer retention ideas grounded in my saved services and customer records. Draft only; do not invent purchase history, consent or results.'},
 {id:'local-visibility',title:'Local visibility',description:'Prepare a manual check of your public business information and service message.',cadence:'Weekly review on your chosen schedule',steps:['Review the confirmed website, hours, locations and services.','Compare them with your public listings yourself.','Ask Mayor to draft improvements from the facts you confirm.'],assistantPrompt:'Use my confirmed business facts to draft a public business description and a manual listing checklist. Do not claim you monitored reviews or listings.'},
 {id:'team-handoff',title:'Team handoff',description:'Turn recorded priorities into a practical handoff for a shop, restaurant, trade team or professional practice.',cadence:'Daily',steps:['Review recorded tasks, callbacks and bookings.','Choose who should handle each item; assignments are suggestions.','Review a handoff draft before sharing it yourself.'],assistantPrompt:'Draft a team handoff from saved tasks, callbacks and confirmed Mayor bookings. Do not invent staff availability or send it.'},
 {id:'weekly-growth',title:'Growth review',description:'Choose a small growth experiment for services, trades, fitness, professional or online businesses.',cadence:'Weekly review on your chosen schedule',steps:['Review confirmed goals, services and current operational counts.','Choose one practical experiment and decide what you will measure.','Save follow-up tasks only after reviewing them.'],assistantPrompt:'Help me choose one growth experiment based on confirmed goals and services. State unknown revenue, conversion and industry benchmarks; do not invent performance.'},
 {id:'service-offer-review',title:'Offer and service review',description:'Clarify a service, session, product or menu offer using the business details you confirmed.',cadence:'Weekly review on your chosen schedule',steps:['Choose an offer from confirmed services or supply the missing details.','Draft its audience, benefit and next step without invented prices.','Review the wording before publishing or changing any profile.'],assistantPrompt:'Help me clarify one offer using my confirmed services and goals. Ask for missing prices or details. Draft only; do not update or publish anything.'},
] as const);
