import {z} from 'zod';
import type {Actor,Env} from './env';
import {HttpError,json,readJson,requireOrigin} from './http';
import {OPERATORS,requireMembership} from './permissions';
import {checkScheduleSchema,nextCheckRun,type CheckSchedule} from './check-schedule';
import {readMemory} from './memory';

import {BUSINESS_ROUTINE_CATALOG} from './business-routine-catalog';
export {BUSINESS_ROUTINE_CATALOG} from './business-routine-catalog';
const ids=BUSINESS_ROUTINE_CATALOG.map(item=>item.id) as [string,...string[]];
const templateIds=z.array(z.enum(ids)).min(1).max(8).refine(value=>new Set(value).size===value.length,'Choose each routine once.');
export const businessRoutineConfigSchema=z.object({revision:z.number().int().min(0),enabled:z.boolean(),templateIds,schedule:checkScheduleSchema.optional()}).strict().refine(input=>!input.enabled||Boolean(input.schedule),'Choose a schedule before enabling routines.');
type ConfigInput=z.infer<typeof businessRoutineConfigSchema>;
export type RoutineProposal={input:ConfigInput;actor:Actor;expiresAt:number};
type ConfigRow={tenant_id:string;user_id:string;enabled:number;template_ids_json:string;schedule_json:string|null;revision:number;next_run_at:string|null;due_local_date:string|null;lease_token:string|null;lease_until:string|null;attempts:number;last_run_at:string|null;last_status:'ready'|'failed'|null};
type RunRow={id:string;tenant_id:string;user_id:string;config_revision:number;dedupe_key:string;trigger_kind:'manual'|'scheduled';state:'processing'|'ready'|'failed'|'discarded';lease_token:string|null;lease_until:string|null;brief_json:string|null;created_at:string;updated_at:string};
export type BusinessRoutineBrief={id:string;generatedAt:string;templateIds:string[];summary:string;metrics:{key:string;label:string;value:number|null}[];priorities:{id:string;title:string;detail:string;source:{kind:string;id?:string};assistantPrompt?:string}[];suggestions:{title:string;detail:string;assistantPrompt:string}[];gaps:string[];scope:string};
const SCOPE='Saved confirmed business profile, local tasks, saved customer/contact counts, pending callback requests and confirmed Mayor bookings only. Other calendar events, inbox, reviews, sales, revenue and benchmarks are not monitored. Suggestions are drafts; nothing is sent, published or changed.';
const permission="EXISTS(SELECT 1 FROM agent_memberships m JOIN agent_tenants t ON t.id=m.tenant_id WHERE m.tenant_id=? AND m.user_id=? AND m.status='active' AND t.status='active' AND m.role IN ('owner','manager') AND (m.expires_at IS NULL OR m.expires_at>?))";
const configSelect='SELECT * FROM mayor_business_routines WHERE tenant_id=? AND user_id=?';
const runSelect='SELECT * FROM mayor_business_routine_runs WHERE tenant_id=? AND user_id=? AND dedupe_key=?';
function configView(row:ConfigRow|null){return {enabled:Boolean(row?.enabled),templateIds:row?JSON.parse(row.template_ids_json) as string[]:['daily-priorities'],schedule:row?.schedule_json?checkScheduleSchema.parse(JSON.parse(row.schedule_json)):null,revision:row?.revision??0,nextRunAt:row?.next_run_at&&row.lease_until&&row.lease_until>row.next_run_at?row.lease_until:row?.next_run_at??null,lastRunAt:row?.last_run_at??null,lastStatus:row?.last_status??null,running:Boolean(row?.lease_token&&row.lease_until&&row.lease_until>new Date().toISOString())};}
export async function readBusinessRoutines(env:Env,actor:Actor){
 await requireMembership(env,actor,OPERATORS);
 const [row,runs]=await Promise.all([env.AGENT_DB.prepare(configSelect).bind(actor.tenantId,actor.userId).first<ConfigRow>(),env.AGENT_DB.prepare("SELECT id,state,brief_json,created_at,read_at,trigger_kind FROM mayor_business_routine_runs WHERE tenant_id=? AND user_id=? AND state='ready' ORDER BY updated_at DESC,id DESC LIMIT 10").bind(actor.tenantId,actor.userId).all<{id:string;state:string;brief_json:string;created_at:string;read_at:string|null;trigger_kind:string}>()]);
 await requireMembership(env,actor,OPERATORS);
 return {catalog:BUSINESS_ROUTINE_CATALOG,config:configView(row),latestBrief:runs.results[0]?JSON.parse(runs.results[0].brief_json) as BusinessRoutineBrief:null,history:runs.results.map(run=>({id:run.id,generatedAt:(JSON.parse(run.brief_json) as BusinessRoutineBrief).generatedAt,trigger:run.trigger_kind,read:run.read_at!==null})),scope:SCOPE};
}
export async function prepareBusinessRoutines(env:Env,actor:Actor,raw:ConfigInput):Promise<RoutineProposal>{const input=businessRoutineConfigSchema.parse(raw),current=await readBusinessRoutines(env,actor);if(input.revision!==current.config.revision)throw new HttpError(409,'routine_config_changed','Your routines changed. Review them again.');return {input,actor:{...actor},expiresAt:Date.now()+120000};}
export function businessRoutinesReadback(proposal:RoutineProposal){const names=BUSINESS_ROUTINE_CATALOG.filter(item=>proposal.input.templateIds.includes(item.id)).map(item=>item.title).join(', ');if(!proposal.input.enabled)return `Save ${names} and pause scheduled business briefs? Existing briefs stay available. Nothing will be sent or changed. Say yes to confirm.`;const schedule=proposal.input.schedule!;return `Enable ${names} ${schedule.frequency==='daily'?'every day':'Monday through Friday'} at ${String(schedule.hour).padStart(2,'0')}:${String(schedule.minute).padStart(2,'0')} in ${schedule.timeZone}? Briefs use saved facts, tasks, callbacks and confirmed Mayor bookings, with in-app notices only. Nothing is sent or changed. Checks normally start within five minutes; nonexistent clock-change times are skipped. Say yes to confirm.`;}
export async function confirmBusinessRoutines(env:Env,actor:Actor,proposal:RoutineProposal){
 if(proposal.expiresAt<=Date.now()||proposal.actor.tenantId!==actor.tenantId||proposal.actor.userId!==actor.userId)throw new HttpError(409,'confirmation_expired','Review the business routines again.');
 const input=businessRoutineConfigSchema.parse(proposal.input);await requireMembership(env,actor,OPERATORS);
 const prior=await env.AGENT_DB.prepare(configSelect).bind(actor.tenantId,actor.userId).first<ConfigRow>();
 if((prior?.revision??0)!==input.revision)throw new HttpError(409,'routine_config_changed','Your routines changed. Review them again.');
 const now=new Date().toISOString(),schedule=input.schedule??(prior?.schedule_json?checkScheduleSchema.parse(JSON.parse(prior.schedule_json)):null),next=input.enabled?nextCheckRun(schedule!,Date.now()):null;
 const result=await env.AGENT_DB.prepare(`INSERT INTO mayor_business_routines(tenant_id,user_id,enabled,template_ids_json,schedule_json,next_run_at,due_local_date,created_at,updated_at)
 SELECT ?,?,?,?,?,?,?,?,? WHERE ${permission} AND COALESCE((SELECT revision FROM mayor_business_routines WHERE tenant_id=? AND user_id=?),0)=?
 ON CONFLICT(tenant_id,user_id) DO UPDATE SET enabled=excluded.enabled,template_ids_json=excluded.template_ids_json,schedule_json=excluded.schedule_json,revision=mayor_business_routines.revision+1,next_run_at=excluded.next_run_at,due_local_date=excluded.due_local_date,lease_token=NULL,lease_until=NULL,attempts=0,updated_at=excluded.updated_at WHERE mayor_business_routines.revision=?`).bind(actor.tenantId,actor.userId,Number(input.enabled),JSON.stringify(input.templateIds),schedule?JSON.stringify(schedule):null,next?.at??null,next?.date??null,now,now,actor.tenantId,actor.userId,now,actor.tenantId,actor.userId,input.revision,input.revision).run();
 if(result.meta.changes!==1)throw new HttpError(409,'routine_config_changed','Your routines or access changed. Review them again.');
 return readBusinessRoutines(env,actor);
}
/** Deterministic snapshot from local records. No provider, model, email or record writes. */
export async function buildBusinessRoutineBrief(env:Env,actor:Actor,selected:string[],time=Date.now()):Promise<Omit<BusinessRoutineBrief,'id'>>{
 await requireMembership(env,actor,OPERATORS);const generatedAt=new Date(time).toISOString(),endSeconds=(time+7*86400000)/1000;
 const bookingWhere="a.tenant_id=? AND a.state='confirmed' AND j.state='applied' AND a.start_epoch>=? AND a.start_epoch<? AND NOT EXISTS(SELECT 1 FROM mayor_appointment_changes c WHERE c.appointment_id=a.id AND c.tenant_id=a.tenant_id AND c.state IN ('running','uncertain'))";
 const [memory,tasks,taskCounts,callbackCounts,callbacks,customerCounts,bookingCounts,bookings]=await Promise.all([
  readMemory(env,actor),
  env.AGENT_DB.prepare("SELECT id,title,due_at,priority FROM mayor_tasks WHERE tenant_id=? AND status='open' ORDER BY CASE WHEN due_at<? THEN 0 WHEN priority='high' THEN 1 ELSE 2 END,COALESCE(due_at,'9999'),id LIMIT 8").bind(actor.tenantId,generatedAt).all<{id:string;title:string;due_at:string|null;priority:string}>(),
  env.AGENT_DB.prepare("SELECT COUNT(*) AS open,COALESCE(SUM(due_at<?),0) AS overdue FROM mayor_tasks WHERE tenant_id=? AND status='open'").bind(generatedAt,actor.tenantId).first<{open:number;overdue:number}>(),
  env.AGENT_DB.prepare("SELECT COUNT(*) AS pending FROM mayor_callbacks WHERE tenant_id=? AND status='pending'").bind(actor.tenantId).first<{pending:number}>(),
  env.AGENT_DB.prepare("SELECT id,reason,created_at FROM mayor_callbacks WHERE tenant_id=? AND status='pending' ORDER BY created_at,id LIMIT 5").bind(actor.tenantId).all<{id:string;reason:string;created_at:string}>(),
  env.AGENT_DB.prepare("SELECT COUNT(*) AS total,COALESCE(SUM((email IS NOT NULL AND trim(email)!='') OR (phone IS NOT NULL AND trim(phone)!='')),0) AS contact FROM mayor_customers WHERE tenant_id=?").bind(actor.tenantId).first<{total:number;contact:number}>(),
  env.AGENT_DB.prepare(`SELECT COUNT(*) AS total FROM mayor_appointments a JOIN mayor_appointment_jobs j ON j.id=a.id AND j.tenant_id=a.tenant_id WHERE ${bookingWhere}`).bind(actor.tenantId,time/1000,endSeconds).first<{total:number}>(),
  env.AGENT_DB.prepare(`SELECT a.id,a.input_json FROM mayor_appointments a JOIN mayor_appointment_jobs j ON j.id=a.id AND j.tenant_id=a.tenant_id WHERE ${bookingWhere} ORDER BY a.start_epoch,a.id LIMIT 5`).bind(actor.tenantId,time/1000,endSeconds).all<{id:string;input_json:string}>(),
 ]);
 await requireMembership(env,actor,OPERATORS);
 const priorities:BusinessRoutineBrief['priorities']=tasks.results.map(task=>({id:`task:${task.id}`,title:task.title,detail:`${task.due_at&&task.due_at<generatedAt?'Overdue task. ':''}${task.priority==='high'?'High priority. ':''}${task.due_at?`Recorded due time: ${task.due_at}.`:'No due date recorded.'}`,source:{kind:'task',id:task.id},assistantPrompt:`Help me review the saved task ${task.id}. Ask before changing it.`}));
 priorities.push(...callbacks.results.map(callback=>({id:`callback:${callback.id}`,title:'Review a pending callback',detail:`${callback.reason==='scheduling'?'Scheduling request':'Human assistance request'} recorded ${callback.created_at}. Contact identity and permission to call are unverified.`,source:{kind:'callback',id:callback.id},assistantPrompt:`Help me review callback ${callback.id} and draft a follow-up. Do not call or send anything.`})));
 priorities.push(...bookings.results.map(booking=>{const input=JSON.parse(booking.input_json) as {title:string;start:string};return {id:`booking:${booking.id}`,title:`Prepare for ${input.title}`,detail:`Confirmed Mayor booking starts ${input.start}. External calendar events are not included.`,source:{kind:'booking',id:booking.id},assistantPrompt:`Help me prepare for confirmed Mayor booking ${booking.id}. Do not change the appointment.`};}));
 const confirmedService=memory.profile.services?.find(value=>value.trim()),goals=memory.profile.businessGoals??[];
 const details:Record<string,string>={
  'daily-priorities':`Start with ${taskCounts!.overdue} overdue tasks and ${callbackCounts!.pending} callback requests. Choose the most urgent next action yourself.`,
  'callback-follow-up':'Draft: “Hello [name], I’m following up on your request for help. Is now a good time to discuss what you need?” Verify the recipient and consent; this has not been sent.',
  'booking-readiness':`Review preparation for ${bookingCounts!.total} confirmed Mayor bookings in the next seven days. Supplies, staffing and other calendar events have not been verified.`,
  'customer-retention':`There are ${customerCounts!.total} saved customer records, including ${customerCounts!.contact} with a contact field. Purchase history and marketing consent are unknown. Draft: “Hello [name], would a helpful follow-up about [service] be welcome?”`,
  'local-visibility':`Manually compare your public listings with the confirmed ${[memory.profile.website?'website':null,memory.profile.hours?'hours':null,memory.profile.locations?.length?'locations':null,confirmedService?'services':null].filter(Boolean).join(', ')||'business facts once you provide them'}. No listing or review was checked by this routine.`,
  'team-handoff':`Draft a handoff for the ${taskCounts!.open} open tasks, ${callbackCounts!.pending} callback requests and ${bookingCounts!.total} upcoming Mayor bookings. Staff availability and assignments need your review.`,
  'weekly-growth':goals.length?`Choose one small experiment supporting your confirmed goal: “${goals[0]}”. Decide a measure and baseline yourself; no revenue, conversion or benchmark data is available.`:'Confirm one business goal, then choose a small experiment and a measure. Revenue, conversion and industry benchmarks are unknown.',
  'service-offer-review':confirmedService?`Draft an offer description for the confirmed service “${confirmedService}”: audience, benefit and next step. Price, capacity and availability must be supplied and reviewed.`:'Supply an offer, service, menu item or product before drafting its audience, benefit and next step. No price or inventory has been inferred.',
 };
 const gaps=['No sales, revenue, conversion, review or inbox data is collected by these routines.','Saved contact details do not establish customer identity, purchase history or permission to send messages.'];
 if(!memory.confirmedAt)gaps.push('No business profile has been confirmed yet.');if(!confirmedService)gaps.push('No services or offers are confirmed.');if(!goals.length)gaps.push('No business goals are confirmed.');
 if(taskCounts!.open>tasks.results.length||callbackCounts!.pending>callbacks.results.length||bookingCounts!.total>bookings.results.length)gaps.push('The priority list is capped; counts include additional saved records.');
 return {generatedAt,templateIds:selected,summary:`${taskCounts!.overdue} overdue tasks, ${callbackCounts!.pending} callback requests awaiting review, and ${bookingCounts!.total} confirmed Mayor bookings in the next seven days.`,metrics:[{key:'open_tasks',label:'Open tasks',value:taskCounts!.open},{key:'overdue_tasks',label:'Overdue tasks',value:taskCounts!.overdue},{key:'pending_callbacks',label:'Pending callbacks',value:callbackCounts!.pending},{key:'bookings_next_7_days',label:'Confirmed Mayor bookings · next 7 days',value:bookingCounts!.total},{key:'saved_customers',label:'Saved customer records',value:customerCounts!.total},{key:'customers_with_contact',label:'Records with a contact field',value:customerCounts!.contact},{key:'revenue',label:'Revenue · not recorded',value:null}],priorities,suggestions:BUSINESS_ROUTINE_CATALOG.filter(item=>selected.includes(item.id)).map(item=>({title:item.title,detail:details[item.id],assistantPrompt:item.assistantPrompt})),gaps,scope:SCOPE};
}
type RunOptions={now?:number;build?:typeof buildBusinessRoutineBrief};
async function executeRoutine(env:Env,actor:Actor,row:ConfigRow,key:string,trigger:'manual'|'scheduled',options:RunOptions={}){
 const time=options.now??Date.now(),now=new Date(time).toISOString(),token=crypto.randomUUID();
 const existing=await env.AGENT_DB.prepare(runSelect).bind(actor.tenantId,actor.userId,key).first<RunRow>();
 if(existing?.state==='ready'){await requireMembership(env,actor,OPERATORS);return {brief:JSON.parse(existing.brief_json!) as BusinessRoutineBrief,replay:true};}
 if(trigger==='manual'&&existing&&existing.config_revision!==row.revision)throw new HttpError(409,'routine_request_changed','Your routines changed after this request began. Review them before starting a new brief.');
 const claim=await env.AGENT_DB.prepare(`UPDATE mayor_business_routines SET lease_token=?,lease_until=?,attempts=attempts+1 WHERE tenant_id=? AND user_id=? AND revision=? AND (lease_until IS NULL OR lease_until<=?) ${trigger==='scheduled'?'AND enabled=1 AND next_run_at=?':''} AND ${permission} RETURNING attempts`).bind(token,new Date(time+120000).toISOString(),actor.tenantId,actor.userId,row.revision,now,...(trigger==='scheduled'?[row.next_run_at]:[]),actor.tenantId,actor.userId,now).first<{attempts:number}>();
 if(!claim)throw new HttpError(409,'routine_running','A brief is running or your routines changed. Refresh before trying again.');
 const runId=existing?.id??crypto.randomUUID(),leaseUntil=new Date(time+120000).toISOString();
 const run=await env.AGENT_DB.prepare(`INSERT INTO mayor_business_routine_runs(id,tenant_id,user_id,config_revision,dedupe_key,trigger_kind,due_local_date,state,lease_token,lease_until,created_at,updated_at)
 SELECT ?,?,?,?,?,?,?,'processing',?,?,?,? WHERE EXISTS(SELECT 1 FROM mayor_business_routines WHERE tenant_id=? AND user_id=? AND revision=? AND lease_token=?) AND ${permission}
 ON CONFLICT(tenant_id,user_id,dedupe_key) DO UPDATE SET config_revision=excluded.config_revision,state='processing',lease_token=excluded.lease_token,lease_until=excluded.lease_until,brief_json=NULL,updated_at=excluded.updated_at WHERE mayor_business_routine_runs.state!='ready' AND (mayor_business_routine_runs.lease_until IS NULL OR mayor_business_routine_runs.lease_until<=?) RETURNING id`).bind(runId,actor.tenantId,actor.userId,row.revision,key,trigger,trigger==='scheduled'?row.due_local_date:null,token,leaseUntil,now,now,actor.tenantId,actor.userId,row.revision,token,actor.tenantId,actor.userId,now,now).first<{id:string}>();
 if(!run){await env.AGENT_DB.prepare('UPDATE mayor_business_routines SET lease_token=NULL,lease_until=NULL WHERE tenant_id=? AND user_id=? AND lease_token=?').bind(actor.tenantId,actor.userId,token).run();throw new HttpError(409,'routine_running','This brief is already running. Retry the same request after it finishes.');}
 let content:Omit<BusinessRoutineBrief,'id'>|null=null;
 try{content=await (options.build??buildBusinessRoutineBrief)(env,actor,JSON.parse(row.template_ids_json),time);}catch{console.warn(JSON.stringify({event:'business_routine_failed',reason:'brief_unavailable'}));}
 const finished=new Date(options.now??Date.now()).toISOString(),brief=content?{...content,id:run.id}:null;
 const next=trigger==='scheduled'&&(content||claim.attempts>=3)?nextCheckRun(JSON.parse(row.schedule_json!) as CheckSchedule,Math.max(time,Date.parse(finished)),row.due_local_date??undefined):null;
 const guard=`EXISTS(SELECT 1 FROM mayor_business_routines WHERE tenant_id=? AND user_id=? AND revision=? AND lease_token=? AND lease_until>?) ${trigger==='scheduled'?'AND EXISTS(SELECT 1 FROM mayor_business_routines WHERE tenant_id=? AND user_id=? AND enabled=1)':''} AND ${permission}`;
 const args=[actor.tenantId,actor.userId,row.revision,token,finished,...(trigger==='scheduled'?[actor.tenantId,actor.userId]:[]),actor.tenantId,actor.userId,finished];
 const results=await env.AGENT_DB.batch([
  env.AGENT_DB.prepare(`UPDATE mayor_business_routine_runs SET state=?,brief_json=?,lease_until=NULL,updated_at=? WHERE id=? AND tenant_id=? AND user_id=? AND state='processing' AND lease_token=? AND config_revision=? AND ${guard}`).bind(brief?'ready':'failed',brief?JSON.stringify(brief):null,finished,run.id,actor.tenantId,actor.userId,token,row.revision,...args),
  env.AGENT_DB.prepare(`UPDATE mayor_business_routine_runs SET read_at=COALESCE(read_at,?) WHERE tenant_id=? AND user_id=? AND state='ready' AND id!=? AND EXISTS(SELECT 1 FROM mayor_business_routine_runs WHERE id=? AND state='ready' AND lease_token=?) AND ${guard}`).bind(finished,actor.tenantId,actor.userId,run.id,run.id,token,...args),
  env.AGENT_DB.prepare(`UPDATE mayor_business_routines SET last_run_at=?,last_status=?,next_run_at=?,due_local_date=?,lease_token=NULL,lease_until=?,attempts=?,updated_at=? WHERE tenant_id=? AND user_id=? AND revision=? AND lease_token=? AND EXISTS(SELECT 1 FROM mayor_business_routine_runs WHERE id=? AND state IN ('ready','failed') AND lease_token=?) AND ${permission}`).bind(finished,brief?'ready':'failed',trigger==='scheduled'?(next?.at??row.next_run_at):row.next_run_at,trigger==='scheduled'?(next?.date??row.due_local_date):row.due_local_date,trigger==='scheduled'&&!next?new Date(Date.parse(finished)+300000).toISOString():null,trigger==='scheduled'&&!next?claim.attempts:0,finished,actor.tenantId,actor.userId,row.revision,token,run.id,token,actor.tenantId,actor.userId,finished),
 ]);
 if(!results[0].meta.changes){await env.AGENT_DB.prepare("UPDATE mayor_business_routine_runs SET state='discarded',brief_json=NULL,lease_token=NULL,lease_until=NULL,updated_at=? WHERE id=? AND state='processing' AND lease_token=?").bind(finished,run.id,token).run();await env.AGENT_DB.prepare('UPDATE mayor_business_routines SET lease_token=NULL,lease_until=NULL WHERE tenant_id=? AND user_id=? AND lease_token=?').bind(actor.tenantId,actor.userId,token).run();throw new HttpError(409,'routine_result_discarded','Your routines or access changed while preparing the brief. No result was saved.');}
 if(!brief)throw new HttpError(503,'routine_brief_unavailable','The brief could not be prepared. Retry the same request.');
 await requireMembership(env,actor,OPERATORS);return {brief,replay:false};
}
export async function runBusinessRoutineNow(env:Env,actor:Actor,input:{requestId:string},options:RunOptions={}){const request=z.object({requestId:z.uuid()}).strict().parse(input);await requireMembership(env,actor,OPERATORS);const row=await env.AGENT_DB.prepare(configSelect).bind(actor.tenantId,actor.userId).first<ConfigRow>();if(!row)throw new HttpError(409,'routine_config_required','Review and save your selected routines before running a brief.');return executeRoutine(env,actor,row,`manual:${request.requestId}`,'manual',options);}
export async function runBusinessRoutines(env:Env,options:RunOptions={}){
 const now=new Date(options.now??Date.now()).toISOString(),due=await env.AGENT_DB.prepare(`SELECT * FROM mayor_business_routines r WHERE enabled=1 AND next_run_at<=? AND (lease_until IS NULL OR lease_until<=?) AND ${permission.replaceAll('m.tenant_id=?','m.tenant_id=r.tenant_id').replaceAll('m.user_id=?','m.user_id=r.user_id')} ORDER BY next_run_at LIMIT 10`).bind(now,now,now).all<ConfigRow>();let completed=0,failed=0,discarded=0;
 for(const row of due.results){const actor={tenantId:row.tenant_id,userId:row.user_id};try{const result=await executeRoutine(env,actor,row,`scheduled:${row.due_local_date}`,'scheduled',options);if(result.replay){const next=nextCheckRun(JSON.parse(row.schedule_json!),options.now??Date.now(),row.due_local_date??undefined);await env.AGENT_DB.prepare(`UPDATE mayor_business_routines SET next_run_at=?,due_local_date=? WHERE tenant_id=? AND user_id=? AND enabled=1 AND revision=? AND next_run_at=? AND ${permission}`).bind(next.at,next.date,actor.tenantId,actor.userId,row.revision,row.next_run_at,actor.tenantId,actor.userId,now).run();}else completed++;}catch(error){if(error instanceof HttpError&&error.code==='routine_result_discarded')discarded++;else if(error instanceof HttpError&&error.code==='routine_brief_unavailable')failed++;else if(!(error instanceof HttpError&&error.code==='routine_running'))failed++;}}
 return {completed,failed,discarded};
}
export async function routineNotifications(env:Env,actor:Actor){await requireMembership(env,actor,OPERATORS);const rows=await env.AGENT_DB.prepare("SELECT id,updated_at AS created_at,read_at FROM mayor_business_routine_runs WHERE tenant_id=? AND user_id=? AND state='ready' AND read_at IS NULL ORDER BY updated_at DESC,id DESC LIMIT 1").bind(actor.tenantId,actor.userId).all<{id:string;created_at:string;read_at:string|null}>();await requireMembership(env,actor,OPERATORS);return rows.results.map(row=>({id:row.id,title:'Your business brief is ready',message:'Review recorded priorities and draft suggestions in Tasks. Nothing was sent or changed.',action:'tasks',createdAt:row.created_at,read:false}));}
export async function markRoutineBriefRead(env:Env,actor:Actor,id:string){z.uuid().parse(id);await requireMembership(env,actor,OPERATORS);const row=await env.AGENT_DB.prepare("SELECT id FROM mayor_business_routine_runs WHERE id=? AND tenant_id=? AND user_id=? AND state='ready'").bind(id,actor.tenantId,actor.userId).first();if(!row)return null;const now=new Date().toISOString(),result=await env.AGENT_DB.prepare(`UPDATE mayor_business_routine_runs SET read_at=COALESCE(read_at,?) WHERE id=? AND tenant_id=? AND user_id=? AND state='ready' AND ${permission}`).bind(now,id,actor.tenantId,actor.userId,actor.tenantId,actor.userId,now).run();if(!result.meta.changes)throw new HttpError(404,'notification_unavailable','This business brief is not available.');return {read:true};}
export async function handleBusinessRoutinesRequest(request:Request,env:Env,actor:Actor):Promise<Response|null>{
 const match=new URL(request.url).pathname.match(/^\/api\/businesses\/([a-f0-9]{32})\/routines(?:\/(run|brief\/read))?$/);if(!match)return null;if(match[1]!==actor.tenantId)throw new HttpError(404,'workspace_not_found','This workspace is not available.');await requireMembership(env,actor,OPERATORS);
 if(!match[2]&&request.method==='GET')return json(await readBusinessRoutines(env,actor));
 if(request.method==='POST'){requireOrigin(request,env.APP_ORIGIN);if(!match[2])return json(await confirmBusinessRoutines(env,actor,await prepareBusinessRoutines(env,actor,businessRoutineConfigSchema.parse(await readJson(request,8192)))));if(match[2]==='run')return json(await runBusinessRoutineNow(env,actor,z.object({requestId:z.uuid()}).strict().parse(await readJson(request,512))));const input=z.object({id:z.uuid()}).strict().parse(await readJson(request,512)),result=await markRoutineBriefRead(env,actor,input.id);if(!result)throw new HttpError(404,'notification_unavailable','This business brief is not available.');return json(result);}
 throw new HttpError(405,'method_not_allowed','This routine action is unavailable.');
}
