/**
 * Procedural 3D "Mayor" head — 100% authored in code, no external model.
 *
 * Visual identity matches the existing 2D Mayor avatar
 * (client/public/assets/mayor-avatar.png): Pixar-style illustrated man,
 * salt-and-pepper swept hair, brown eyes, graying mustache/goatee, navy
 * suit, white shirt, warm confident expression.
 *
 * Licensing (compliance item 19): every vertex is generated by this file.
 * No downloaded/scraped model, no third-party character IP. Three.js itself
 * is MIT.
 *
 * The mouth is a small bone/scale rig (jaw pivot + lip scaling), NOT morph
 * targets: deterministic, cheap, and directly driven by VisemeWeights from
 * ./lip-sync.ts. Pure three.js core — no DOM/WebGL needed to build or pose
 * the head, so this module is fully testable headless in Node.
 */
import * as THREE from "three";
import type { VisemeWeights } from "./lip-sync.js";

export interface HeadPose {
  yaw: number; // radians, + = turn left
  pitch: number; // radians, + = nod down... (three.js: +x rotation pitches down)
  roll: number; // radians
  lift: number; // vertical offset
}

export interface EyeParams {
  blink: number; // 0..1 (1 = fully closed)
  lookX: number; // -1..1
  lookY: number; // -1..1
}

export interface BrowParams {
  raise: number; // 0..1
  furrow: number; // 0..1
}

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);

const SKIN = 0xd9a077;
const SKIN_DARK = 0xc08a5f;
const HAIR_DARK = new THREE.Color(0x55585f);
const HAIR_GRAY = new THREE.Color(0x9aa0a8);
const LIP = 0xa55a35;
const SUIT = 0x22385e;
const SHIRT = 0xf4f6f8;

function std(color: number | THREE.Color, roughness = 0.65, extra: Record<string, unknown> = {}) {
  return new THREE.MeshStandardMaterial({ color, roughness, metalness: 0.02, ...extra });
}

export interface MayorHeadParts {
  headGroup: THREE.Group;
  torsoGroup: THREE.Group;
  jawGroup: THREE.Group;
  mouthGroup: THREE.Group;
  cavity: THREE.Mesh;
  teeth: THREE.Mesh;
  upperLip: THREE.Mesh;
  eyeL: THREE.Group;
  eyeR: THREE.Group;
  ballL: THREE.Group;
  ballR: THREE.Group;
  browL: THREE.Group;
  browR: THREE.Group;
  cornerL: THREE.Mesh;
  cornerR: THREE.Mesh;
}

export interface MayorHead {
  group: THREE.Group;
  parts: MayorHeadParts;
  setMouth(m: VisemeWeights): void;
  setEyes(e: EyeParams): void;
  setBrows(b: BrowParams): void;
  setPose(p: HeadPose): void;
  setBreath(amount: number): void;
  getStats(): { drawCalls: number; triangles: number };
  dispose(): void;
}

export function buildMayorHead(): MayorHead {
  const group = new THREE.Group();
  const headGroup = new THREE.Group();
  const torsoGroup = new THREE.Group();
  group.add(headGroup, torsoGroup);

  const skin = std(SKIN);
  const skinDark = std(SKIN_DARK);

  // ---- skull + jaw -------------------------------------------------------
  const skull = new THREE.Mesh(new THREE.SphereGeometry(1, 28, 22), skin);
  skull.scale.set(0.85, 1.0, 0.92);
  headGroup.add(skull);

  const chin = new THREE.Mesh(new THREE.SphereGeometry(0.58, 20, 16), skin);
  chin.position.set(0, -0.52, 0.28);
  chin.scale.set(0.88, 0.82, 0.9);
  headGroup.add(chin);

  // ---- hair: swept pompadour, salt-and-pepper vertex colors ---------------
  const hairGeo = new THREE.SphereGeometry(1.07, 36, 24, 0, Math.PI * 2, 0, 1.72);
  {
    const pos = hairGeo.attributes.position;
    const colors = new Float32Array(pos.count * 3);
    const c = new THREE.Color();
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
      const up = THREE.MathUtils.clamp(y / 1.07, 0, 1);
      // sweep toward +x (his left, viewer right — matches the 2D reference)
      const sweep = 0.38 * up * up;
      const front = Math.max(0, z / 1.07); // front of head
      const quiff = 0.34 * front * up * up;
      pos.setX(i, x + sweep);
      pos.setY(i, y + 0.16 * up * up + quiff);
      pos.setZ(i, z * 0.98);
      // salt-and-pepper: gray at temples + streak noise
      const temple = THREE.MathUtils.clamp((Math.abs(x) - 0.55) * 2.2, 0, 1) * (1 - up * 0.4);
      const streak = 0.5 + 0.5 * Math.sin(x * 21 + z * 13 + y * 7);
      const grayAmt = THREE.MathUtils.clamp(temple * 0.85 + streak * 0.28 * up, 0, 1);
      c.copy(HAIR_DARK).lerp(HAIR_GRAY, grayAmt);
      colors[i * 3] = c.r; colors[i * 3 + 1] = c.g; colors[i * 3 + 2] = c.b;
    }
    hairGeo.setAttribute("color", new THREE.BufferAttribute(colors, 3));
    hairGeo.computeVertexNormals();
  }
  const hair = new THREE.Mesh(
    hairGeo,
    new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.9, metalness: 0 }),
  );
  hair.position.set(-0.04, 0.3, -0.08);
  hair.scale.set(0.94, 0.88, 1.0);
  headGroup.add(hair);

  // sideburns
  for (const s of [-1, 1]) {
    const sb = new THREE.Mesh(new THREE.BoxGeometry(0.09, 0.34, 0.16), std(0x8b9097, 0.9));
    sb.position.set(s * 0.88, -0.22, 0.32);
    sb.rotation.z = s * -0.08;
    headGroup.add(sb);
  }

  // ---- ears ---------------------------------------------------------------
  for (const s of [-1, 1]) {
    const ear = new THREE.Mesh(new THREE.SphereGeometry(0.17, 14, 12), skin);
    ear.position.set(s * 0.86, -0.12, -0.06);
    ear.scale.set(0.38, 0.65, 0.55);
    headGroup.add(ear);
  }

  // ---- eyes ---------------------------------------------------------------
  const mkEye = (s: -1 | 1) => {
    const eyeGroup = new THREE.Group();
    eyeGroup.position.set(s * 0.34, 0.06, 0.82);
    const white = new THREE.Mesh(new THREE.SphereGeometry(0.185, 20, 14), std(0xf7f3ec, 0.35));
    white.scale.set(1, 0.8, 0.55);
    const ball = new THREE.Group();
    const iris = new THREE.Mesh(new THREE.SphereGeometry(0.072, 18, 12), std(0x5b3a1e, 0.3));
    iris.position.z = 0.1;
    iris.scale.set(1, 1, 0.5);
    const pupil = new THREE.Mesh(new THREE.SphereGeometry(0.036, 12, 10), std(0x14100c, 0.25));
    pupil.position.z = 0.155;
    pupil.scale.set(1, 1, 0.5);
    const glint = new THREE.Mesh(new THREE.SphereGeometry(0.026, 8, 8), std(0xffffff, 0.2));
    glint.position.set(0.035, 0.04, 0.17);
    ball.add(iris, pupil, glint);
    eyeGroup.add(white, ball);
    headGroup.add(eyeGroup);
    return { eyeGroup, ball };
  };
  const eL = mkEye(-1);
  const eR = mkEye(1);

  // ---- brows ---------------------------------------------------------------
  const mkBrow = (s: -1 | 1) => {
    const pivot = new THREE.Group();
    pivot.position.set(s * 0.34, 0.37, 0.86);
    const brow = new THREE.Mesh(new THREE.CapsuleGeometry(0.036, 0.22, 4, 10), std(0x4a4038, 0.9));
    brow.rotation.z = Math.PI / 2 + s * -0.14;
    brow.position.x = s * 0.05;
    pivot.add(brow);
    headGroup.add(pivot);
    return pivot;
  };
  const browL = mkBrow(-1);
  const browR = mkBrow(1);

  // ---- nose ----------------------------------------------------------------
  const nose = new THREE.Mesh(new THREE.SphereGeometry(0.14, 14, 12), skinDark);
  nose.position.set(0, -0.12, 0.94);
  nose.scale.set(1.0, 0.95, 0.9);
  headGroup.add(nose);

  // ---- facial hair: mustache + chin patch (graying, like the reference) ----
  const facial = std(0x8f8a82, 0.95);
  for (const s of [-1, 1]) {
    const mo = new THREE.Mesh(new THREE.CapsuleGeometry(0.032, 0.17, 4, 8), facial);
    mo.rotation.z = Math.PI / 2 + s * 0.22;
    mo.position.set(s * 0.07, -0.43, 0.92);
    headGroup.add(mo);
  }
  const goatee = new THREE.Mesh(new THREE.SphereGeometry(0.14, 14, 12), facial);
  goatee.position.set(0, -0.76, 0.66);
  goatee.scale.set(1.0, 0.5, 0.45);
  headGroup.add(goatee);

  // ---- mouth rig ------------------------------------------------------------
  // mouthGroup: wide/round/press scaling. jawGroup (pivot near the chin
  // joint): rotation.x opens the jaw. Cavity + teeth + lips inside.
  const mouthGroup = new THREE.Group();
  mouthGroup.position.set(0, -0.54, 0.86);
  headGroup.add(mouthGroup);

  const cavity = new THREE.Mesh(
    new THREE.CircleGeometry(0.16, 20),
    new THREE.MeshStandardMaterial({ color: 0x4a1d1d, roughness: 1 }),
  );
  cavity.position.z = 0.01;
  mouthGroup.add(cavity);

  const teeth = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.07, 0.03), std(0xf5f2ec, 0.4));
  teeth.position.set(0, 0.075, 0.03);
  mouthGroup.add(teeth);

  const upperLip = new THREE.Mesh(new THREE.CapsuleGeometry(0.05, 0.3, 4, 10), std(LIP, 0.7));
  upperLip.rotation.z = Math.PI / 2;
  upperLip.position.set(0, 0.1, 0.035);
  mouthGroup.add(upperLip);

  const jawGroup = new THREE.Group();
  jawGroup.position.set(0, -0.03, -0.04); // pivot: chin joint
  mouthGroup.add(jawGroup);
  const lowerLip = new THREE.Mesh(new THREE.CapsuleGeometry(0.055, 0.26, 4, 10), std(LIP, 0.7));
  lowerLip.rotation.z = Math.PI / 2;
  lowerLip.position.set(0, -0.06, 0.075);
  jawGroup.add(lowerLip);

  const cornerGeo = new THREE.SphereGeometry(0.03, 8, 8);
  const cornerL = new THREE.Mesh(cornerGeo, std(LIP, 0.7));
  const cornerR = new THREE.Mesh(cornerGeo, std(LIP, 0.7));
  cornerL.position.set(-0.26, -0.02, 0.03);
  cornerR.position.set(0.26, -0.02, 0.03);
  mouthGroup.add(cornerL, cornerR);

  // ---- neck + torso (navy suit, white shirt — like the reference) -----------
  const neck = new THREE.Mesh(new THREE.CylinderGeometry(0.27, 0.3, 0.36, 16), skin);
  neck.position.set(0, -1.2, 0.05);
  torsoGroup.add(neck);

  const shoulders = new THREE.Mesh(new THREE.CylinderGeometry(0.95, 1.05, 1.0, 24), std(SUIT, 0.8));
  shoulders.position.set(0, -2.02, -0.05);
  shoulders.scale.set(1.4, 1, 0.72);
  torsoGroup.add(shoulders);

  const shirt = new THREE.Mesh(new THREE.BoxGeometry(0.52, 0.75, 0.12), std(SHIRT, 0.7));
  shirt.position.set(0, -1.9, 0.58);
  shirt.rotation.x = -0.06;
  torsoGroup.add(shirt);
  for (const s of [-1, 1]) {
    const lapel = new THREE.Mesh(new THREE.BoxGeometry(0.22, 0.85, 0.06), std(SUIT, 0.8));
    lapel.position.set(s * 0.36, -1.98, 0.6);
    lapel.rotation.z = s * -0.28;
    lapel.rotation.x = -0.06;
    torsoGroup.add(lapel);
    const collar = new THREE.Mesh(new THREE.BoxGeometry(0.16, 0.3, 0.05), std(SHIRT, 0.7));
    collar.position.set(s * 0.3, -1.78, 0.6);
    collar.rotation.z = s * 1.0;
    torsoGroup.add(collar);
  }

  const parts: MayorHeadParts = {
    headGroup, torsoGroup, jawGroup, mouthGroup, cavity, teeth, upperLip,
    eyeL: eL.eyeGroup, eyeR: eR.eyeGroup, ballL: eL.ball, ballR: eR.ball,
    browL, browR, cornerL, cornerR,
  };

  const baseBrowY = 0.37;

  const api: MayorHead = {
    group,
    parts,

    setMouth(m: VisemeWeights) {
      const jaw = clamp01(m.jawOpen);
      const wide = clamp01(m.mouthWide);
      const round = clamp01(m.mouthRound);
      const press = clamp01(m.lipPress);
      const smile = clamp01(m.smile);

      jawGroup.rotation.x = jaw * 0.55 * (1 - press * 0.7);
      jawGroup.scale.x = 1 + wide * 0.3;

      mouthGroup.scale.set(
        (1 + wide * 0.28) * (1 - round * 0.32),
        (1 - press * 0.85) * (1 - wide * 0.15) + round * 0.25,
        1,
      );
      mouthGroup.position.z = 0.86 + round * 0.1;
      mouthGroup.position.y = -0.54 + smile * 0.02;

      cavity.scale.set(1.35 * (1 + wide * 0.25) * (1 - round * 0.3), 0.3 + jaw * 1.15, 1);
      teeth.visible = jaw > 0.1;
      cavity.visible = jaw > 0.04;
      upperLip.scale.x = 1 + wide * 0.35 - round * 0.2;

      cornerL.position.set(-0.26 - smile * 0.03, -0.02 + smile * 0.1, 0.03);
      cornerR.position.set(0.26 + smile * 0.03, -0.02 + smile * 0.1, 0.03);
    },

    setEyes(e: EyeParams) {
      const blink = clamp01(e.blink);
      const sy = Math.max(0.06, 1 - blink * 0.94);
      eL.eyeGroup.scale.y = sy;
      eR.eyeGroup.scale.y = sy;
      const lx = THREE.MathUtils.clamp(e.lookX, -1, 1);
      const ly = THREE.MathUtils.clamp(e.lookY, -1, 1);
      eL.ball.rotation.y = lx * 0.28;
      eR.ball.rotation.y = lx * 0.28;
      eL.ball.rotation.x = -ly * 0.2;
      eR.ball.rotation.x = -ly * 0.2;
    },

    setBrows(b: BrowParams) {
      const raise = clamp01(b.raise);
      const furrow = clamp01(b.furrow);
      browL.position.y = baseBrowY + raise * 0.13 - furrow * 0.03;
      browR.position.y = baseBrowY + raise * 0.13 - furrow * 0.03;
      browL.rotation.z = furrow * 0.38;
      browR.rotation.z = -furrow * 0.38;
    },

    setPose(p: HeadPose) {
      headGroup.rotation.set(p.pitch, p.yaw, p.roll);
      headGroup.position.y = p.lift;
    },

    setBreath(amount: number) {
      const s = 1 + amount * 0.012;
      torsoGroup.scale.set(1, s, 1);
    },

    getStats() {
      let drawCalls = 0;
      let triangles = 0;
      group.traverse((o) => {
        if ((o as THREE.Mesh).isMesh) {
          drawCalls++;
          const geo = (o as THREE.Mesh).geometry as THREE.BufferGeometry;
          const pos = geo.attributes.position;
          const idx = geo.index;
          triangles += idx ? idx.count / 3 : pos.count / 3;
        }
      });
      return { drawCalls, triangles: Math.round(triangles) };
    },

    dispose() {
      group.traverse((o) => {
        const mesh = o as THREE.Mesh;
        if (mesh.isMesh) {
          mesh.geometry.dispose();
          const mat = mesh.material as THREE.Material | THREE.Material[];
          if (Array.isArray(mat)) mat.forEach((mm) => mm.dispose());
          else mat.dispose();
        }
      });
    },
  };

  // Neutral pose.
  api.setMouth({ jawOpen: 0, mouthWide: 0, mouthRound: 0, lipPress: 0, smile: 0.25 });
  api.setEyes({ blink: 0, lookX: 0, lookY: 0 });
  api.setBrows({ raise: 0, furrow: 0 });
  api.setPose({ yaw: 0, pitch: 0, roll: 0, lift: 0 });
  return api;
}
