// functions/api/_shared/fulfillSproutscore.js
// SproutScore — NYC daycare inspection decoder ($19 single / $29 3-pack).
// Stripe fulfillment for fulfillment='sproutscore' products.
//
// Contract: fulfillSproutscore({ db, env, waitUntil, sendEmail }, payment)
//   db        — D1 binding (shared mehyar_leads_prod; owns sproutscore_orders,
//               sproutscore_credits, sproutscore_suppressions)
//   env       — worker env (SPROUTSCORE_BASE_URL optional, defaults to
//               https://sproutscore.mehyar.us)
//   waitUntil — Pages Functions waitUntil (optional; falls back to await)
//   sendEmail — injected mailer: sendEmail(env, {from, fromName, to, replyTo,
//               subject, text, html, headers}) -> {ok, ...}. NEVER sends in
//               local dev: the caller injects a stub. In prod, mehyar-web
//               injects a wrapper around sendCloudflareEmail.
//   payment   — billing_payments row {id, product_id, email, access_token,
//               metadata_json}. metadata_json is the checkout params FLAT
//               (see checkout.js) — intake accepted flat or {inputs:{...}}.
//
// Behavior:
//   1. Idempotent by construction: exactly one sproutscore_orders row per
//      payment.id (UNIQUE index idx_sproutscore_orders_payment). Replays
//      return {replay:true} and do nothing, send nothing twice.
//   2. Token unification: the order REUSES billing_payments.access_token
//      (the token Stripe's success_url was rendered with at checkout —
//      minting a new one orphans the success page, cf. 2026-09-16 payment 68
//      lesson). One token gates the success page, the status API, the
//      report page, and the unsubscribe link.
//   3. Single report SKU: deterministic decode runs in the background
//      (waitUntil); on success the order is marked ready and the buyer is
//      emailed the token-gated report link. On failure the order is marked
//      failed and NO email goes out — the success page shows live status +
//      retry (POST /api/sproutscore/status {action:"retry"}).
//   4. 3-pack SKU: creates the order with bundle_slots=3 plus three
//      sproutscore_credits rows (available/used per slot). The buyer gets
//      the center-picker link immediately; no generation at webhook time.
//      The product PWA consumes slots against sproutscore_credits (same D1,
//      LEADS_DB binding) — see SLOT CONTRACT below.
//   5. Generation is DETERMINISTIC from the bundled dataset snapshot
//      (./sproutscoreData.js: 3,014 centers + 478-code violation translation
//      table, NYC DOHMH via NYC Open Data dsg6-ifza, data through
//      2023-04-24). No live AI generation in this path; no Socrata calls at
//      webhook time. Every report carries the stale-data banner
//      (data_source:"snapshot").
//
// SLOT CONTRACT (for the sproutscore.mehyar.us PWA, same D1):
//   - sproutscore_credits: one row per (order_id, slot_no 1..3), status
//     'available'|'used'. To consume a slot for a center: UPDATE
//     sproutscore_credits SET status='used', center_id=?, center_name=?,
//     used_at=<now> WHERE order_id=? AND slot_no=? AND status='available'
//     — the affected-row count decides who won the race (exactly-once).
//   - Per-center decoded reports are generated by the PWA from the same
//     dataset and stored in the PWA's own tables; the order row's
//     output_json covers the single-report SKU only.

const nowSql = "strftime('%Y-%m-%dT%H:%M:%fZ','now')";

const SKUS = {
  "sproutscore-report": { slots: 0, name: "SproutScore Decoded Report" },
  "sproutscore-3pack": { slots: 3, name: "SproutScore 3-Pack" },
};

function randomToken(bytes = 32) {
  const b = crypto.getRandomValues(new Uint8Array(bytes));
  return [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
}

function baseUrl(env) {
  return String(env.SPROUTSCORE_BASE_URL || "https://sproutscore.mehyar.us").replace(/\/+$/, "");
}

function fromAddress() {
  // Until sproutscore.mehyar.us is onboarded on both ESPs (standing rule),
  // send from the proven mehyar.us identity.
  return { from: "team@mehyar.us", fromName: "SproutScore" };
}

function unsubscribeUrl(env, email, token) {
  return (
    "https://mehyar.us/api/sproutscore/unsubscribe?email=" +
    encodeURIComponent(email) +
    "&token=" +
    encodeURIComponent(token)
  );
}

function listUnsubscribeHeaders(env, email, token) {
  const u = unsubscribeUrl(env, email, token);
  return { "List-Unsubscribe": `<${u}>`, "List-Unsubscribe-Post": "List-Unsubscribe=One-Click" };
}

async function ensureSchema(db) {
  // Belt and suspenders: the webhook must never fail on a missing table.
  // D1 enforces foreign keys — these tables reference nothing, so plain
  // CREATE TABLE IF NOT EXISTS is safe (never DROP+RENAME).
  await db.prepare(
    "CREATE TABLE IF NOT EXISTS sproutscore_orders (" +
      "id INTEGER PRIMARY KEY AUTOINCREMENT, " +
      "payment_id INTEGER NOT NULL, " +
      "product_id TEXT NOT NULL, " +
      "email TEXT NOT NULL, " +
      "inputs_json TEXT NOT NULL DEFAULT '{}', " +
      "bundle_slots INTEGER, " +
      "status TEXT NOT NULL DEFAULT 'paid', " +
      "access_token TEXT NOT NULL, " +
      "output_json TEXT, " +
      "email_sent_at TEXT, " +
      "ready_at TEXT, " +
      "failure_reason TEXT, " +
      "created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')))"
  ).run();
  await db.prepare(
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_sproutscore_orders_payment ON sproutscore_orders(payment_id)"
  ).run();
  await db.prepare(
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_sproutscore_orders_token ON sproutscore_orders(access_token)"
  ).run();
  await db.prepare(
    "CREATE TABLE IF NOT EXISTS sproutscore_credits (" +
      "id INTEGER PRIMARY KEY AUTOINCREMENT, " +
      "order_id INTEGER NOT NULL, " +
      "slot_no INTEGER NOT NULL, " +
      "center_id TEXT, " +
      "center_name TEXT, " +
      "status TEXT NOT NULL DEFAULT 'available', " +
      "used_at TEXT, " +
      "UNIQUE(order_id, slot_no))"
  ).run();
  await db.prepare(
    "CREATE TABLE IF NOT EXISTS sproutscore_suppressions (" +
      "email TEXT PRIMARY KEY, " +
      "reason TEXT NOT NULL DEFAULT 'unsubscribe_request', " +
      "source TEXT NOT NULL DEFAULT 'sproutscore', " +
      "created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')))"
  ).run();
}

function readIntake(payment) {
  let meta = {};
  try {
    meta = JSON.parse(payment.metadata_json || "{}") || {};
  } catch {}
  const flat = meta && typeof meta === "object" && meta.inputs && typeof meta.inputs === "object" ? meta.inputs : meta;
  const pick = (o, k) => (o && typeof o[k] === "string" ? o[k].slice(0, 500).trim() : "");
  return {
    center_id: pick(flat, "center_id"),
    center_name: pick(flat, "center_name"),
    email: payment.email || "",
  };
}

// ── Deterministic report generation ────────────────────────────────────────
// Real dataset: NYC DOHMH via NYC Open Data (dsg6-ifza), bundled as a compact
// lookup in ./sproutscoreData.js (built by
// ~/workspace/sproutscore/build/build-sproutscore-bundle.js — deterministic,
// no live AI, no network at webhook time). Loaded lazily so cold starts for
// unrelated routes never pay the parse cost.
//
// Report JSON matches ~/workspace/sproutscore/data/data-model.md section (b).
// Every report carries the stale-data banner: city data ends 2023-04-24 —
// never imply recent/live data. CORRECTED = the city recorded a fix;
// OPEN = no correction on record by Apr 2023, NOT proof it is still broken.

const SPROUT_DATA_AS_OF = "2023-04-24";
const SPROUT_SOURCE = "NYC DOHMH via NYC Open Data (dsg6-ifza)";

const STALE_BANNER =
  "Inspection history: 2020–2023. The city has not published newer daycare " +
  "inspection data since April 2023 — always confirm current conditions on your tour.";
const DATA_CAVEAT = "City inspection data ends April 2023. Newer inspections are not published.";
const BUNDLE_DOWN_COPY =
  "We can't reach the city's inspection records right now. Your report will be " +
  "ready as soon as they're back — nothing was charged for missing data.";
function centerNotFoundCopy(name) {
  return (
    `We couldn't find "${name}" in NYC's published daycare inspection records ` +
    `(2020–2023). Check the spelling, or try the legal name on the center's door. ` +
    `Newer centers may not appear — the city's public data ends in April 2023.`
  );
}
function lowDataCopy(n) {
  return `Only ${n} inspection(s) on record — too few to judge a pattern. Treat this as a starting point, not a verdict.`;
}

// User-facing copy for a failed order, shown by /api/sproutscore/status.
export function sproutscoreErrorCopy(reason, centerName) {
  if (reason === "center_not_found") return centerNotFoundCopy(centerName || "that center");
  if (reason === "bundle_unavailable") return BUNDLE_DOWN_COPY;
  return "We couldn't generate this report. Please retry — if it still fails, reply to your receipt email and we'll make it right.";
}

const COHORT_LABELS = {
  "Child Care - Pre School": "preschool",
  "School Based Child Care": "school-based child care",
  "Child Care - Infants/Toddlers": "infant/toddler care",
  Camp: "camp",
};

let sproutDataCache = null;
async function loadSproutData() {
  if (sproutDataCache) return sproutDataCache;
  const mod = await import("./sproutscoreData.js");
  sproutDataCache = { meta: mod.SPROUT_META, centers: mod.SPROUT_CENTERS, codes: mod.SPROUT_CODES };
  return sproutDataCache;
}

function findSproutCenter(centers, centerId, centerName) {
  const id = String(centerId || "").trim().toLowerCase();
  if (id) {
    const hit = centers.find((c) => String(c.id).toLowerCase() === id);
    if (hit) return hit;
  }
  const q = String(centerName || "").trim().toLowerCase();
  if (q) {
    const keyHit = centers.find((c) => (c.keys || []).some((k) => String(k).toLowerCase() === q));
    if (keyHit) return keyHit;
    const nameHit = centers.find(
      (c) => String(c.name).toLowerCase().includes(q) || q.includes(String(c.name).toLowerCase())
    );
    if (nameHit) return nameHit;
  }
  return null;
}

const SEV_RANK = { critical: 0, major: 1, minor: 2 };
function sevRank(s) { return SEV_RANK[s] !== undefined ? SEV_RANK[s] : 3; }
function dateDesc(a, b) { return a < b ? 1 : a > b ? -1 : 0; }

function cohortAvgPct(meta, cohort) {
  const table = (meta && meta.cohort_avg_violation_rate_pct) || {};
  const v = parseFloat(table[cohort]);
  if (Number.isFinite(v)) return v;
  const g = parseFloat(meta && meta.global_flagged_rate_pct);
  return Number.isFinite(g) ? g : 30.9;
}

function round1(x) { return Math.round(x * 10) / 10; }

// Pure + deterministic: same center, same report, every time. No AI.
// Returns {ok:true, report} or {ok:false, error:"center_not_found"|"bundle_unavailable"}.
export async function buildSproutscoreReport(centerId, centerName) {
  const data = await loadSproutData().catch(() => null);
  if (!data) return { ok: false, error: "bundle_unavailable" };
  const { meta, centers, codes } = data;
  const c = findSproutCenter(centers, centerId, centerName);
  if (!c) return { ok: false, error: "center_not_found" };

  // Decode every violation through the translation table (never paraphrased).
  const decoded = [];
  for (const v of c.viol || []) {
    const t = codes[v[0]];
    if (!t) continue; // build-time validated to zero; skip honestly if ever hit
    decoded.push({
      code: v[0],
      date: v[1],
      inspection: v[2],
      city_category: v[3],
      status: v[4],
      severity: t[1],
      what_happened: t[0],
      city_text: t[5],
      status_plain: t[2],
      tour_question: t[3],
      family: t[4],
    });
  }
  decoded.sort((a, b) => sevRank(a.severity) - sevRank(b.severity) || dateDesc(a.date, b.date));

  const bySeverity = { critical: 0, major: 0, minor: 0 };
  let openNow = 0;
  let corrected = 0;
  for (const d of decoded) {
    if (bySeverity[d.severity] !== undefined) bySeverity[d.severity]++;
    if (d.status === "OPEN") openNow++;
    if (d.status === "CORRECTED") corrected++;
  }

  // NYC-average comparison against the center's program cohort (never one
  // citywide number for every cohort).
  const avg = cohortAvgPct(meta, c.cohort);
  let centerRate = parseFloat(c.rate);
  if (!Number.isFinite(centerRate)) centerRate = c.insp > 0 ? (c.flag / c.insp) * 100 : 0;
  centerRate = round1(centerRate);
  const ratio = avg > 0 ? centerRate / avg : 99;
  const verdict = ratio < 0.8 ? "below_average" : ratio <= 1.2 ? "near_average" : "above_average";
  const label = COHORT_LABELS[c.cohort] || String(c.cohort || "child care");
  const verdictWord = verdict === "above_average" ? "above" : verdict === "below_average" ? "below" : "near";
  const vsNyc = {
    center_violation_rate_pct: centerRate,
    nyc_avg_pct: avg,
    verdict,
    plain: `Flagged in ${c.flag} of ${c.insp} inspections — ${verdictWord} the NYC average for ${label} (${round1(avg)}%).`,
  };

  // Nearby comparison: same ZIP; widen to borough when fewer than 5 centers.
  const flaggedRate = (x) => (x.insp > 0 ? x.flag / x.insp : 0);
  let pool = centers.filter((x) => x.boro === c.boro);
  let scopeLabel = c.boro || "NYC";
  if (c.zip) {
    const zipPool = centers.filter((x) => x.zip === c.zip);
    if (zipPool.length >= 5) {
      pool = zipPool;
      scopeLabel = `ZIP ${c.zip}`;
    }
  }
  const myRate = flaggedRate(c);
  const nearbyAvg = pool.length ? pool.reduce((s, x) => s + flaggedRate(x), 0) / pool.length : 0;
  const rank = 1 + pool.filter((x) => flaggedRate(x) < myRate).length;
  const m = pool.length;
  const rankNote =
    rank === 1 ? " (cleanest)" : rank * 2 > m ? " (more flagged than most nearby centers)" : "";
  const nearbyPlain =
    rank === 1
      ? `The cleanest record among the ${m} centers in ${scopeLabel}.`
      : rank * 2 <= m
        ? `Fewer flags than most of the ${m} centers in ${scopeLabel}.`
        : `More flagged than most of the ${m} centers in ${scopeLabel}.`;

  // Tour checklist: one question per distinct violation family, newest
  // violation's wording wins, deduplicated.
  const byFamily = new Map();
  for (const d of decoded) {
    const prev = byFamily.get(d.family);
    if (!prev || d.date > prev.date) byFamily.set(d.family, d);
  }
  const famList = [...byFamily.values()].sort(
    (a, b) => sevRank(a.severity) - sevRank(b.severity) || dateDesc(a.date, b.date)
  );
  const tourChecklist = [];
  for (const d of famList) {
    if (d.tour_question && !tourChecklist.includes(d.tour_question)) tourChecklist.push(d.tour_question);
  }

  const capNum = parseFloat(c.cap);
  const violations = decoded.map((d) => {
    const { family, ...rest } = d;
    return rest;
  });
  return {
    ok: true,
    report: {
      report_version: "sproutscore-v1",
      data_source: "snapshot",
      source: SPROUT_SOURCE,
      data_as_of: SPROUT_DATA_AS_OF,
      data_caveat: DATA_CAVEAT,
      stale_banner: STALE_BANNER,
      low_data_caveat: c.insp < 3 ? lowDataCopy(c.insp) : null,
      generated_at: new Date().toISOString(),
      deterministic: true,
      center: {
        center_id: c.id,
        name: c.name,
        address: c.addr,
        borough: c.boro,
        zipcode: c.zip,
        phone: c.phone,
        agerange: c.age,
        maximumcapacity: Number.isFinite(capNum) ? capNum : c.cap,
        programtype: c.prog,
      },
      summary: {
        inspections: c.insp,
        flagged: c.flag,
        clean: c.clean,
        violations_total: decoded.length,
        by_severity: bySeverity,
        open_now: openNow,
        corrected,
        last_inspection: c.last,
        data_as_of: SPROUT_DATA_AS_OF,
      },
      violations,
      comparison: {
        vs_nyc_avg: vsNyc,
        vs_nearby: {
          scope: scopeLabel,
          centers: m,
          nearby_avg_flagged_rate: Math.round(nearbyAvg * 100) / 100,
          rank: `${rank} of ${m}${rankNote}`,
          plain: nearbyPlain,
        },
      },
      tour_checklist: tourChecklist,
      printable_pdf: {
        sections: [
          "cover (center, as-of date, caveat)",
          "at-a-glance summary",
          "every violation decoded (date, what happened, severity, fixed or not)",
          "how this center compares (NYC avg + nearby)",
          "tour checklist (tear-off questions)",
          "methodology & sources",
        ],
      },
    },
  };
}

async function generateReport(env, intake) {
  return buildSproutscoreReport(intake.center_id, intake.center_name);
}

// Runs the single-report generation for an existing order row and emails the
// buyer on success. Never throws: failures mark the order failed (no email).
export async function runSproutscoreGeneration(db, env, sendEmail, orderId) {
  let order;
  try {
    order = await db
      .prepare("SELECT id, payment_id, product_id, email, inputs_json, status, access_token FROM sproutscore_orders WHERE id = ?")
      .bind(orderId)
      .first();
  } catch (e) {
    console.error("fulfillSproutscore generation entry failed", orderId, e && e.message);
    return { ok: false, error: "db_error" };
  }
  if (!order || order.status === "ready") return { ok: true, replay: order && order.status === "ready" };
  let intake = {};
  try { intake = JSON.parse(order.inputs_json || "{}") || {}; } catch {}
  if (!intake.center_id && !intake.center_name) {
    // No center yet — the success page acts as the picker (see status.js
    // set-center). Not a failure; leave the order in paid.
    return { ok: true, awaiting_center: true };
  }
  await db.prepare(`UPDATE sproutscore_orders SET status='generating', failure_reason=NULL WHERE id=? AND status!='ready'`)
    .bind(orderId).run();
  try {
    const built = await generateReport(env, intake);
    if (!built.ok) {
      await db.prepare("UPDATE sproutscore_orders SET status='failed', failure_reason=? WHERE id=? AND status!='ready'")
        .bind(built.error, orderId).run();
      // No email: the status endpoint shows the honest degradation copy.
      return { ok: false, error: built.error };
    }
    const report = built.report;
    const outputJson = JSON.stringify(report);
    await db.prepare(
      `UPDATE sproutscore_orders SET status='ready', output_json=?, ready_at=${nowSql} WHERE id=? AND status!='ready'`
    ).bind(outputJson, orderId).run();

    const reportUrl = `${baseUrl(env)}/report.html?token=${order.access_token}`;
    const { from, fromName } = fromAddress();
    const centerName = report.center.name;
    const s = report.summary;
    const bs = s.by_severity;
    const cmp = report.comparison;
    const topViolations = report.violations.slice(0, 5).map(
      (v) => `- [${String(v.severity).toUpperCase()}] ${v.code} (${v.date}, ${v.status}): ${v.what_happened}`
    );
    if (report.violations.length > 5) topViolations.push(`- ...and ${report.violations.length - 5} more decoded in the full report.`);
    const checklist = report.tour_checklist.map((q, i) => `${i + 1}. ${q}`);
    const unsub = unsubscribeUrl(env, order.email, order.access_token);
    const subject = `Your SproutScore decoded report is ready — ${centerName}`;
    const text =
      `Your decoded inspection report for ${centerName} is ready:\n${reportUrl}\n\n` +
      `At a glance (${s.inspections} inspections, ${s.flagged} flagged, ${s.violations_total} violations decoded):\n` +
      `- Critical: ${bs.critical} · Major: ${bs.major} · Minor: ${bs.minor}\n` +
      `- Corrected: ${s.corrected} · No correction on record: ${s.open_now}\n` +
      `- ${cmp.vs_nyc_avg.plain}\n` +
      `- ${cmp.vs_nearby.plain}\n\n` +
      `Worst violations first:\n${topViolations.join("\n")}\n\n` +
      `Tour checklist — ask these on your visit:\n${checklist.join("\n")}\n\n` +
      `${report.stale_banner}\n\n` +
      `Full report: ${reportUrl}\n\n` +
      `This link is personal to you — keep it somewhere safe.\n\n` +
      `Unsubscribe from SproutScore updates: ${unsub}\n\n-- ${fromName}`;
    const html =
      `<p>Your decoded inspection report for <strong>${escapeHtml(centerName)}</strong> is ready.</p>` +
      `<p><a href="${reportUrl}" style="display:inline-block;background:#166534;color:#fff;padding:12px 28px;border-radius:8px;text-decoration:none;font-weight:bold;">View your decoded report</a></p>` +
      `<p style="color:#374151;">At a glance: <strong>${s.violations_total}</strong> violations decoded ` +
      `(${bs.critical} critical, ${bs.major} major, ${bs.minor} minor) across ` +
      `${s.inspections} inspections.<br>${escapeHtml(cmp.vs_nyc_avg.plain)}<br>${escapeHtml(cmp.vs_nearby.plain)}</p>` +
      `<p style="color:#374151;">${escapeHtml(report.stale_banner)}</p>` +
      `<p style="color:#6b7280;font-size:13px;">Or copy this link:<br><a href="${reportUrl}">${reportUrl}</a></p>` +
      `<p style="color:#6b7280;font-size:13px;">This link is personal to you — keep it somewhere safe.</p>` +
      `<p style="color:#9ca3af;font-size:12px;"><a href="${unsub}">Unsubscribe</a> from SproutScore updates.</p>` +
      `<p>-- ${fromName}</p>`;
    const result = await sendEmail(env, {
      from, fromName, to: order.email, replyTo: "info@mehyar.us",
      subject, text, html, headers: listUnsubscribeHeaders(env, order.email, order.access_token),
    });
    if (!result.ok) {
      console.error("fulfillSproutscore report email failed", orderId, result.error);
    } else {
      await db.prepare(`UPDATE sproutscore_orders SET email_sent_at=${nowSql} WHERE id=?`).bind(orderId).run();
    }
    return { ok: true, order_id: orderId, email_ok: !!result.ok };
  } catch (e) {
    console.error("fulfillSproutscore generation failed", orderId, e && e.message);
    try {
      await db.prepare("UPDATE sproutscore_orders SET status='failed', failure_reason=? WHERE id=? AND status!='ready'")
        .bind(String((e && e.message) || e).slice(0, 300), orderId).run();
    } catch {}
    // No email on failure: the buyer lands on success.html?token= from
    // Stripe, which shows live status + a retry button.
    return { ok: false, error: "generation_failed" };
  }
}

function escapeHtml(s) {
  return String(s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

export async function fulfillSproutscore({ db, env, waitUntil, sendEmail }, payment) {
  if (!db || !payment || !payment.id) throw new Error("fulfillSproutscore: bad args");
  await ensureSchema(db);

  const productId = payment.product_id;
  const sku = SKUS[productId];
  if (!sku) {
    console.error("fulfillSproutscore: unknown product", productId);
    return { ok: false, error: "unknown_product" };
  }

  // ── idempotent order create (one row per payment) ──
  const existing = await db
    .prepare("SELECT id, access_token, status, product_id FROM sproutscore_orders WHERE payment_id = ?")
    .bind(payment.id)
    .first();
  if (existing) {
    return { ok: true, replay: true, order_id: existing.id, status: existing.status };
  }

  const intake = readIntake(payment);
  // Token unification: reuse the checkout-time access_token (the token
  // Stripe's success_url was rendered with). Mint + persist only if missing.
  let orderToken = payment.access_token;
  if (!orderToken || String(orderToken).length < 16) {
    orderToken = randomToken(32);
    await db.prepare("UPDATE billing_payments SET access_token = ? WHERE id = ?").bind(orderToken, payment.id).run();
  }

  const ins = await db
    .prepare(
      "INSERT INTO sproutscore_orders (payment_id, product_id, email, inputs_json, bundle_slots, status, access_token) " +
        "VALUES (?, ?, ?, ?, ?, 'paid', ?)"
    )
    .bind(payment.id, productId, payment.email, JSON.stringify(intake), sku.slots || null, orderToken)
    .run();
  const orderId = ins.meta.last_row_id;

  const { from, fromName } = fromAddress();

  // ── 3-pack: credits + picker email, no generation yet ──
  if (sku.slots > 0) {
    for (let slot = 1; slot <= sku.slots; slot++) {
      await db.prepare(
        "INSERT OR IGNORE INTO sproutscore_credits (order_id, slot_no, status) VALUES (?, ?, 'available')"
      ).bind(orderId, slot).run();
    }
    const pickerUrl = `${baseUrl(env)}/success.html?token=${orderToken}`;
    const unsub = unsubscribeUrl(env, payment.email, orderToken);
    const subject = `Your ${sku.name} is ready — pick your 3 centers`;
    const text =
      `Thanks for your purchase!\n\n` +
      `Your ${sku.name} is paid. Decode any 3 NYC daycare centers — compare them side by side:\n${pickerUrl}\n\n` +
      `Pick a center and its decoded report is generated on the spot: every violation ` +
      `in plain English, tour questions, and a printable version.\n\n` +
      `This link is personal to you — keep it somewhere safe.\n\n` +
      `Unsubscribe from SproutScore updates: ${unsub}\n\n-- ${fromName}`;
    const html =
      `<p>Thanks for your purchase!</p>` +
      `<p>Your <strong>${sku.name}</strong> is paid. Decode any 3 NYC daycare centers — compare them side by side.</p>` +
      `<p><a href="${pickerUrl}" style="display:inline-block;background:#166534;color:#fff;padding:12px 28px;border-radius:8px;text-decoration:none;font-weight:bold;">Pick your 3 centers</a></p>` +
      `<p style="color:#6b7280;font-size:13px;">Or copy this link:<br><a href="${pickerUrl}">${pickerUrl}</a></p>` +
      `<p style="color:#6b7280;font-size:13px;">Pick a center and its decoded report is generated on the spot. This link is personal to you — keep it somewhere safe.</p>` +
      `<p style="color:#9ca3af;font-size:12px;"><a href="${unsub}">Unsubscribe</a> from SproutScore updates.</p>` +
      `<p>-- ${fromName}</p>`;
    const result = await sendEmail(env, {
      from, fromName, to: payment.email, replyTo: "info@mehyar.us",
      subject, text, html, headers: listUnsubscribeHeaders(env, payment.email, orderToken),
    });
    if (!result.ok) console.error("fulfillSproutscore 3-pack email failed", productId, result.error);
    else await db.prepare(`UPDATE sproutscore_orders SET email_sent_at=${nowSql} WHERE id=?`).bind(orderId).run();
    return { ok: true, order_id: orderId, mode: "bundle", slots: sku.slots, email_ok: !!result.ok };
  }

  // ── single report: background generation, then email ──
  const run = () => runSproutscoreGeneration(db, env, sendEmail, orderId).catch((e) => {
    console.error("fulfillSproutscore background run threw", orderId, e && e.message);
  });
  if (typeof waitUntil === "function") waitUntil(run());
  else await run();

  return { ok: true, order_id: orderId, mode: "single" };
}
